const supabaseUrl="https://dtjhuejmxrjkcxzvilgw.supabase.co",supabaseKey="sb_publishable_kwXvFOCpknkDf9BKmcszrQ_Q7IBVg87";
const supabaseClient=window.supabase.createClient(supabaseUrl,supabaseKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
let currentAdmin=null,customers=[],notes=[],openCustomerId=null;const pendingCustomerCards=new Set();
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':'&quot;'}[c]));
async function guard(){const {data}=await supabaseClient.auth.getSession(),u=data?.session?.user;if(!u){location.replace('admin.html');return false}const {data:p}=await supabaseClient.from('customers').select('is_admin,blocked,admin_role').eq('id',u.id).maybeSingle();if(p?.is_admin!==true||p?.blocked===true){location.replace('admin-home.html');return false}currentAdmin={...u,admin_role:p.admin_role};document.body.classList.add('auth-ready');document.body.classList.remove('auth-pending');return true}
async function load(){const [c,n]=await Promise.all([supabaseClient.from('customers').select('id,name,phone,approved,blocked').eq('is_admin',false).order('name'),supabaseClient.from('customer_admin_notes').select('id,customer_id,customer_name,note_text,created_at,created_by_name').order('created_at',{ascending:false})]);if(c.error)return alert('거래처 조회 실패: '+c.error.message);if(n.error)return alert('메모 조회 실패: '+n.error.message+'\n\nV6.6.69 SQL을 먼저 실행해주세요.');customers=c.data||[];notes=n.data||[];fillSelect();render()}
function fillSelect(){const used=new Set(notes.map(n=>n.customer_id));$('newCustomerSelect').innerHTML='<option value="">거래처를 선택하세요</option>'+customers.filter(c=>!used.has(c.id)).map(c=>`<option value="${esc(c.id)}">${esc(c.name||'이름없음')}${c.phone?` · ${esc(c.phone)}`:''}</option>`).join('')}
function grouped(){const map=new Map();for(const n of notes){if(!map.has(n.customer_id))map.set(n.customer_id,{id:n.customer_id,name:n.customer_name||'거래처',notes:[]});map.get(n.customer_id).notes.push(n)}for(const id of pendingCustomerCards){if(!map.has(id)){const c=customers.find(x=>x.id===id);if(c)map.set(id,{id,name:c.name||'거래처',notes:[]})}}return [...map.values()]}
function render(){let rows=grouped(),q=$('customerNoteSearch').value.trim().toLowerCase(),sort=$('customerNoteSort').value;if(q)rows=rows.filter(g=>g.name.toLowerCase().includes(q));if(sort==='name')rows.sort((a,b)=>a.name.localeCompare(b.name,'ko'));else if(sort==='count')rows.sort((a,b)=>b.notes.length-a.notes.length||a.name.localeCompare(b.name,'ko'));else rows.sort((a,b)=>new Date(b.notes[0]?.created_at||0)-new Date(a.notes[0]?.created_at||0));$('customerNotesList').innerHTML=rows.length?rows.map(g=>card(g)).join(''):'<div class="empty-notes">등록된 거래처 관리메모가 없습니다.<br>위의 ‘거래처 추가’로 시작하세요.</div>';document.querySelectorAll('[data-customer-toggle]').forEach(b=>b.onclick=()=>{openCustomerId=openCustomerId===b.dataset.customerToggle?null:b.dataset.customerToggle;render()});document.querySelectorAll('[data-note-add]').forEach(b=>b.onclick=()=>addNote(b.dataset.noteAdd));document.querySelectorAll('[data-note-delete]').forEach(b=>b.onclick=()=>deleteNote(b.dataset.noteDelete))}
function card(g){const open=openCustomerId===g.id,last=g.notes[0],entries=g.notes.map((n,i)=>`<div class="note-entry"><p><b>${i+1}.</b> ${esc(n.note_text)}</p><footer><span>${esc(n.created_by_name||'관리자')} · ${new Date(n.created_at).toLocaleString('ko-KR')}</span><button type="button" data-note-delete="${n.id}">삭제</button></footer></div>`).join('');return `<article class="customer-note-card ${open?'open':''}"><button type="button" class="customer-note-summary" data-customer-toggle="${g.id}"><strong>${esc(g.name)}</strong><span>메모 ${g.notes.length}개</span><em>${last?`최근 ${new Date(last.created_at).toLocaleDateString('ko-KR')}`:''}</em><span class="chevron">⌄</span></button>${open?`<div class="customer-note-body">${entries}<div class="note-compose"><textarea id="note-input-${g.id}" maxlength="1000" placeholder="${esc(g.name)} 거래처에 새 메모 추가"></textarea><button type="button" data-note-add="${g.id}">메모 추가</button></div></div>`:''}</article>`}
async function createCard(){const id=$('newCustomerSelect').value,c=customers.find(x=>x.id===id);if(!c)return alert('거래처를 선택해주세요.');$('newCustomerPanel').hidden=true;pendingCustomerCards.add(id);openCustomerId=id;render();setTimeout(()=>$(`note-input-${id}`)?.focus(),0)}
async function addNote(id){const input=$(`note-input-${id}`),text=input?.value.trim();if(!text)return alert('메모 내용을 입력해주세요.');const c=customers.find(x=>x.id===id),adminProfile=await supabaseClient.from('customers').select('name').eq('id',currentAdmin.id).maybeSingle();const {error}=await supabaseClient.from('customer_admin_notes').insert({customer_id:id,customer_name:c?.name||'',note_text:text,created_by:currentAdmin.id,created_by_name:adminProfile.data?.name||currentAdmin.email||'관리자'});if(error)return alert('메모 저장 실패: '+error.message);pendingCustomerCards.delete(id);await load();openCustomerId=id;render()}
async function deleteNote(id){if(!confirm('이 메모를 삭제할까요?'))return;const target=notes.find(n=>String(n.id)===String(id)),cid=target?.customer_id;const {error}=await supabaseClient.from('customer_admin_notes').delete().eq('id',id);if(error)return alert('메모 삭제 실패: '+error.message);await load();openCustomerId=cid;render()}
(async()=>{if(!await guard())return;$('addCustomerCardBtn').onclick=()=>{$('newCustomerPanel').hidden=false;$('newCustomerSelect').focus()};$('cancelCustomerCardBtn').onclick=()=>{$('newCustomerPanel').hidden=true};$('createCustomerCardBtn').onclick=createCard;$('customerNoteSearch').oninput=render;$('customerNoteSort').onchange=render;await load()})();
