const supabaseUrl="https://dtjhuejmxrjkcxzvilgw.supabase.co",supabaseKey="sb_publishable_kwXvFOCpknkDf9BKmcszrQ_Q7IBVg87";
const supabaseClient=window.supabase.createClient(supabaseUrl,supabaseKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
let currentAdmin=null,customers=[],allProfiles=[],notes=[],openCustomerId=null,selectedNewCustomerId=null;const pendingCustomerCards=new Set();
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':'&quot;'}[c]));
const KOREAN_INITIALS='ㄱㄲㄴㄷㄸㄹㅁㅂㅃㅅㅆㅇㅈㅉㅊㅋㅌㅍㅎ';
function koreanInitialText(value){return[...String(value||'').normalize('NFKC')].map(char=>{const code=char.charCodeAt(0)-0xAC00;return code>=0&&code<=11171?KOREAN_INITIALS[Math.floor(code/588)]:char}).join('')}
function norm(value){return String(value||'').trim().normalize('NFKC').replace(/\s+/g,'').toLowerCase()}
function lookupMatches(label,query){const needle=norm(query);if(!needle)return true;const source=String(label||'');return norm(source).includes(needle)||norm(koreanInitialText(source)).includes(needle)}
function lookupRank(label,query){const needle=norm(query);if(!needle)return 0;const source=norm(label),initials=norm(koreanInitialText(label));if(source===needle)return 0;if(source.startsWith(needle))return 1;if(initials===needle)return 2;if(initials.startsWith(needle))return 3;if(source.includes(needle))return 4;if(initials.includes(needle))return 5;return 99}
function customerSearchCompare(a,b,q){return lookupRank(a.business_name||a.owner_name||'',q)-lookupRank(b.business_name||b.owner_name||'',q)||String(a.business_name||a.owner_name||'').localeCompare(String(b.business_name||b.owner_name||''),'ko',{numeric:true})}
function customerName(c){return String(c?.business_name||c?.owner_name||c?.email||'거래처').trim()}
async function guard(){const {data}=await supabaseClient.auth.getSession(),u=data?.session?.user;if(!u){location.replace('admin.html');return false}const {data:p}=await supabaseClient.from('customers').select('is_admin,blocked,admin_role,business_name,owner_name').eq('id',u.id).maybeSingle();if(p?.is_admin!==true||p?.blocked===true){location.replace('admin-home.html');return false}currentAdmin={...u,...p};document.body.classList.add('auth-ready');document.body.classList.remove('auth-pending');return true}
async function load(){const [c,n,m]=await Promise.all([supabaseClient.from('customers').select('id,business_name,owner_name,email,phone,is_admin,approved,blocked').order('business_name',{ascending:true}),supabaseClient.from('customer_admin_notes').select('id,customer_id,memo,created_at,created_by').order('created_at',{ascending:false}),supabaseClient.from('customer_admin_metadata').select('customer_id,customer_code').then(r=>r.error?{data:[],error:null}:r)]);if(c.error)return alert('거래처 조회 실패: '+c.error.message);if(n.error)return alert('메모 조회 실패: '+n.error.message+'\n\n거래처 관리메모 SQL 설치 상태를 확인해주세요.');const metaMap=new Map((m.data||[]).map(x=>[String(x.customer_id),x]));allProfiles=(c.data||[]).map(x=>({...x,...(metaMap.get(String(x.id))||{})}));customers=allProfiles.filter(c=>c.is_admin!==true);notes=n.data||[];renderNewCustomerSuggestions('');render()}
function usedCustomerIds(){return new Set([...notes.map(n=>String(n.customer_id)),...pendingCustomerCards].map(String))}
function availableCustomers(query=''){const used=usedCustomerIds();return customers.filter(c=>!used.has(String(c.id))&&lookupMatches([c.business_name,c.owner_name,c.phone,c.customer_code].filter(Boolean).join(' '),query)).sort((a,b)=>customerSearchCompare(a,b,query)).slice(0,50)}
function renderNewCustomerSuggestions(query=''){const box=$('newCustomerSuggestions'),q=String(query||'').trim();selectedNewCustomerId=null;$('createCustomerCardBtn').disabled=true;if(!q){box.hidden=true;box.innerHTML='';return}const rows=availableCustomers(q);box.hidden=false;box.innerHTML=rows.length?rows.map(c=>`<button type="button" data-new-customer="${esc(c.id)}"><b>${esc(customerName(c))}</b><small>${c.owner_name?esc(c.owner_name)+' · ':''}${esc(c.phone||c.customer_code||'등록 거래처')}</small></button>`).join(''):'<p>추가할 수 있는 거래처가 없습니다. 이미 등록된 거래처는 기존 카드에 메모를 추가하세요.</p>';box.querySelectorAll('[data-new-customer]').forEach(b=>b.onclick=()=>selectNewCustomer(b.dataset.newCustomer))}
function selectNewCustomer(id){const c=customers.find(x=>String(x.id)===String(id));if(!c)return;selectedNewCustomerId=String(id);$('newCustomerSearch').value=customerName(c);$('newCustomerSelected').textContent=`선택됨: ${customerName(c)}`;$('newCustomerSelected').hidden=false;$('newCustomerSuggestions').hidden=true;$('createCustomerCardBtn').disabled=false}
function grouped(){const map=new Map();for(const n of notes){const id=String(n.customer_id),c=allProfiles.find(x=>String(x.id)===id);if(!map.has(id))map.set(id,{id,name:customerName(c),notes:[]});map.get(id).notes.push(n)}for(const rawId of pendingCustomerCards){const id=String(rawId);if(!map.has(id)){const c=customers.find(x=>String(x.id)===id);if(c)map.set(id,{id,name:customerName(c),notes:[]})}}return [...map.values()]}
function render(){let rows=grouped(),q=$('customerNoteSearch').value.trim(),sort=$('customerNoteSort').value;if(q)rows=rows.filter(g=>lookupMatches(g.name,q));if(sort==='name')rows.sort((a,b)=>a.name.localeCompare(b.name,'ko',{numeric:true}));else if(sort==='count')rows.sort((a,b)=>b.notes.length-a.notes.length||a.name.localeCompare(b.name,'ko'));else rows.sort((a,b)=>new Date(b.notes[0]?.created_at||0)-new Date(a.notes[0]?.created_at||0));$('customerNotesList').innerHTML=rows.length?rows.map(g=>card(g)).join(''):'<div class="empty-notes">등록된 거래처 관리메모가 없습니다.<br>위의 ‘거래처 추가’로 시작하세요.</div>';document.querySelectorAll('[data-customer-toggle]').forEach(b=>b.onclick=()=>{openCustomerId=openCustomerId===b.dataset.customerToggle?null:b.dataset.customerToggle;render()});document.querySelectorAll('[data-note-add]').forEach(b=>b.onclick=()=>addNote(b.dataset.noteAdd));document.querySelectorAll('[data-note-delete]').forEach(b=>b.onclick=()=>deleteNote(b.dataset.noteDelete))}
function authorName(n){const p=allProfiles.find(x=>String(x.id)===String(n.created_by));return customerName(p)||'관리자'}
function card(g){const open=openCustomerId===g.id,last=g.notes[0],entries=g.notes.map((n,i)=>`<div class="note-entry"><p><b>${i+1}.</b> ${esc(n.memo)}</p><footer><span>${esc(authorName(n))} · ${new Date(n.created_at).toLocaleString('ko-KR')}</span><button type="button" data-note-delete="${n.id}">삭제</button></footer></div>`).join('');return `<article class="customer-note-card ${open?'open':''}"><button type="button" class="customer-note-summary" data-customer-toggle="${g.id}"><strong>${esc(g.name)}</strong><span>메모 ${g.notes.length}개</span><em>${last?`최근 ${new Date(last.created_at).toLocaleDateString('ko-KR')}`:''}</em><span class="chevron">⌄</span></button>${open?`<div class="customer-note-body">${entries}<div class="note-compose"><textarea id="note-input-${g.id}" maxlength="1000" placeholder="${esc(g.name)} 거래처에 새 메모 추가"></textarea><button type="button" data-note-add="${g.id}">메모 추가</button></div></div>`:''}</article>`}
async function createCard(){const id=selectedNewCustomerId,c=customers.find(x=>String(x.id)===String(id));if(!c)return alert('검색 결과에서 거래처를 선택해주세요.');if(usedCustomerIds().has(String(id))){openCustomerId=String(id);$('newCustomerPanel').hidden=true;render();return}pendingCustomerCards.add(String(id));openCustomerId=String(id);$('newCustomerPanel').hidden=true;render();setTimeout(()=>$(`note-input-${id}`)?.focus(),0)}
async function addNote(id){const input=$(`note-input-${id}`),text=input?.value.trim();if(!text)return alert('메모 내용을 입력해주세요.');const {error}=await supabaseClient.from('customer_admin_notes').insert({customer_id:id,memo:text,created_by:currentAdmin.id});if(error)return alert('메모 저장 실패: '+error.message);pendingCustomerCards.delete(String(id));await load();openCustomerId=String(id);render()}
async function deleteNote(id){if(!confirm('이 메모를 삭제할까요?'))return;const target=notes.find(n=>String(n.id)===String(id)),cid=String(target?.customer_id||'');const {error}=await supabaseClient.from('customer_admin_notes').delete().eq('id',id);if(error)return alert('메모 삭제 실패: '+error.message);await load();openCustomerId=cid;render()}
(async()=>{if(!await guard())return;$('addCustomerCardBtn').onclick=()=>{selectedNewCustomerId=null;$('newCustomerPanel').hidden=false;$('newCustomerSearch').value='';$('newCustomerSelected').hidden=true;$('createCustomerCardBtn').disabled=true;$('newCustomerSearch').focus()};$('cancelCustomerCardBtn').onclick=()=>{$('newCustomerPanel').hidden=true};$('createCustomerCardBtn').onclick=createCard;$('newCustomerSearch').oninput=e=>renderNewCustomerSuggestions(e.target.value);$('customerNoteSearch').oninput=render;$('customerNoteSort').onchange=render;await load()})();
