(function(){'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let rows=[];
async function guard(){const {data:{user}}=await supabaseClient.auth.getUser();if(!user)return location.replace('admin.html');const {data:p}=await supabaseClient.from('customers').select('is_admin,blocked').eq('id',user.id).maybeSingle();if(!(p?.is_admin&&!p?.blocked))return location.replace('admin.html');document.body.classList.add('auth-ready');return true}
function periodStart(value){if(value==='all')return null;const d=new Date();d.setHours(0,0,0,0);if(value!=='today')d.setDate(d.getDate()-Math.max(0,Number(value)-1));return d}
function render(){const q=String($('deletedOrderSearch').value||'').trim().toLowerCase(),period=$('deletedOrderPeriod').value,fromValue=$('deletedOrderFrom').value,toValue=$('deletedOrderTo').value,start=fromValue?new Date(`${fromValue}T00:00:00`):periodStart(period),end=toValue?new Date(`${toValue}T23:59:59.999`):null;const filtered=rows.filter(r=>{const date=new Date(r.deleted_at);return(!start||date>=start)&&(!end||date<=end)&&[r.order_number,r.customer_name,r.delete_reason,r.deleted_by_role].join(' ').toLowerCase().includes(q)});$('deletedOrderResultCount').textContent=`${filtered.length.toLocaleString()}건`;$('deletedOrderList').innerHTML=filtered.length?filtered.map(r=>{const items=Array.isArray(r.order_snapshot)?r.order_snapshot:[],qty=items.reduce((s,x)=>s+Number(x.qty||0),0),total=items.reduce((s,x)=>s+Number(x.total||0),0);return `<article class="deleted-order-card order-party-summary"><div class="deleted-order-card-head"><h3>${esc(r.customer_name||'거래처 미입력')}</h3><button type="button" class="deleted-history-remove" data-delete-history="${r.id}">이력 삭제</button></div><p><strong>주문번호</strong> ${esc(r.order_number)}</p><p><strong>삭제</strong> ${new Date(r.deleted_at).toLocaleString('ko-KR')} · ${esc(r.deleted_by_role||'-')} · ${esc(r.delete_reason||'-')}</p><p><strong>원본</strong> ${items.length}품번 · ${qty}죽 · ${total.toLocaleString()}원</p><details><summary>삭제 전 품번 보기</summary>${items.map(x=>`<p>${esc(x.warehouse_code?`${x.warehouse_code}-${x.item_number}`:x.item_number)} · ${Number(x.qty||0)}죽 · ${Number(x.price||0).toLocaleString()}원</p>`).join('')}</details></article>`}).join(''):'<p>선택한 기간의 삭제 주문이 없습니다.</p>';$('deletedOrderList').querySelectorAll('[data-delete-history]').forEach(button=>button.onclick=()=>removeHistory(Number(button.dataset.deleteHistory)));}
async function removeHistory(id){const row=rows.find(item=>Number(item.id)===id);if(!row)return;if(!confirm(`삭제 주문 이력을 영구 삭제할까요?\n\n${row.customer_name||'거래처'} · ${row.order_number}\n삭제 후 복구할 수 없습니다.`))return;const {error}=await supabaseClient.rpc('admin_delete_order_history',{p_history_id:id});if(error)return alert('삭제 이력 제거 실패: '+error.message+'\n\nV6.5.69 SQL을 실행해주세요.');rows=rows.filter(item=>Number(item.id)!==id);render()}
async function load(){const {data,error}=await supabaseClient.from('deleted_order_history').select('*').order('deleted_at',{ascending:false}).limit(2000);if(error){$('deletedOrderList').innerHTML=`<p>불러오기 실패: ${esc(error.message)}<br>V6.5.28 SQL을 먼저 실행하세요.</p>`;return}rows=data||[];render()}
document.addEventListener('DOMContentLoaded',async()=>{if(!await guard())return;['deletedOrderSearch','deletedOrderPeriod','deletedOrderFrom','deletedOrderTo'].forEach(id=>$(id).addEventListener(id==='deletedOrderSearch'?'input':'change',render));$('refreshDeletedOrders').onclick=load;load()});
})();
