(function(){
'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let code='S',orders=[],preview=[],factoryItems={S:[],B:[],I:[]};
const draftKey=()=>`designsocks_factory_draft_${code}`;
function warehouse(row){const saved=String(row.warehouse_code||'').trim().toUpperCase();if(['S','B','I'].includes(saved))return saved;return String(row.item_number||'').trim().toUpperCase().match(/^([SBI])(?:[-_\s]|(?=\d))/)?.[1]||''}
function splitItems(value){if(Array.isArray(value))return value.map(String);if(typeof value==='string'){try{const parsed=JSON.parse(value);if(Array.isArray(parsed))return parsed.map(String)}catch{}return value.split(/[\s,\/]+/).filter(Boolean)}return[]}
async function guard(){const {data:{user}}=await supabaseClient.auth.getUser();if(!user)return location.replace('admin.html');const {data:p}=await supabaseClient.from('customers').select('is_admin,blocked').eq('id',user.id).maybeSingle();if(!(p?.is_admin&&!p?.blocked))return location.replace('admin.html');document.body.classList.add('auth-ready');return true}
function readDraft(){try{return JSON.parse(localStorage.getItem(draftKey())||'[]')}catch{return[]}}
function saveDraft(){localStorage.setItem(draftKey(),JSON.stringify(preview));}
function sourcePreview(){const map=new Map();orders.filter(x=>warehouse(x)===code).forEach(x=>{const item=String(x.item_number||'').trim(),qty=Number(x.qty||0);if(item&&qty>0)map.set(item,(map.get(item)||0)+qty)});return[...map].map(([item_number,qty])=>({item_number,qty}))}
function rebuild(useDraft=true){const map=new Map(sourcePreview().map(x=>[x.item_number,{...x}]));if(useDraft)readDraft().forEach(x=>{if(x?.item_number&&Number(x.qty)>0)map.set(String(x.item_number),{item_number:String(x.item_number),qty:Number(x.qty)})});preview=[...map.values()].sort((a,b)=>a.item_number.localeCompare(b.item_number,'ko',{numeric:true}));render();saveDraft()}
function renderCatalog(){const keyword=String($('factoryItemSearch')?.value||'').trim().toUpperCase(),selected=new Map(preview.map(x=>[String(x.item_number).toUpperCase(),Number(x.qty||1)])),items=(factoryItems[code]||[]).filter(item=>!keyword||String(item).toUpperCase().includes(keyword));$('factoryCatalogList').innerHTML=items.length?items.map(item=>{const qty=selected.get(String(item).toUpperCase())||1,checked=selected.has(String(item).toUpperCase());return `<label class="factory-catalog-row ${checked?'selected':''}" data-catalog-item="${esc(item)}"><input class="factory-catalog-check" type="checkbox" ${checked?'checked':''}><strong>${esc(item)}</strong><input class="factory-catalog-qty" type="number" min="1" step="1" value="${qty}" ${checked?'':'disabled'} aria-label="${esc(item)} 주문수량"></label>`}).join(''):'<p class="factory-catalog-empty">검색된 공장 품번이 없습니다. 위 입력칸에서 직접 추가할 수 있습니다.</p>'}
function render(){const source=new Set(orders.filter(x=>warehouse(x)===code).map(x=>x.order_number));$('factoryPreviewTitle').textContent=`${code} 공장 선택 주문목록`;$('factorySummary').textContent=`${preview.length.toLocaleString()}품번 · ${preview.reduce((s,x)=>s+Number(x.qty||0),0).toLocaleString()}죽 · 원주문 ${source.size.toLocaleString()}건`;$('factoryItemList').innerHTML=(factoryItems[code]||[]).map(item=>`<option value="${esc(item)}"></option>`).join('');$('factoryPreview').innerHTML=preview.length?preview.map((x,index)=>`<div class="factory-list-row" data-index="${index}"><strong>${esc(x.item_number)}</strong><input class="factory-row-qty" type="number" min="1" step="1" value="${Number(x.qty)}" aria-label="${esc(x.item_number)} 수량"><button class="factory-remove" type="button">삭제</button></div>`).join(''):'<p>현재 발주할 품번이 없습니다.</p>';renderCatalog()}
function setCatalogItem(item,checked,qty=1){const index=preview.findIndex(x=>String(x.item_number).toUpperCase()===String(item).toUpperCase());if(checked){if(index>=0)preview[index].qty=Math.max(1,Math.floor(Number(qty||1)));else preview.push({item_number:item,qty:Math.max(1,Math.floor(Number(qty||1)))})}else if(index>=0)preview.splice(index,1);preview.sort((a,b)=>a.item_number.localeCompare(b.item_number,'ko',{numeric:true}));saveDraft();render()}
function addItem(){const item=String($('factoryItemSearch').value||'').trim(),qty=Math.max(1,Math.floor(Number($('factoryItemQty').value||1)));if(!item)return alert('추가할 품번을 검색하거나 직접 입력하세요.');const existing=preview.find(x=>x.item_number.toUpperCase()===item.toUpperCase());if(existing)existing.qty+=qty;else preview.push({item_number:item,qty});preview.sort((a,b)=>a.item_number.localeCompare(b.item_number,'ko',{numeric:true}));$('factoryItemSearch').value='';$('factoryItemQty').value='1';saveDraft();render()}
function fallbackFactoryCopy(text){const x=window.scrollX,y=window.scrollY,focused=document.activeElement,area=document.createElement('textarea');area.value=text;area.readOnly=true;area.setAttribute('aria-hidden','true');area.style.cssText='position:fixed;left:0;top:0;width:1px;height:1px;padding:0;border:0;opacity:0;pointer-events:none;z-index:-1';document.body.appendChild(area);area.focus({preventScroll:true});area.select();area.setSelectionRange(0,area.value.length);const copied=document.execCommand('copy');area.remove();window.scrollTo(x,y);focused?.focus?.({preventScroll:true});return copied}
async function copyText(items=preview,mode='excel'){const text=items.map(x=>mode==='kakao'?`${x.item_number}      ${x.qty}`:`${x.item_number}\t${x.qty}`).join('\n');if(!text)return alert('복사할 품번이 없습니다.');try{if(!navigator.clipboard?.writeText)throw new Error('clipboard unavailable');await navigator.clipboard.writeText(text)}catch{if(!fallbackFactoryCopy(text))return alert('복사하지 못했습니다. 브라우저의 클립보드 권한을 확인해 주세요.')}alert(mode==='kakao'?`${code} 공장 카톡용 목록을 넓은 간격으로 복사했습니다.`:`${code} 공장 엑셀용 목록을 복사했습니다. A열 품번·B열 수량으로 나뉩니다.`)}
async function load(){const [orderResult,groupResult]=await Promise.all([supabaseClient.from('orders').select('order_number,item_number,warehouse_code,qty,status').neq('status','출고완료'),supabaseClient.from('product_groups').select('item_numbers,warehouse_code')]);if(orderResult.error)return alert(orderResult.error.message);orders=orderResult.data||[];factoryItems={S:[],B:[],I:[]};(groupResult.data||[]).forEach(group=>{const w=warehouse(group);if(factoryItems[w])factoryItems[w].push(...splitItems(group.item_numbers))});Object.keys(factoryItems).forEach(key=>factoryItems[key]=[...new Set(factoryItems[key])].sort((a,b)=>a.localeCompare(b,'ko',{numeric:true})));rebuild(true);await loadHistory()}
async function save(){if(!preview.length)return alert('저장할 품번이 없습니다.');if(!confirm(`${code} 공장 ${preview.length}품번을 발주기록으로 저장할까요?`))return;const source=[...new Set(orders.filter(x=>warehouse(x)===code).map(x=>x.order_number))],d=new Date(),num=`${code}-${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}-${Date.now().toString().slice(-6)}`;const {error}=await supabaseClient.from('factory_orders').insert({factory_code:code,factory_order_number:num,items:preview,source_order_numbers:source,note:$('factoryNote').value.trim()});if(error)return alert(error.message);localStorage.removeItem(draftKey());$('factoryNote').value='';alert(`발주번호 ${num} 저장 완료`);rebuild(false);await loadHistory()}
async function loadHistory(){const {data,error}=await supabaseClient.from('factory_orders').select('*').order('created_at',{ascending:false}).limit(100);if(error){$('factoryHistory').innerHTML=`<p>${esc(error.message)}</p>`;return}$('factoryHistory').innerHTML=(data||[]).map(r=>`<article class="factory-record"><div class="factory-record-head"><div><strong>${esc(r.factory_order_number)} · ${r.factory_code} 공장</strong><small>${new Date(r.created_at).toLocaleString('ko-KR')} · ${(r.items||[]).length}품번 · ${esc(r.note||'메모 없음')}</small></div><div><button data-copy="${r.id}">복사</button> <select data-status="${r.id}">${['발주완료','생산중','입고완료','취소'].map(s=>`<option ${r.status===s?'selected':''}>${s}</option>`).join('')}</select></div></div></article>`).join('')||'<p>저장된 발주 기록이 없습니다.</p>';$('factoryHistory').querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>copyText((data||[]).find(x=>String(x.id)===b.dataset.copy)?.items||[]));$('factoryHistory').querySelectorAll('[data-status]').forEach(s=>s.onchange=async()=>{const {error}=await supabaseClient.from('factory_orders').update({status:s.value,updated_at:new Date().toISOString()}).eq('id',s.dataset.status);if(error)alert(error.message)})}
document.addEventListener('DOMContentLoaded',async()=>{if(!await guard())return;document.querySelectorAll('[data-factory]').forEach(b=>b.onclick=()=>{code=b.dataset.factory;document.querySelectorAll('[data-factory]').forEach(x=>x.classList.toggle('active',x===b));$('factoryItemSearch').value='';rebuild(true)});$('refreshFactory').onclick=load;$('copyFactoryKakao').onclick=()=>copyText(preview,'kakao');$('copyFactoryExcel').onclick=()=>copyText(preview,'excel');$('saveFactory').onclick=save;$('addFactoryItem').onclick=addItem;$('factoryItemSearch').oninput=renderCatalog;$('factoryItemSearch').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();addItem()}};$('factoryCatalogList').addEventListener('change',e=>{const row=e.target.closest('[data-catalog-item]');if(!row)return;const check=row.querySelector('.factory-catalog-check'),qty=row.querySelector('.factory-catalog-qty');if(e.target.classList.contains('factory-catalog-check'))setCatalogItem(row.dataset.catalogItem,check.checked,qty.value);else if(e.target.classList.contains('factory-catalog-qty')&&check.checked)setCatalogItem(row.dataset.catalogItem,true,qty.value)});$('factoryPreview').addEventListener('change',e=>{const row=e.target.closest('[data-index]');if(!row||!e.target.classList.contains('factory-row-qty'))return;preview[Number(row.dataset.index)].qty=Math.max(1,Math.floor(Number(e.target.value||1)));saveDraft();render()});$('factoryPreview').addEventListener('click',e=>{const row=e.target.closest('[data-index]');if(!row||!e.target.classList.contains('factory-remove'))return;preview.splice(Number(row.dataset.index),1);saveDraft();render()});await load()})
})();
