const supabaseClient=window.supabase.createClient('https://dtjhuejmxrjkcxzvilgw.supabase.co','sb_publishable_kwXvFOCpknkDf9BKmcszrQ_Q7IBVg87');
const ADMIN_EMAILS=new Set(['900smk@naver.com','sm0727sm@hanmail.net','p1028p@naver.com']);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
async function guard(){const {data:{user}}=await supabaseClient.auth.getUser();if(!user)return location.replace('admin.html');const {data:p}=await supabaseClient.from('customers').select('is_admin').eq('id',user.id).maybeSingle();if(!ADMIN_EMAILS.has(String(user.email).toLowerCase())&&!p?.is_admin)return location.replace('admin.html');document.body.classList.add('auth-ready');return true;}
async function saveNotice(){const payload={notice_type:noticeType.value,title:noticeTitle.value.trim(),content:noticeContent.value.trim(),image_url:noticeImage.value.trim()||null,end_at:noticeEnd.value?new Date(noticeEnd.value+'T23:59:59').toISOString():null,is_pinned:noticePinned.checked,is_published:true};if(!payload.title||!payload.content)return alert('제목과 내용을 입력하세요.');const {error}=await supabaseClient.from('announcements').insert(payload);if(error)return alert(error.message);noticeTitle.value='';noticeContent.value='';noticeImage.value='';noticeEnd.value='';noticePinned.checked=false;loadNotices();}
async function loadNotices(){const box=document.getElementById('noticeList');const {data,error}=await supabaseClient.from('announcements').select('*').order('is_pinned',{ascending:false}).order('created_at',{ascending:false});if(error){box.innerHTML=`<div class="product-card"><p>설치 SQL 실행이 필요합니다: ${esc(error.message)}</p></div>`;return;}box.innerHTML=data?.length?data.map(n=>`<article class="product-card v3-notice-admin-card"><div class="order-top"><div><span class="v3-notice-type">${esc(n.notice_type)}</span><h2>${esc(n.title)}</h2></div><span class="status-badge ${n.is_published?'done':'blocked'}">${n.is_published?'공개':'숨김'}</span></div><p>${esc(n.content).replace(/\n/g,'<br>')}</p><small>${new Date(n.created_at).toLocaleString('ko-KR')}${n.end_at?' · 종료 '+new Date(n.end_at).toLocaleDateString('ko-KR'):''}</small><div class="v3-card-actions"><button class="cart-btn" onclick="togglePublish('${n.id}',${!!n.is_published})">${n.is_published?'숨기기':'공개하기'}</button><button class="cart-btn gray-btn" onclick="deleteNotice('${n.id}')">삭제</button></div></article>`).join(''):'<div class="product-card"><p>게시물이 없습니다.</p></div>';}
async function togglePublish(id,current){const {error}=await supabaseClient.from('announcements').update({is_published:!current}).eq('id',id);if(error)return alert(error.message);loadNotices();}
async function deleteNotice(id){if(!confirm('게시물을 삭제할까요?'))return;const {error}=await supabaseClient.from('announcements').delete().eq('id',id);if(error)return alert(error.message);loadNotices();}
window.togglePublish=togglePublish;window.deleteNotice=deleteNotice;document.addEventListener('DOMContentLoaded',async()=>{if(await guard()){saveNoticeBtn.onclick=saveNotice;loadNotices();}});
