const supabaseClient=window.supabase.createClient('https://dtjhuejmxrjkcxzvilgw.supabase.co','sb_publishable_kwXvFOCpknkDf9BKmcszrQ_Q7IBVg87');
const ADMIN_SESSION_KEY='designjam_admin_session';
let paymentOrders=[],paymentRecords=new Map(),paymentAccounts=[];
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':'&quot;'}[c])),money=v=>Math.round(Number(v||0)).toLocaleString('ko-KR');
const keyFor=(orderNumber,customerKey)=>`${orderNumber}::${customerKey||''}`;
const effectiveQty=row=>Math.max(0,Number(row.qty||0)-Math.max(0,Number(row.soldout_qty||0)));
const dateKey=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?'':`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const localDateTime=v=>{if(!v)return '';const d=new Date(v);if(Number.isNaN(d.getTime()))return '';const off=d.getTimezoneOffset();return new Date(d.getTime()-off*60000).toISOString().slice(0,16)};

async function guard(){const {data:{user}}=await supabaseClient.auth.getUser();if(!user)return location.replace('admin.html');const {data:p}=await supabaseClient.from('customers').select('is_admin,blocked,admin_role').eq('id',user.id).maybeSingle();if(!p?.is_admin||p.blocked||['manager','employee'].includes(p.admin_role)){alert('입금·미수금 관리는 일반 관리자 이상만 사용할 수 있습니다.');return location.replace('admin-home.html')}localStorage.setItem(ADMIN_SESSION_KEY,user.id);document.body.classList.add('auth-ready');return true}
async function fetchAll(table,column){const out=[];for(let from=0;;from+=1000){const r=await supabaseClient.from(table).select('*').order(column,{ascending:true}).range(from,from+999);if(r.error)throw r.error;out.push(...(r.data||[]));if((r.data||[]).length<1000)return out}}
function groupOrders(rows){const map=new Map();rows.forEach(row=>{const customerKey=String(row.customer_id||'');const key=keyFor(row.order_number,customerKey);if(!map.has(key))map.set(key,{key,orderNumber:row.order_number,customerKey,customerName:row.customer_name||'거래처 미입력',createdAt:row.created_at,status:row.status||'주문접수',shippingFee:Number(row.shipping_fee||0),items:[]});const g=map.get(key);g.items.push(row);g.shippingFee=Math.max(g.shippingFee,Number(row.shipping_fee||0));if(row.created_at&&(!g.createdAt||new Date(row.created_at)<new Date(g.createdAt)))g.createdAt=row.created_at});return [...map.values()].map(g=>({...g,orderAmount:g.items.reduce((s,x)=>s+effectiveQty(x)*Number(x.price||0),0)+g.shippingFee,orderQty:g.items.reduce((s,x)=>s+effectiveQty(x),0)})).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt))}
function derived(g){const r=paymentRecords.get(g.key)||{};const paid=Math.max(0,Number(r.paid_amount||0));return {...r,paid,balance:Math.max(0,g.orderAmount-paid),status:paid<=0?'미입금':paid<g.orderAmount?'일부입금':'입금완료'}}
async function load(){try{$('paymentMessage').textContent='주문과 입금정보를 불러오는 중입니다.';const [rows,records,accounts]=await Promise.all([fetchAll('orders','created_at'),fetchAll('order_payment_records','updated_at'),supabaseClient.from('payment_accounts').select('*').eq('is_active',true).order('is_default',{ascending:false})]);paymentOrders=groupOrders(rows);paymentRecords=new Map(records.map(r=>[keyFor(r.order_number,r.customer_key),r]));paymentAccounts=accounts.data||[];populateCustomerSelect();$('paymentMessage').textContent='';render()}catch(e){$('paymentOrderList').innerHTML='<p class="payment-error">입금 관리 데이터를 불러오지 못했습니다.</p>';$('paymentMessage').textContent=e.message.includes('order_payment_records')?'Supabase에서 V6.6.4-PAYMENT-RECEIVABLES.sql을 먼저 실행해주세요.':e.message}}
function filtered(){const start=$('paymentStartDate').value,end=$('paymentEndDate').value,customer=$('paymentCustomer').value,status=$('paymentStatus').value,q=$('paymentSearch').value.trim().toLowerCase();return paymentOrders.filter(g=>{const day=dateKey(g.createdAt);return(!start||day>=start)&&(!end||day<=end)&&(customer==='all'||g.customerKey===customer)&&(status==='all'||derived(g).status===status)&&(!q||`${g.orderNumber} ${g.customerName}`.toLowerCase().includes(q))})}
function render(){const list=filtered(),values=list.map(g=>({g,p:derived(g)}));const total=values.reduce((s,x)=>s+x.g.orderAmount,0),paid=values.reduce((s,x)=>s+Math.min(x.p.paid,x.g.orderAmount),0),balance=values.reduce((s,x)=>s+x.p.balance,0);$('paymentSummary').innerHTML=[['주문금액',total,'원'],['입금액',paid,'원'],['미수금',balance,'원'],['미입금',values.filter(x=>x.p.status==='미입금').length,'건'],['일부입금',values.filter(x=>x.p.status==='일부입금').length,'건'],['입금완료',values.filter(x=>x.p.status==='입금완료').length,'건']].map(([a,b,c])=>`<article class="v3-metric-card"><span>${a}</span><strong>${money(b)}</strong><small>${c}</small></article>`).join('');renderCustomers(values);$('paymentResultCount').textContent=`${list.length}건`;$('paymentOrderList').innerHTML=list.length?list.map(orderCard).join(''):'<p class="product-card">조건에 맞는 주문이 없습니다.</p>';renderDailyCustomer(values)}

function populateCustomerSelect(){const sel=$('paymentCustomer'),current=sel.value||'all',map=new Map();paymentOrders.forEach(g=>{if(g.customerKey&&!map.has(g.customerKey))map.set(g.customerKey,g.customerName)});sel.innerHTML='<option value="all">전체 거래처</option>'+[...map.entries()].sort((a,b)=>String(a[1]).localeCompare(String(b[1]),'ko')).map(([id,name])=>`<option value="${esc(id)}">${esc(name)}</option>`).join('');if([...sel.options].some(o=>o.value===current))sel.value=current}
function renderDailyCustomer(values){const section=$('paymentDailySection'),customer=$('paymentCustomer').value;if(customer==='all'){section.hidden=true;return}section.hidden=false;const map=new Map();values.forEach(({g,p})=>{const day=dateKey(g.createdAt),x=map.get(day)||{day,total:0,shipping:0,paid:0,balance:0,count:0};x.total+=g.orderAmount;x.shipping+=g.shippingFee;x.paid+=Math.min(p.paid,g.orderAmount);x.balance+=p.balance;x.count++;map.set(day,x)});const rows=[...map.values()].sort((a,b)=>a.day.localeCompare(b.day));const totals=rows.reduce((a,x)=>({total:a.total+x.total,shipping:a.shipping+x.shipping,paid:a.paid+x.paid,balance:a.balance+x.balance,count:a.count+x.count}),{total:0,shipping:0,paid:0,balance:0,count:0});$('paymentDailyCaption').textContent=`${$('paymentStartDate').value} ~ ${$('paymentEndDate').value}`;$('paymentDailyTotals').innerHTML=rows.length?`<div style="overflow:auto"><table class="payment-daily-table"><thead><tr><th>날짜</th><th>주문</th><th>배송비</th><th>입금</th><th>미수</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.day)}</td><td>${money(x.total)}원</td><td>${money(x.shipping)}원</td><td>${money(x.paid)}원</td><td><strong>${money(x.balance)}원</strong></td></tr>`).join('')}</tbody><tfoot><tr><td>합계 ${totals.count}건</td><td>${money(totals.total)}원</td><td>${money(totals.shipping)}원</td><td>${money(totals.paid)}원</td><td>${money(totals.balance)}원</td></tr></tfoot></table></div>`:'<p>선택 기간의 내역이 없습니다.</p>'}
function renderCustomers(values){const map=new Map();values.forEach(({g,p})=>{const k=g.customerKey||g.customerName;if(!map.has(k))map.set(k,{name:g.customerName,total:0,paid:0,balance:0,count:0});const x=map.get(k);x.total+=g.orderAmount;x.paid+=Math.min(p.paid,g.orderAmount);x.balance+=p.balance;x.count++});const rows=[...map.values()].sort((a,b)=>b.balance-a.balance);$('paymentCustomerList').innerHTML=rows.length?rows.map(x=>`<button type="button" data-customer="${esc(x.name)}" data-customer-key="${esc(values.find(v=>v.g.customerName===x.name)?.g.customerKey||'')}"><b>${esc(x.name)}</b><span>${x.count}건</span><span>입금 ${money(x.paid)}원</span><strong>미수 ${money(x.balance)}원</strong></button>`).join(''):'<p>조회 결과가 없습니다.</p>';$('paymentCustomerList').querySelectorAll('button').forEach(b=>b.onclick=()=>{$('paymentCustomer').value=b.dataset.customerKey||'all';$('paymentSearch').value='';render()})}
function orderCard(g){const p=derived(g),r=paymentRecords.get(g.key)||{},accountOptions=['',...paymentAccounts.map(x=>`${x.label||''} ${x.bank_name||''} ${x.account_number||''}`.trim())].filter((x,i,a)=>a.indexOf(x)===i);if(r.payment_account&&!accountOptions.includes(r.payment_account))accountOptions.push(r.payment_account);return `<article class="product-card payment-order-card status-${p.status}"><div class="payment-order-head"><div><span class="payment-status">${p.status}</span><h3>${esc(g.customerName)}</h3><p>${esc(g.orderNumber)} · ${esc(new Date(g.createdAt).toLocaleString('ko-KR'))} · ${g.orderQty}죽 · ${esc(g.status)}</p></div><div><span>주문금액</span><strong>${money(g.orderAmount)}원</strong><small>남은 미수 ${money(p.balance)}원</small></div></div><div class="payment-edit-grid"><label>입금액<input data-field="paid" type="number" min="0" step="100" value="${p.paid}"></label><label>입금계좌<select data-field="account">${accountOptions.map(x=>`<option ${x===(r.payment_account||'')?'selected':''}>${esc(x||'선택 안 함')}</option>`).join('')}</select></label><label>입금자명<input data-field="depositor" value="${esc(r.depositor_name||'')}"></label><label>입금일시<input data-field="paidAt" type="datetime-local" value="${localDateTime(r.paid_at)}"></label><label class="wide">관리 메모<input data-field="memo" value="${esc(r.memo||'')}" placeholder="관리자만 보는 메모"></label></div><div class="payment-actions"><button type="button" class="gray-btn" data-action="unpaid">미입금 처리</button><button type="button" data-action="full">전액 입금</button><button type="button" data-action="save">입금정보 저장</button></div></article>`}
async function saveCard(card,g,forced){const paidInput=card.querySelector('[data-field=paid]');if(forced==='unpaid')paidInput.value=0;if(forced==='full')paidInput.value=g.orderAmount;let paid=Math.max(0,Number(paidInput.value||0));if(paid>g.orderAmount&&!confirm(`입금액이 주문금액보다 ${money(paid-g.orderAmount)}원 많습니다. 그대로 저장할까요?`))return;if(forced==='full'&&!card.querySelector('[data-field=paidAt]').value)card.querySelector('[data-field=paidAt]').value=localDateTime(new Date());const args={p_order_number:g.orderNumber,p_customer_key:g.customerKey,p_customer_name:g.customerName,p_order_amount:g.orderAmount,p_paid_amount:paid,p_payment_account:card.querySelector('[data-field=account]').value.replace('선택 안 함','')||null,p_depositor_name:card.querySelector('[data-field=depositor]').value||null,p_paid_at:card.querySelector('[data-field=paidAt]').value?new Date(card.querySelector('[data-field=paidAt]').value).toISOString():null,p_memo:card.querySelector('[data-field=memo]').value||null};card.querySelectorAll('button').forEach(b=>b.disabled=true);const {data,error}=await supabaseClient.rpc('admin_save_order_payment',args);if(error){card.querySelectorAll('button').forEach(b=>b.disabled=false);return alert('입금정보 저장 실패: '+error.message)}paymentRecords.set(g.key,data);render()}
function bind(){['paymentCustomer','paymentStartDate','paymentEndDate','paymentStatus'].forEach(id=>$(id).addEventListener('change',render));$('paymentSearch').addEventListener('input',render);$('paymentRefresh').onclick=load;$('paymentOrderList').addEventListener('click',e=>{const btn=e.target.closest('[data-action]');if(!btn)return;const card=btn.closest('.payment-order-card'),idx=[...$('paymentOrderList').children].indexOf(card),g=filtered()[idx];if(g)saveCard(card,g,btn.dataset.action)})}
document.addEventListener('DOMContentLoaded',async()=>{const now=new Date(),start=new Date(now);start.setMonth(start.getMonth()-1);$('paymentEndDate').value=dateKey(now);$('paymentStartDate').value=dateKey(start);bind();if(await guard())load()});
