(function(){"use strict";
const ADMIN_SESSION_KEY="designjam_admin_session";const ADMIN_EMAILS=new Set(["900smk@naver.com","sm0727sm@hanmail.net","p1028p@naver.com"]);let orders=[],groups=[],active=null,autoPrintHandled=false,pickingLiveChannel=null,currentPicker={id:'',name:'관리자',role:'admin'};let pickingSort='item-asc',scanIncrement=1;const $=id=>document.getElementById(id);const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));const KO_TO_EN={"ㅂ":"Q","ㅃ":"QQ","ㅈ":"W","ㅉ":"WW","ㄷ":"E","ㄸ":"EE","ㄱ":"R","ㄲ":"RR","ㅅ":"T","ㅆ":"TT","ㅛ":"Y","ㅕ":"U","ㅑ":"I","ㅐ":"O","ㅒ":"OO","ㅔ":"P","ㅖ":"PP","ㅁ":"A","ㄴ":"S","ㅇ":"D","ㄹ":"F","ㅎ":"G","ㅗ":"H","ㅓ":"J","ㅏ":"K","ㅣ":"L","ㅋ":"Z","ㅌ":"X","ㅊ":"C","ㅍ":"V","ㅠ":"B","ㅜ":"N","ㅡ":"M","ᄇ":"Q","ᄈ":"QQ","ᄌ":"W","ᄍ":"WW","ᄃ":"E","ᄄ":"EE","ᄀ":"R","ᄁ":"RR","ᄉ":"T","ᄊ":"TT","ᄋ":"D","ᄂ":"S","ᄆ":"A","ᄅ":"F","ᄒ":"G","ᄏ":"Z","ᄐ":"X","ᄎ":"C","ᄑ":"V","ᅭ":"Y","ᅧ":"U","ᅣ":"I","ᅢ":"O","ᅤ":"OO","ᅦ":"P","ᅨ":"PP","ᅩ":"H","ᅥ":"J","ᅡ":"K","ᅵ":"L","ᅲ":"B","ᅮ":"N","ᅳ":"M","ᆨ":"R","ᆩ":"RR","ᆪ":"RT","ᆫ":"S","ᆬ":"SW","ᆭ":"SG","ᆮ":"E","ᆯ":"F","ᆰ":"FR","ᆱ":"FA","ᆲ":"FQ","ᆳ":"FT","ᆴ":"FX","ᆵ":"FV","ᆶ":"FG","ᆷ":"A","ᆸ":"Q","ᆹ":"QT","ᆺ":"T","ᆻ":"TT","ᆼ":"D","ᆽ":"W","ᆾ":"C","ᆿ":"Z","ᇀ":"X","ᇁ":"V","ᇂ":"G"};
let inventoryMap=new Map(),inventoryAvailable=false;
const CODE_TO_KEY={...Object.fromEntries(Array.from({length:26},(_,i)=>[`Key${String.fromCharCode(65+i)}`,String.fromCharCode(65+i)])),...Object.fromEntries(Array.from({length:10},(_,i)=>[`Digit${i}`,String(i)])),...Object.fromEntries(Array.from({length:10},(_,i)=>[`Numpad${i}`,String(i)])),Minus:'-',NumpadSubtract:'-',Equal:'=',NumpadAdd:'+',Slash:'/',NumpadDivide:'/',Backslash:'\\',Semicolon:';',Quote:"'",Comma:',',Period:'.',NumpadDecimal:'.',Backquote:'`',BracketLeft:'[',BracketRight:']'};
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0000-\u001F\u007F-\u009F\u200B-\u200D\uFEFF]/g,'').replace(/\s+/g,'').split('').map(ch=>KO_TO_EN[ch]||ch).join('').normalize('NFKC').toUpperCase().replace(/[^A-Z0-9_\-~]/g,'');
function scanCandidates(v){const base=norm(v).replace(/^\]C[012]/,'').replace(/^(CODE128|EAN13|EAN8|SKU|ITEM)[:\-_]?/,'');const out=new Set([base]);if(/^0+\d+$/.test(base))out.add(base.replace(/^0+/,'')||'0');(base.match(/[A-Z0-9_\-~]+/g)||[]).forEach(x=>out.add(x));return [...out].filter(Boolean)}
function keyFromEvent(e){if(e.code&&CODE_TO_KEY[e.code])return CODE_TO_KEY[e.code];if(e.key&&e.key.length===1)return e.key;return ''}
async function guard(){const {data:{user}}=await supabaseClient.auth.getUser();const stored=sessionStorage.getItem(ADMIN_SESSION_KEY)||localStorage.getItem(ADMIN_SESSION_KEY);if(!user||(stored&&stored!==user.id)){location.replace('admin.html?view=orders');return false}const {data:p}=await supabaseClient.from('customers').select('is_admin,blocked,business_name,owner_name,admin_role,email').eq('id',user.id).maybeSingle();if(!ADMIN_EMAILS.has((user.email||'').toLowerCase())&&!(p?.is_admin===true&&p?.blocked!==true)){location.replace('admin.html?view=orders');return false}currentPicker={id:user.id,name:String(p?.business_name||p?.owner_name||user.email||'관리자'),role:String(p?.admin_role||'admin')};document.body.classList.add('auth-ready');return true}
async function fetchAll(requestedOrder=''){const all=[];for(let from=0;;from+=1000){const {data,error}=await supabaseClient.from('orders').select('*').neq('status','출고완료').order('created_at',{ascending:true}).range(from,from+999);if(error)throw error;all.push(...(data||[]));if(!data||data.length<1000)break}if(requestedOrder&&!all.some(row=>row.order_number===requestedOrder)){const {data,error}=await supabaseClient.from('orders').select('*').eq('order_number',requestedOrder).order('id',{ascending:true});if(error)throw error;all.push(...(data||[]))}return all}
async function fetchInventory(){const all=[];for(let from=0;;from+=1000){const {data,error}=await supabaseClient.from('inventory_items').select('item_number,barcode,quantity').range(from,from+999);if(error){console.warn('ERP 재고 조회 실패:',error.message);return null}all.push(...(data||[]));if(!data||data.length<1000)break}return all}
function stockKey(v){return String(v??'').trim().toUpperCase()}
function setInventory(rows){inventoryMap=new Map();inventoryAvailable=Array.isArray(rows);if(!rows)return;(rows||[]).forEach(r=>{const qty=Number(r.quantity||0),item=stockKey(r.item_number),barcode=stockKey(r.barcode);if(item)inventoryMap.set(item,qty);if(barcode)inventoryMap.set(barcode,qty)})}
function stockStatus(item){if(!inventoryAvailable)return{warning:false,kind:'unknown',stock:null,text:'재고조회 불가'};const key=stockKey(item?.item_number),registered=inventoryMap.has(key),stock=registered?Number(inventoryMap.get(key)||0):null,ordered=Number(item?.qty||0);if(!registered)return{warning:true,kind:'unregistered',stock:null,text:'ERP 재고 미등록'};if(stock<=0)return{warning:true,kind:'empty',stock,text:'재고 없음'};if(stock<ordered)return{warning:true,kind:'short',stock,text:`재고 부족 ${stock}죽`};return{warning:false,kind:'enough',stock,text:`재고 ${stock}죽`}}
function availableStock(item){if(!inventoryAvailable)return null;const key=stockKey(item?.item_number);return inventoryMap.has(key)?Math.max(0,Number(inventoryMap.get(key)||0)):0}
function buildGroups(){const map=new Map();for(const r of orders){if(!map.has(r.order_number))map.set(r.order_number,{orderNumber:r.order_number,customerName:r.customer_name||'거래처 미입력',customerOwnerName:r.customer_owner_name||'',deliveryName:r.delivery_name||r.customer_name||'',deliveryAddress:r.delivery_address||'',createdAt:r.created_at,status:r.status||'주문접수',revisionStatus:r.customer_revision_status||'',assignedTo:r.picking_assigned_to||'',assignedName:r.picking_assigned_name||'',assignedDevice:r.picking_assigned_device||'',items:[],isProxy:String(r.order_number||'').startsWith('ADMIN-')||String(r.memo||'').includes('[관리자 대신주문]')});const group=map.get(r.order_number);if(r.customer_revision_status)group.revisionStatus=r.customer_revision_status;if(r.delivery_name&&(!group.deliveryName||group.deliveryName===group.customerName))group.deliveryName=r.delivery_name;if(r.delivery_address&&!group.deliveryAddress)group.deliveryAddress=r.delivery_address;if(r.picking_assigned_to){group.assignedTo=r.picking_assigned_to;group.assignedName=r.picking_assigned_name||group.assignedName;group.assignedDevice=r.picking_assigned_device||group.assignedDevice}group.items.push(r);if(r.status==='출고완료')group.status='출고완료'}groups=[...map.values()]}
function totals(g){const originalOrdered=g.items.reduce((s,x)=>s+Number(x.qty||0),0),picked=g.items.reduce((s,x)=>s+Number(x.picked_qty||0),0),soldout=g.items.reduce((s,x)=>s+Math.min(Number(x.qty||0),Number(x.soldout_qty||(x.is_soldout?x.qty:0))),0),ordered=Math.max(0,originalOrdered-soldout);return{ordered,originalOrdered,picked,soldout,shippable:ordered,processed:Math.min(picked,ordered)}}
function natural(a,b){return String(a??'').localeCompare(String(b??''),'ko',{numeric:true,sensitivity:'base'})}function sortedItems(items){const rows=[...items];if(pickingSort==='item-desc')return rows.sort((a,b)=>natural(b.item_number,a.item_number));if(pickingSort==='ordered-desc')return rows.sort((a,b)=>Number(b.qty||0)-Number(a.qty||0)||natural(a.item_number,b.item_number));if(pickingSort==='status')return rows.sort((a,b)=>{const ac=Number(a.picked_qty||0)+Number(a.soldout_qty||0)>=Number(a.qty||0),bc=Number(b.picked_qty||0)+Number(b.soldout_qty||0)>=Number(b.qty||0);return Number(ac)-Number(bc)||natural(a.item_number,b.item_number)});return rows.sort((a,b)=>natural(a.item_number,b.item_number))}
function warehouseCode(item){const saved=String(item?.warehouse_code||'').trim().toUpperCase();if(['S','B','I'].includes(saved))return saved;const match=String(item?.item_number||'').trim().toUpperCase().match(/^([SBI])(?:[-\s]|(?=\d))/);return match?match[1]:'기타'}
function warehouseLabel(code){return code==='S'?'S 출고지':code==='B'?'B 출고지':code==='I'?'I 출고지':'기타 출고지'}
function warehouseSections(items){const order=['S','B','I','기타'],map=new Map(order.map(code=>[code,[]]));(items||[]).forEach(item=>(map.get(warehouseCode(item))||map.get('기타')).push(item));return order.map(code=>({code,label:warehouseLabel(code),items:[...map.get(code)].sort((a,b)=>natural(a.item_number,b.item_number))})).filter(section=>section.items.length)}
function displayItemNumber(item){const code=String(item?.warehouse_code||'').trim().toUpperCase();return ['S','B','I'].includes(code)?`${code}-${item.item_number}`:String(item?.item_number||'')}
function renderWarehousePickSections(items){return warehouseSections(items).map(section=>{const warehouseComplete=section.items.every(x=>Number(x.picked_qty||0)+Number(x.soldout_qty||0)>=Number(x.qty||0));return `<section class="warehouse-pick-section warehouse-${section.code.toLowerCase()}" data-warehouse-code="${esc(section.code)}"><h3><span>${esc(section.label)}</span><span class="warehouse-heading-actions"><small>${section.items.length}품번 · ${totals({items:section.items}).ordered}죽</small>${['S','B','I'].includes(section.code)?`<button type="button" class="bulk-pick-button ${warehouseComplete?'cancel':''}" data-bulk-pick="${esc(section.code)}">${esc(section.code)} ${warehouseComplete?'일괄취소':'일괄피킹'}</button>`:''}<button type="button" data-print-warehouse="${esc(section.code)}">이 출고지만 인쇄</button></span></h3><div class="pick-table-wrap"><div class="pick-table-head"><span>품번</span><span>주문</span><span>피킹</span><span>상태·관리</span></div><div>${section.items.map(x=>{const need=Number(x.qty||0),got=Number(x.picked_qty||0),unpicked=Number(x.soldout_qty||0),remain=Math.max(0,need-got-unpicked),complete=remain===0,cls=complete?'complete':'incomplete',checkField=`${section.code.toLowerCase()}_outbound_confirmed`,checked=Boolean(x[checkField]);return `<div class="pick-item-row ${cls}" data-item-id="${x.id}"><strong>${esc(displayItemNumber(x))}</strong><b>${need}</b><b>${got}</b><span class="pick-row-actions"><em class="picking-state ${unpicked>0?'soldout':complete?'done':'not-done'}">${unpicked>0?(unpicked<need?'일부품절 '+unpicked:'전체품절'):complete?'피킹완료':'피킹미완료'}</em><button data-minus="${x.id}">-1</button><button data-plus="${x.id}" ${got+unpicked>=need?'disabled':''}>+1</button><label class="soldout-check"><input type="checkbox" data-soldout-toggle="${x.id}" ${unpicked>0?'checked':''}>품절</label>${['S','B','I'].includes(section.code)?`<label class="warehouse-outbound-check warehouse-check-${section.code.toLowerCase()}"><input type="checkbox" data-outbound-check="${x.id}" data-outbound-code="${section.code}" ${checked?'checked':''}>${section.code}출고</label><input class="picking-item-note" type="text" maxlength="100" value="${esc(x.picking_note||'')}" placeholder="메모" data-picking-note="${x.id}" aria-label="${esc(displayItemNumber(x))} 피킹 메모">`:''}</span></div>`}).join('')}</div></div></section>`}).join('')}
function renderList(){const q=norm($('orderSearch').value);const visible=groups.filter(g=>!q||norm([g.orderNumber,g.customerName,g.deliveryName,g.assignedName,...g.items.map(x=>x.item_number)].join(' ')).includes(q));$('orderList').innerHTML=visible.length?visible.map(g=>{const t=totals(g),shortages=g.items.filter(x=>stockStatus(x).warning),done=g.status==='출고완료',live=g.items.some(x=>x.picking_session_active===true),mine=live&&String(g.assignedTo)===String(currentPicker.id),pickerLabel=live?`${mine?'내 작업':'담당 '+(g.assignedName||'다른 관리자')}`:'';return `<button class="order-pick-card ${active?.orderNumber===g.orderNumber?'active':''} ${shortages.length&&!done?'has-stock-warning':''} ${live?'picking-live':''} ${mine?'my-picking-order':''} ${g.revisionStatus?'revision-locked':''}" data-order="${esc(g.orderNumber)}"><strong>${esc(g.customerName)} ${g.isProxy?'<em class="proxy-order-badge">관리자 대신주문</em>':''} ${g.revisionStatus?`<em class="pick-stock-order-badge">${esc(g.revisionStatus==='수정중'?'고객 수정중':'수정완료·관리자 확인필요')}</em>`:''} ${live&&!done?`<em class="picking-live-badge">● ${esc(pickerLabel)} 피킹중</em>`:''} ${done?'<em class="proxy-order-badge">출고완료·결과확인</em>':!g.revisionStatus&&shortages.length?`<em class="pick-stock-order-badge">⚠ 재고부족 ${shortages.length}품번</em>`:''}</strong><span class="pick-delivery-name"><b>납품처</b> ${esc(g.deliveryName||g.customerName||'-')}</span>${live?`<span class="pick-assignee"><b>담당자</b> ${esc(g.assignedName||'관리자')}${g.assignedDevice?` · ${esc(g.assignedDevice)}`:''}</span>`:''}<span class="pick-order-number">${esc(g.orderNumber)}</span><small class="pick-order-counts">${g.items.length}품번 · 총 ${t.ordered}죽 · 처리 ${t.processed}/${t.ordered}</small></button>`}).join(''):'<p>피킹 대기 주문이 없습니다.</p>'}
function focusScan(){setTimeout(()=>$('pickScanInput')?.focus({preventScroll:true}),30)}
function decorateStockWarnings(){if(!active||active.status==='출고완료')return;const sorted=warehouseSections(active.items).flatMap(section=>section.items),rows=[...document.querySelectorAll('#workArea .pick-item-row')],shortages=[];rows.forEach((row,index)=>{const item=sorted[index],status=stockStatus(item);if(!item||!status.warning)return;shortages.push({item,status});row.classList.add('stock-warning',status.kind);const strong=row.querySelector('strong');if(strong&&!strong.querySelector('.pick-stock-warning'))strong.insertAdjacentHTML('beforeend',` <small class="pick-stock-warning ${status.kind}">⚠ ${esc(status.text)} / 주문 ${Number(item.qty||0)}죽</small>`) });const existing=document.querySelector('#workArea .pick-stock-alert');if(existing)existing.remove();if(shortages.length){const alert=document.createElement('div');alert.className='pick-stock-alert';alert.innerHTML=`<strong>⚠ ERP 재고 확인 필요: ${shortages.length}품번</strong><span>${shortages.map(x=>`${esc(displayItemNumber(x.item))} (${esc(x.status.text)})`).join(' · ')}</span>`;document.querySelector('#workArea .pick-status')?.insertAdjacentElement('afterend',alert)}}
function renderWork(message='',type='',shouldFocus=true){
 if(!active){$('workArea').innerHTML='<div class="empty-work">주문을 선택하세요.</div>';return}
 const verified=active.items.some(x=>String(x.picking_status||'').includes('검증완료')),revisionBlocked=Boolean(active.revisionStatus),pickingActive=active.items.some(x=>x.picking_session_active===true),assignedTo=String(active.assignedTo||active.items.find(x=>x.picking_assigned_to)?.picking_assigned_to||''),assignedName=active.assignedName||active.items.find(x=>x.picking_assigned_name)?.picking_assigned_name||'',mine=pickingActive&&assignedTo===String(currentPicker.id),otherPicker=pickingActive&&!mine,canForce=['admin','developer_admin'].includes(currentPicker.role),t=totals(active),completedCount=active.items.filter(x=>Number(x.picked_qty||0)+Number(x.soldout_qty||0)===Number(x.qty||0)).length,incompleteCount=active.items.length-completedCount,allOk=incompleteCount===0,canDelete=!revisionBlocked&&!pickingActive&&active.items.every(x=>Number(x.picked_qty||0)===0&&Number(x.soldout_qty||0)===0&&!x.is_soldout&&["","대기"].includes(String(x.picking_status||"대기")));
 const warehouseSummary=warehouseSections(active.items).map(section=>`<span class="warehouse-summary warehouse-${section.code.toLowerCase()}">${esc(section.label)} ${section.items.length}품번</span>`).join('');
 $('workArea').innerHTML=`<div class="work-header"><div><h2>${esc(active.customerName)} ${active.isProxy?'<small class="proxy-order-badge">관리자 대신주문</small>':''}</h2><p>납품처 ${esc(active.deliveryName||'-')}</p><p>주문번호 ${esc(active.orderNumber)} · ${new Date(active.createdAt).toLocaleString('ko-KR')}</p>${pickingActive?`<p class="active-picker-banner"><b>피킹 담당자</b> ${esc(assignedName||'관리자')} ${mine?'· 현재 내 작업':''}</p>`:''}<div class="pick-order-summary"><span>품번 ${active.items.length}종</span><span>수량 ${t.ordered}죽</span></div><div class="warehouse-summary-list">${warehouseSummary}</div></div><div class="pick-progress"><b>총 ${t.ordered}죽</b><span class="picking-complete-text">피킹완료 ${completedCount}품번</span><span class="picking-incomplete-text">피킹미완료 ${incompleteCount}품번</span></div></div><div class="scan-quantity-control"><strong>바코드 1회 스캔수량</strong><button type="button" data-scan-qty="1" class="${scanIncrement===1?'active':''}">1개</button><button type="button" data-scan-qty="10" class="${scanIncrement===10?'active':''}">10개</button><button type="button" id="togglePickingSession" class="picking-session-button ${mine?'active':''}" ${otherPicker?'disabled':''}>${mine?'내 피킹중·종료':otherPicker?`${esc(assignedName||'다른 관리자')} 피킹중`:'피킹시작'}</button>${otherPicker&&canForce?'<button type="button" id="forceReleasePicking" class="picking-force-release">관리자 담당해제</button>':''}<span>현재 ${scanIncrement}개씩 반영 · ${mine?'내 계정으로 피킹중':otherPicker?'다른 계정 작업을 실시간 확인중':'시작 대기'}</span></div><div class="pick-status ${type}">${message||(otherPicker?`${esc(assignedName||'다른 관리자')} 계정이 피킹 중입니다. 이 화면은 실시간 확인 전용입니다.`:`바코드를 스캔하면 해당 품번의 피킹수량이 ${scanIncrement}개씩 올라갑니다.`)}</div>${renderWarehousePickSections(active.items)}<div class="pick-controls"><button class="pick-action print-btn" id="printWork">출고지별 작업지시서 인쇄</button><button class="pick-action reset-btn" id="resetPick">피킹 초기화</button>${canDelete?`<button class="pick-action delete-order-btn" id="deleteWholeOrder">피킹 전 주문 전체삭제</button>`:""}<button class="pick-action verify-btn" id="verifyPick" ${verified||!allOk||!mine?'disabled':''}>${verified?'피킹 최종검증 완료됨':'피킹 최종검증 완료'}</button></div>`;
 if(!mine)document.querySelectorAll('#workArea [data-bulk-pick]').forEach(button=>{button.disabled=true;button.title=otherPicker?'다른 담당자가 피킹 중입니다.':'피킹시작 버튼을 먼저 누르세요.'});
 if(verified){const button=$('verifyPick');if(button){const done=document.createElement('span');done.className='picking-verified-complete';done.textContent='✓ 피킹 최종검증 완료';button.replaceWith(done)}}
 if(revisionBlocked){const lock=document.createElement('div');lock.className='pick-stock-alert';lock.innerHTML=`<strong>🔒 ${esc(active.revisionStatus==='수정중'?'고객이 주문을 수정하고 있습니다.':'고객 수정완료·관리자 변경확인이 필요합니다.')}</strong><span>주문관리에서 변경확인을 완료한 뒤 다시 피킹할 수 있습니다.</span>`;$('workArea').prepend(lock)}
 bindWork();if(verified||active.status==='출고완료'||revisionBlocked||otherPicker||!pickingActive){document.querySelectorAll('#workArea [data-minus],#workArea [data-plus],#workArea [data-soldout-toggle],#workArea [data-outbound-check],#workArea [data-picking-note],#workArea [data-bulk-pick],#workArea [data-scan-qty],#resetPick,#verifyPick').forEach(element=>element.disabled=true);const status=$('workArea').querySelector('.pick-status');if(status&&!message&&(verified||active.status==='출고완료'||revisionBlocked)){status.classList.add('ok');status.textContent=revisionBlocked?'고객 주문변경 확인 전에는 피킹할 수 없습니다.':active.status==='출고완료'?'출고완료 주문의 피킹결과입니다. 결과 확인 전용으로 표시됩니다.':'피킹 최종검증이 완료된 결과입니다. 주문관리에서 출고정보를 확인하세요.'}}if(shouldFocus&&mine&&!verified&&active.status!=='출고완료'&&!revisionBlocked)focusScan()
}
function isMyActivePicking(){return Boolean(active?.items.some(row=>row.picking_session_active===true))&&String(active?.assignedTo||active?.items.find(row=>row.picking_assigned_to)?.picking_assigned_to||'')===String(currentPicker.id)}
async function updateRow(row,picked,soldout){if(!isMyActivePicking()){renderWork('이 주문의 피킹 담당자가 아닙니다. 피킹시작을 먼저 눌러주세요.','error');return false}picked=Math.max(0,Number(picked||0));soldout=Math.max(0,Number(soldout||0));if(picked+soldout>Number(row.qty||0)){renderWork(`${row.item_number} 주문 수량을 초과할 수 없습니다.`,'error');return false}const {error}=await supabaseClient.from('orders').update({picked_qty:picked,soldout_qty:soldout,is_soldout:soldout>=Number(row.qty||0),picking_status:picked+soldout>0?'피킹중':'대기',picking_started_at:picked+soldout>0?new Date().toISOString():null}).eq('id',row.id).eq('picking_assigned_to',currentPicker.id).eq('picking_session_active',true);if(error){renderWork(error.message,'error');return false}row.picked_qty=picked;row.soldout_qty=soldout;row.is_soldout=soldout>=Number(row.qty||0);renderList();renderWork();return true}
async function scan(code){if(!active)return;if(!isMyActivePicking())return renderWork('내 계정으로 피킹시작을 먼저 눌러주세요. 다른 담당자의 주문은 스캔할 수 없습니다.','error');if(active.revisionStatus)return renderWork('고객 주문변경 확인 전에는 피킹할 수 없습니다.','error');const candidates=scanCandidates(code);const item=active.items.find(x=>{const itemCandidates=scanCandidates(x.item_number);return candidates.some(c=>itemCandidates.includes(c))});if(!item){renderWork(`주문목록에 없는 품번입니다: ${String(code).trim()}`,'error');navigator.vibrate?.(180);return}const need=Number(item.qty||0),got=Number(item.picked_qty||0),sold=Number(item.soldout_qty||0),available=availableStock(item);if(got+sold>=need){renderWork(`${item.item_number}은 주문수량 ${need}죽을 모두 처리했습니다. 초과 스캔을 차단했습니다.`,'error');navigator.vibrate?.([120,80,120]);return}const pickLimit=available===null?need:Math.min(need,available),add=Math.min(scanIncrement,Math.max(0,pickLimit-got)),nextSold=got+add>=pickLimit?Math.max(sold,need-(got+add)):sold;if(add<=0)return updateRow(item,got,nextSold);const {data,error}=await supabaseClient.rpc('increment_assigned_order_pick',{p_order_number:active.orderNumber,p_order_row_id:Number(item.id),p_increment:add});if(error){renderWork(`동시 피킹 반영 실패: ${error.message}\nV6.5.96 SQL 실행 여부를 확인하세요.`,'error');return}item.picked_qty=Number(data?.picked_qty??got);item.soldout_qty=Number(data?.soldout_qty??sold);item.picking_status='피킹중';const actualAdd=Number(data?.added||0);renderList();renderWork(`${item.item_number} 피킹 +${actualAdd} · ${item.picked_qty}/${need}`,'ok')}
async function setSoldout(id,checked){const r=orders.find(x=>String(x.id)===String(id));if(!r)return;const need=Number(r.qty||0),picked=Number(r.picked_qty||0);if(checked){const remain=Math.max(0,need-picked);if(!remain){renderWork(`${r.item_number}은 이미 모두 피킹되었습니다.`,'error');return}if(!confirm(`${r.item_number} 남은 ${remain}죽을 품절 처리할까요?\n품절 문구가 표시되며 최종검증은 완료할 수 있습니다.`)){renderWork();return}if(await updateRow(r,picked,remain))renderWork(`${r.item_number} 남은 ${remain}죽을 품절 처리했습니다. 모든 품번 처리가 끝나면 최종검증할 수 있습니다.`,'success')}else{if(!confirm(`${r.item_number} 품절 체크를 해제할까요?`)){renderWork();return}await updateRow(r,picked,0)}}
async function bulkCompleteWarehouse(code){
 if(!isMyActivePicking()){renderWork('내 계정으로 피킹시작 버튼을 누른 뒤 일괄피킹을 진행하세요.','error');return}
 if(!active||!['S','B','I'].includes(code))return;
 const rows=active.items.filter(item=>warehouseCode(item)===code),isComplete=rows.length>0&&rows.every(row=>Number(row.picked_qty||0)+Number(row.soldout_qty||0)>=Number(row.qty||0));
 if(!rows.length)return;
 if(isComplete){
  if(!confirm(`${code} 출고지 ${rows.length}품번의 피킹을 모두 취소하고 0으로 되돌릴까요?`))return;
  const results=await Promise.all(rows.map(row=>supabaseClient.from('orders').update({picked_qty:0,soldout_qty:0,is_soldout:false,picking_status:'대기',picking_started_at:null}).eq('id',row.id).eq('picking_assigned_to',currentPicker.id)));
  const failed=results.find(result=>result.error);if(failed)return renderWork(`${code} 출고지 일괄취소 실패: ${failed.error.message}`,'error');
  rows.forEach(row=>{row.picked_qty=0;row.soldout_qty=0;row.is_soldout=false;row.picking_status='대기';row.picking_started_at=null});renderList();renderWork(`${code} 출고지 ${rows.length}품번의 피킹을 일괄취소했습니다.`,'success');return;
 }
 if(!confirm(`${code} 출고지 ${rows.length}품번을 재고수량에 맞춰 일괄피킹할까요?\n재고 부족분은 자동으로 품절 처리됩니다.`))return;
 const startedAt=new Date().toISOString();
 const remainingByItem=new Map();
 const allocations=rows.map(row=>{const key=stockKey(row.item_number);if(!remainingByItem.has(key))remainingByItem.set(key,availableStock(row));const need=Number(row.qty||0),available=remainingByItem.get(key),picked=available===null?need:Math.min(need,Math.max(0,Number(available||0))),soldout=Math.max(0,need-picked);if(available!==null)remainingByItem.set(key,Math.max(0,Number(available||0)-picked));return{row,picked,soldout}});
 const results=await Promise.all(allocations.map(({row,picked,soldout})=>supabaseClient.from('orders').update({picked_qty:picked,soldout_qty:soldout,is_soldout:soldout>=Number(row.qty||0),picking_status:'피킹중',picking_started_at:startedAt}).eq('id',row.id).eq('picking_assigned_to',currentPicker.id)));
 const failed=results.find(result=>result.error);if(failed)return renderWork(`${code} 출고지 일괄피킹 실패: ${failed.error.message}`,'error');
 allocations.forEach(({row,picked,soldout})=>{row.picked_qty=picked;row.soldout_qty=soldout;row.is_soldout=soldout>=Number(row.qty||0);row.picking_status='피킹중'});const shortageItems=allocations.filter(x=>x.soldout>0),pickedTotal=allocations.reduce((sum,x)=>sum+x.picked,0),soldoutTotal=allocations.reduce((sum,x)=>sum+x.soldout,0);renderList();renderWork(`${code} 출고지 일괄피킹 완료 · 피킹 ${pickedTotal}죽${soldoutTotal?` · 품절 ${soldoutTotal}죽 (${shortageItems.length}품번)`:''}`,'success');
}
async function setOutboundConfirmed(id,code,checked){
 code=String(code||'').toUpperCase();const row=orders.find(item=>String(item.id)===String(id));if(!isMyActivePicking()||!row||!['S','B','I'].includes(code)||warehouseCode(row)!==code)return;
 const field=`${code.toLowerCase()}_outbound_confirmed`,{error}=await supabaseClient.from('orders').update({[field]:Boolean(checked)}).eq('id',row.id).eq('picking_assigned_to',currentPicker.id);
 if(error){renderWork(`${code} 출고기록 저장 실패: SQL/V6.5.13-LIVE-PICKING-RESERVATION.sql을 먼저 실행해 주세요. ${error.message}`,'error');return}
 row[field]=Boolean(checked);renderWork(`${displayItemNumber(row)} ${code} 출고체크를 ${checked?'기록':'해제'}했습니다.`,'success',false);
}
async function setPickingSetting(field,value,message){if(!active)return;if(active.revisionStatus)return renderWork('고객 주문변경 확인 전에는 피킹을 시작할 수 없습니다.','error');if(!isMyActivePicking())return renderWork('내 계정으로 피킹 중인 주문에서만 설정을 변경할 수 있습니다.','error');const orderNumber=active.orderNumber;const {error}=await supabaseClient.from('orders').update({[field]:value}).eq('order_number',orderNumber).eq('picking_assigned_to',currentPicker.id);if(error)return renderWork(`피킹 설정 저장 실패: ${error.message}`,'error');active.items.forEach(row=>row[field]=value);orders.filter(row=>row.order_number===orderNumber).forEach(row=>row[field]=value);if(field==='picking_scan_increment')scanIncrement=Number(value)===10?10:1;buildGroups();active=groups.find(group=>group.orderNumber===orderNumber)||active;renderList();renderWork(message,'success',false);pickingLiveChannel?.send({type:'broadcast',event:'picking-setting',payload:{orderNumber,field,value,assignedTo:currentPicker.id}}).catch(()=>{})}
function pickingDeviceLabel(){const mobile=/Android|iPhone|iPad|Mobile/i.test(navigator.userAgent);return `${mobile?'모바일·태블릿':'PC'} · ${navigator.platform||'기기'}`.slice(0,190)}
async function releaseMyPreviousPicking(targetOrder){
 const {data,error}=await supabaseClient.from('orders')
  .select('order_number,customer_name,status,picked_qty,soldout_qty')
  .eq('picking_assigned_to',currentPicker.id)
  .eq('picking_session_active',true)
  .neq('order_number',targetOrder);
 if(error){renderWork(`이전 피킹 작업 조회 실패: ${error.message}`,'error');return false}
 const sessionMap=new Map();
 (data||[]).forEach(row=>{const key=String(row.order_number||'');if(!key)return;const item=sessionMap.get(key)||{orderNumber:key,customerName:row.customer_name||'거래처 미입력',status:row.status||'',hasProgress:false};item.hasProgress=item.hasProgress||Number(row.picked_qty||0)>0||Number(row.soldout_qty||0)>0;sessionMap.set(key,item)});
 const mine=[...sessionMap.values()];
 if(!mine.length)return true;
 const hasProgress=mine.some(group=>group.hasProgress);
 if(hasProgress&&!confirm(`내 계정에 이전 피킹 작업이 남아 있습니다.\n${mine.map(group=>`· ${group.customerName} (${group.orderNumber})`).join('\n')}\n\n이전 담당만 종료하고 새 주문을 시작할까요?\n기존 피킹수량은 그대로 유지됩니다.`))return false;
 for(const group of mine){
  const {error:releaseError}=await supabaseClient.rpc('release_order_picking',{p_order_number:group.orderNumber,p_force:false});
  if(releaseError){renderWork(`이전 피킹 작업 정리 실패: ${releaseError.message}`,'error');return false}
 }
 return true;
}
async function toggleAssignedPicking(){if(!active||active.revisionStatus)return;if(isMyActivePicking()){if(!confirm('내 피킹 작업을 종료하고 이 주문의 담당을 해제할까요?\n피킹된 수량은 그대로 유지됩니다.'))return;const {error}=await supabaseClient.rpc('release_order_picking',{p_order_number:active.orderNumber,p_force:false});if(error)return renderWork('피킹 종료 실패: '+error.message,'error');await load(false);return renderWork('내 피킹 담당을 해제했습니다. 피킹수량은 유지됩니다.','success',false)}const existing=active.items.some(row=>row.picking_session_active===true);if(existing)return renderWork(`${active.assignedName||'다른 관리자'} 계정이 이미 피킹 중입니다.`,'error');const orderNumber=active.orderNumber;if(!(await releaseMyPreviousPicking(orderNumber)))return;const {error}=await supabaseClient.rpc('claim_order_picking',{p_order_number:orderNumber,p_device_name:pickingDeviceLabel(),p_force:false});if(error)return renderWork('피킹 시작 실패: '+error.message,'error');await load(false);active=groups.find(group=>group.orderNumber===orderNumber)||active;renderList();renderWork(`${currentPicker.name} 계정으로 피킹을 시작했습니다. 다른 PC는 각자 선택한 주문 화면을 유지합니다.`,'success',true)}
async function forceReleaseAssignedPicking(){if(!active||!['admin','developer_admin'].includes(currentPicker.role))return;if(!confirm(`${active.assignedName||'다른 담당자'}의 피킹 담당을 강제로 해제할까요?\n현재 피킹수량은 그대로 유지됩니다.`))return;const orderNumber=active.orderNumber,{error}=await supabaseClient.rpc('release_order_picking',{p_order_number:orderNumber,p_force:true});if(error)return renderWork('담당자 해제 실패: '+error.message,'error');await load(false);active=groups.find(group=>group.orderNumber===orderNumber)||active;renderList();renderWork('관리자가 기존 피킹 담당을 해제했습니다.','success',false)}
async function savePickingNote(id,value,input){const row=orders.find(item=>String(item.id)===String(id));if(!isMyActivePicking()||!row)return;const note=String(value||'').trim().slice(0,100);input.disabled=true;const {error}=await supabaseClient.from('orders').update({picking_note:note}).eq('id',row.id).eq('picking_assigned_to',currentPicker.id);input.disabled=false;if(error){alert(`피킹 메모 저장 실패: ${error.message}\nSQL/V6.5.16-PICKING-ITEM-NOTE.sql을 먼저 실행해주세요.`);return}row.picking_note=note;input.value=note;input.classList.add('saved');setTimeout(()=>input.classList.remove('saved'),900)}
async function resetPick(skipConfirm=false){if(!isMyActivePicking())return renderWork('현재 피킹 담당자만 초기화할 수 있습니다.','error');if(!skipConfirm&&!confirm('이 주문의 피킹·미피킹 수량을 모두 초기화할까요?\n최종검증된 주문이면 차감된 ERP 재고도 함께 복원됩니다.'))return false;const orderNumber=active?.orderNumber;if(!orderNumber)return false;const {data,error}=await supabaseClient.rpc('reset_order_picking',{p_order_number:orderNumber,p_device_name:'피킹 초기화'});if(error){renderWork('피킹 초기화 실패: '+error.message,'error');return false}const clearChecks=await supabaseClient.from('orders').update({s_outbound_confirmed:false,b_outbound_confirmed:false,i_outbound_confirmed:false,picking_session_active:false,picking_scan_increment:1,picking_assigned_to:null,picking_assigned_name:null,picking_assigned_device:null,picking_assigned_at:null}).eq('order_number',orderNumber);if(clearChecks.error&&!/outbound_confirmed/i.test(String(clearChecks.error.message||'')))console.warn('SBI 출고체크 초기화 실패',clearChecks.error);await load(false);active=groups.find(g=>g.orderNumber===orderNumber)||active;renderList();renderWork(`피킹수량과 이전 검증상태를 초기화했습니다.${Number(data?.restored_quantity||0)>0?` ERP 재고 ${Number(data.restored_quantity)}개를 복원했습니다.`:''} 다시 피킹 후 최종검증할 수 있습니다.`,'success');return true}
async function prepareEditReset(){if(!active)return false;const orderNumber=active.orderNumber;if(!isMyActivePicking()){const occupied=active.items.some(row=>row.picking_session_active===true&&row.picking_assigned_to);if(occupied)return renderWork(`${active.assignedName||'다른 관리자'} 계정이 피킹 중이라 수정모드로 전환할 수 없습니다.`,'error');if(!(await releaseMyPreviousPicking(orderNumber)))return false;const {error}=await supabaseClient.rpc('claim_order_picking',{p_order_number:orderNumber,p_device_name:pickingDeviceLabel(),p_force:false});if(error)return renderWork('피킹 수정 준비 실패: '+error.message,'error');await load(false);active=groups.find(group=>group.orderNumber===orderNumber)||active}return resetPick(true)}
async function deleteWholeOrder(){if(!active)return;const orderNumber=active.orderNumber,customer=active.customerName,itemCount=active.items.length;if(!confirm(`피킹 전 주문 전체삭제\n\n거래처: ${customer}\n주문번호: ${orderNumber}\n품번: ${itemCount}개\n\n삭제 전 원본은 삭제 주문 이력에 보관됩니다. 계속할까요?`))return;if(!confirm(`정말 삭제할까요?\n삭제한 주문은 복구할 수 없습니다.\n${orderNumber}`))return;const {error}=await supabaseClient.rpc('delete_order_and_restore_inventory',{p_order_number:orderNumber,p_device_name:'피킹 전 주문 전체삭제'});if(error)return renderWork(`주문 전체삭제 실패: SQL/V6.5.28-PRE-PICK-ORDER-MANAGEMENT.sql을 먼저 실행해 주세요. ${error.message}`,'error');orders=orders.filter(row=>row.order_number!==orderNumber);active=null;buildGroups();renderList();renderWork();alert(`${customer} 피킹 전 주문을 전체삭제했습니다.`)}
async function verify(){if(!isMyActivePicking())return alert('현재 피킹 담당자만 최종검증할 수 있습니다.');if(!active.items.every(x=>Number(x.picked_qty||0)+Number(x.soldout_qty||0)===Number(x.qty||0)))return alert('피킹수량과 미피킹 처리수량의 합이 주문수량과 일치해야 합니다.');if(!confirm('최종 검증 후 재고를 차감하고 주문관리의 출고대기로 이동할까요?'))return;const {data,error}=await supabaseClient.rpc('complete_order_picking',{p_order_number:active.orderNumber,p_device_name:`피킹검증 · ${currentPicker.name}`});if(error)return renderWork(error.message,'error');await supabaseClient.rpc('release_order_picking',{p_order_number:active.orderNumber,p_force:false});localStorage.setItem('designjam_picking_verified',JSON.stringify({orderNumber:active.orderNumber,at:Date.now()}));alert(`피킹 최종검증 완료\n담당자: ${currentPicker.name}\n거래처: ${data?.customer_name||active.customerName}\n주문번호: ${active.orderNumber}\n주문관리에서 송장정보 확인 후 출고완료하세요.`);location.replace(`admin.html?view=orders&status=${encodeURIComponent('출고대기')}&order=${encodeURIComponent(active.orderNumber)}&refresh=${Date.now()}`)}
function printWorkSheet(warehouse=''){const area=document.getElementById('workArea');if(!area||!active)return;const clone=area.cloneNode(true);if(warehouse)clone.querySelectorAll('.warehouse-pick-section').forEach(section=>{if(section.dataset.warehouseCode!==warehouse)section.remove()});clone.querySelectorAll('.pick-controls,.pick-status,.scan-quantity-control,button,input,label.soldout-check,label.warehouse-outbound-check').forEach(el=>el.remove());const selectedLabel=warehouse?warehouseLabel(warehouse)+' ':'';const win=window.open('','_blank','width=1000,height=800');if(!win){window.print();return}win.document.open();win.document.write(`<!doctype html><html lang="ko"><head><meta charset="utf-8"><title>${esc(selectedLabel)}작업지시서 ${esc(active?.orderNumber||'')}</title><style>@page{margin:8mm}*{box-sizing:border-box}html,body{margin:0;padding:0;background:#fff!important;color:#111;font-family:Arial,'Noto Sans KR',sans-serif}body::before,body::after,.work-header::before,.work-header::after{display:none!important}.work-area{width:100%;background:#fff!important;border:0!important;border-radius:0!important;box-shadow:none!important}.work-header{display:block!important;position:static!important;background:#fff!important;color:#111!important;border:0!important;border-radius:0!important;box-shadow:none!important;margin-bottom:18px;padding:0!important}.work-header h2{margin:0 0 6px;font-size:24px}.work-header p{margin:0;color:#444}.pick-progress,.proxy-order-badge{display:none!important}.warehouse-summary-list{display:flex;gap:8px;margin-top:8px}.warehouse-summary{border:1px solid #111;padding:4px 8px;font-weight:800}.warehouse-pick-section{break-inside:avoid;margin-top:12px}.warehouse-pick-section:not(:first-of-type){break-before:page}.warehouse-pick-section h3{display:flex;justify-content:space-between;align-items:center;margin:0 0 8px;padding:10px 12px;border:2px solid #000;font-size:20px}.warehouse-pick-section h3 small{font-size:13px}.pick-table-head,.pick-item-row{display:grid;grid-template-columns:1.3fr .55fr .55fr 1fr;gap:8px;align-items:center;min-width:0}.pick-table-head{background:#fff!important;color:#000;border-top:2px solid #000;border-bottom:2px solid #000;padding:8px;font-weight:900}.pick-item-row{padding:8px;border-bottom:1px solid #999;break-inside:avoid}.pick-table-head span,.pick-item-row strong,.pick-item-row b,.pick-row-actions{display:flex;justify-content:center;text-align:center}.pick-table-head span:first-child,.pick-item-row strong{justify-content:flex-start}.picking-state{display:inline-block;color:#000;background:none;border:0;font-style:normal;font-weight:800}</style></head><body>${clone.outerHTML}<script>window.onload=()=>{window.print();setTimeout(()=>window.close(),300)}<\/script></body></html>`);win.document.close()}
function bindWork(){decorateStockWarnings();$('printWork')?.addEventListener('click',()=>printWorkSheet());$('deleteWholeOrder')?.addEventListener('click',deleteWholeOrder);$('togglePickingSession')?.addEventListener('click',toggleAssignedPicking);$('forceReleasePicking')?.addEventListener('click',forceReleaseAssignedPicking);document.querySelectorAll('[data-print-warehouse]').forEach(button=>button.onclick=()=>printWorkSheet(button.dataset.printWarehouse));document.querySelectorAll('[data-scan-qty]').forEach(button=>button.onclick=()=>{const value=Number(button.dataset.scanQty)===10?10:1;setPickingSetting('picking_scan_increment',value,`바코드 1회 스캔수량을 ${value}개로 변경했습니다. 다른 기기에도 실시간 반영됩니다.`)});document.querySelectorAll('[data-bulk-pick]').forEach(button=>button.onclick=()=>bulkCompleteWarehouse(button.dataset.bulkPick));document.querySelectorAll('[data-outbound-check]').forEach(input=>input.onchange=()=>setOutboundConfirmed(input.dataset.outboundCheck,input.dataset.outboundCode,input.checked));document.querySelectorAll('[data-picking-note]').forEach(input=>{input.onkeydown=event=>event.stopPropagation();input.onchange=()=>savePickingNote(input.dataset.pickingNote,input.value,input)});$('resetPick')?.addEventListener('click',resetPick);$('verifyPick')?.addEventListener('click',verify);document.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>{const r=orders.find(x=>String(x.id)===b.dataset.minus);updateRow(r,Number(r.picked_qty||0)-1,r.soldout_qty)});document.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>{const r=orders.find(x=>String(x.id)===b.dataset.plus);if(Number(r.picked_qty||0)+Number(r.soldout_qty||0)>=Number(r.qty||0))return renderWork(`${r.item_number} 초과 수량은 추가할 수 없습니다.`,'error');const need=Number(r.qty||0),got=Number(r.picked_qty||0),available=availableStock(r),limit=available===null?need:Math.min(need,available),next=Math.min(got+1,limit),soldout=next>=limit?Math.max(Number(r.soldout_qty||0),need-next):Number(r.soldout_qty||0);updateRow(r,next,soldout)});document.querySelectorAll('[data-soldout-toggle]').forEach(c=>c.onchange=()=>setSoldout(c.dataset.soldoutToggle,c.checked))}
function syncActiveOrderUrl(orderNumber){if(!orderNumber)return;const params=new URLSearchParams(location.search);params.set('order',orderNumber);params.delete('edit');params.delete('print');history.replaceState(null,'',`${location.pathname}?${params.toString()}${location.hash}`)}
async function load(shouldFocus=true){const previous=active?.orderNumber||'',params=new URLSearchParams(location.search),requested=previous||params.get('order')||'';const [orderRows,inventoryRows]=await Promise.all([fetchAll(requested),fetchInventory()]);orders=orderRows;setInventory(inventoryRows);buildGroups();const requestedGroup=requested?groups.find(group=>group.orderNumber===requested):null,ownLiveGroup=groups.find(group=>group.items.some(row=>row.picking_session_active===true&&String(row.picking_assigned_to)===String(currentPicker.id)));active=requestedGroup||ownLiveGroup||null;if(active&&ownLiveGroup&&!requestedGroup)syncActiveOrderUrl(ownLiveGroup.orderNumber);if(active){const sharedStep=Number(active.items[0]?.picking_scan_increment||1);scanIncrement=sharedStep===10?10:1}renderList();renderWork('','',shouldFocus===true);if(params.get('edit')==='1'&&active&&!autoPrintHandled){autoPrintHandled=true;params.delete('edit');history.replaceState(null,'',`${location.pathname}?order=${encodeURIComponent(active.orderNumber)}`);setTimeout(prepareEditReset,150)}else if(params.get('print')==='1'&&active&&!autoPrintHandled){autoPrintHandled=true;params.delete('print');const cleanQuery=params.toString();history.replaceState(null,'',`${location.pathname}${cleanQuery?`?${cleanQuery}`:''}${location.hash}`);setTimeout(printWorkSheet,350)}}
function selectPickingOrder(orderNumber){
 const next=groups.find(group=>group.orderNumber===orderNumber);if(!next)return;
 active=next;
 const params=new URLSearchParams(location.search);params.set('order',active.orderNumber);params.delete('edit');params.delete('print');history.replaceState(null,'',`${location.pathname}?${params.toString()}${location.hash}`);
 renderList();renderWork();
 if(window.matchMedia('(max-width: 900px)').matches)setTimeout(()=>$('workArea')?.scrollIntoView({behavior:'smooth',block:'start'}),30);
}
document.addEventListener('DOMContentLoaded',async()=>{
 if(!(await guard()))return;
 $('refreshOrders').onclick=()=>load(true);$('orderSearch').oninput=renderList;
 if($('pickingSort'))$('pickingSort').onchange=e=>{pickingSort=e.target.value;renderWork()};
 $('orderList').onclick=e=>{const b=e.target.closest('[data-order]');if(!b)return;selectPickingOrder(b.dataset.order)};
 let buffer='',last=0,refreshTimer=null,refreshing=false,realtimeReady=false,lastSafetyRefresh=Date.now();
 const refreshPicking=async()=>{if(refreshing||document.activeElement?.matches?.('[data-picking-note]'))return;refreshing=true;try{await load(false)}finally{refreshing=false}};
 const schedulePickingRefresh=(delay=800)=>{clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>{lastSafetyRefresh=Date.now();refreshPicking()},delay)};
 const applyLiveSetting=payload=>{const orderNumber=String(payload?.orderNumber||''),field=String(payload?.field||''),value=payload?.value;if(!orderNumber||!['picking_session_active','picking_scan_increment'].includes(field))return;orders.filter(row=>row.order_number===orderNumber).forEach(row=>row[field]=value);buildGroups();if(active)active=groups.find(group=>group.orderNumber===active.orderNumber)||active;if(active&&field==='picking_scan_increment'&&active.orderNumber===orderNumber)scanIncrement=Number(value)===10?10:1;renderList();if(active?.orderNumber===orderNumber)renderWork(field==='picking_session_active'?'피킹 담당상태가 변경되었습니다.':`바코드 스캔수량이 ${Number(value)===10?10:1}개로 변경되었습니다.`,'success',false)};
 document.addEventListener('keydown',e=>{if(e.target?.matches?.('input:not(#pickScanInput),textarea,[contenteditable="true"]'))return;if(e.key==='Backspace'){buffer='';return}if(e.key==='Enter'){const fresh=Date.now()-last<=120;if(buffer&&fresh){scan(buffer);e.preventDefault()}buffer='';return}const key=keyFromEvent(e);if(key){const now=Date.now();if(now-last>120)buffer='';buffer+=key;last=now}});
 await load(true);
 pickingLiveChannel=supabaseClient.channel('picking-orders-live-v6639')
  .on('broadcast',{event:'picking-setting'},event=>applyLiveSetting(event.payload))
  .on('postgres_changes',{event:'UPDATE',schema:'public',table:'orders'},event=>{const row=event.new||{},local=orders.find(item=>String(item.id)===String(row.id));lastSafetyRefresh=Date.now();if(!local){schedulePickingRefresh();return}Object.assign(local,row);const activeNumber=active?.orderNumber||'';buildGroups();active=activeNumber?(groups.find(group=>group.orderNumber===activeNumber)||null):null;if(active){const sharedStep=Number(active.items[0]?.picking_scan_increment||1);scanIncrement=sharedStep===10?10:1}renderList();if(active?.orderNumber===row.order_number)renderWork('실시간 피킹 진행상태를 반영했습니다.','success',false)})
  .subscribe(status=>{realtimeReady=status==='SUBSCRIBED';if(['CHANNEL_ERROR','TIMED_OUT','CLOSED'].includes(status)&&!document.hidden)schedulePickingRefresh(1200)});
 setInterval(()=>{if(document.hidden)return;const now=Date.now();if(!realtimeReady||now-lastSafetyRefresh>=300000){lastSafetyRefresh=now;refreshPicking()}},30000);document.addEventListener('visibilitychange',()=>{if(!document.hidden){lastSafetyRefresh=Date.now();refreshPicking()}});
});
})();
