(function(){
  'use strict';
  const app=document.body?.dataset?.pwaApp||'customer';
  const name=app==='admin'?'디자인 삭스 관리자':'디자인 삭스';
  const icon=app==='admin'?'/icons/admin-192.png':'/icons/customer-192.png';
  let deferredPrompt=null;
  function injectStyles(){if(document.getElementById('designSocksPwaStyles'))return;const s=document.createElement('style');s.id='designSocksPwaStyles';s.textContent=`
  #dsPwaInstall{position:fixed;left:12px;bottom:12px;z-index:2147483000;display:flex;align-items:center;gap:10px;max-width:calc(100vw - 24px);padding:10px 12px;border:1px solid #d7e0eb;border-radius:16px;background:#fff;color:#102b52;box-shadow:0 12px 35px rgba(0,0,0,.2);font-family:Arial,sans-serif}#dsPwaInstall[hidden]{display:none!important}#dsPwaInstall img{width:42px;height:42px;border-radius:10px}#dsPwaInstall .ds-copy{min-width:0}#dsPwaInstall strong{display:block;font-size:13px}#dsPwaInstall small{display:block;color:#607086;font-size:11px;margin-top:2px}#dsPwaInstall button{border:0;border-radius:9px;padding:8px 10px;font-weight:800;cursor:pointer}#dsPwaInstall .install{background:#24589f;color:#fff}#dsPwaInstall .close{background:#eef2f7;color:#55606d}#dsSplash{position:fixed;inset:0;z-index:2147483646;display:grid;place-items:center;background:${app==='admin'?'#112437':'#fff'};transition:opacity .3s ease}#dsSplash.hide{opacity:0;pointer-events:none}#dsSplash .inner{text-align:center;color:${app==='admin'?'#fff':'#102b52'};font-family:Arial,sans-serif}#dsSplash img{width:118px;height:118px;border-radius:26px;box-shadow:0 14px 35px rgba(0,0,0,.15)}#dsSplash h1{margin:18px 0 5px;font-size:27px}#dsSplash p{margin:0;opacity:.75;font-weight:700}@media(max-width:520px){#dsPwaInstall{right:8px;left:8px;bottom:8px}}
  `;document.head.appendChild(s)}
  function isStandalone(){return window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true}
  function showSplash(){if(!isStandalone()||sessionStorage.getItem('ds_splash_seen_'+app))return;sessionStorage.setItem('ds_splash_seen_'+app,'1');const el=document.createElement('div');el.id='dsSplash';el.innerHTML=`<div class="inner"><img src="${icon}" alt=""><h1>${name}</h1><p>주문관리</p></div>`;document.body.appendChild(el);setTimeout(()=>{el.classList.add('hide');setTimeout(()=>el.remove(),350)},1050)}
  function ensureInstall(){if(isStandalone()||localStorage.getItem('ds_install_dismissed_'+app)==='1')return null;let el=document.getElementById('dsPwaInstall');if(el)return el;el=document.createElement('aside');el.id='dsPwaInstall';el.hidden=true;el.innerHTML=`<img src="${icon}" alt=""><div class="ds-copy"><strong>${name}</strong><small>홈 화면에 추가하면 앱처럼 바로 실행됩니다.</small></div><button type="button" class="install">설치</button><button type="button" class="close" aria-label="닫기">×</button>`;document.body.appendChild(el);el.querySelector('.close').onclick=()=>{el.hidden=true;localStorage.setItem('ds_install_dismissed_'+app,'1')};el.querySelector('.install').onclick=installApp;return el}
  async function installApp(){const el=ensureInstall();if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;if(el)el.hidden=true;return}const isiOS=/iphone|ipad|ipod/i.test(navigator.userAgent);alert(isiOS?'아이폰: 화면 아래 공유 버튼을 누른 뒤 “홈 화면에 추가”를 선택하세요.':'브라우저 메뉴에서 “홈 화면에 추가” 또는 “앱 설치”를 선택하세요.')}
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;const el=ensureInstall();if(el)el.hidden=false});
  window.addEventListener('appinstalled',()=>{const el=document.getElementById('dsPwaInstall');if(el)el.hidden=true;localStorage.setItem('ds_install_dismissed_'+app,'1')});
  window.designSocksInstallApp=installApp;
  document.addEventListener('DOMContentLoaded',()=>{injectStyles();showSplash();const isiOS=/iphone|ipad|ipod/i.test(navigator.userAgent);if(isiOS&&!isStandalone()){const el=ensureInstall();if(el)el.hidden=false}document.querySelectorAll('[data-install-app]').forEach(b=>b.addEventListener('click',installApp));if('serviceWorker'in navigator){navigator.serviceWorker.register('/service-worker.js').then(reg=>reg.update()).catch(console.warn)}});
})();