(function(){"use strict";
const ADMIN_SESSION_KEY="designjam_admin_session";const ADMIN_EMAILS=new Set(["900smk@naver.com","sm0727sm@hanmail.net","p1028p@naver.com"]);
let mode="IN",step=1,items=[],movements=[],recent=[];
const KO_TO_EN={
"ㅂ":"Q","ㅈ":"W","ㄷ":"E","ㄱ":"R","ㅅ":"T","ㅛ":"Y","ㅕ":"U","ㅑ":"I","ㅐ":"O","ㅔ":"P","ㅁ":"A","ㄴ":"S","ㅇ":"D","ㄹ":"F","ㅎ":"G","ㅗ":"H","ㅓ":"J","ㅏ":"K","ㅣ":"L","ㅋ":"Z","ㅌ":"X","ㅊ":"C","ㅍ":"V","ㅠ":"B","ㅜ":"N","ㅡ":"M",
"ᄇ":"Q","ᄌ":"W","ᄃ":"E","ᄀ":"R","ᄉ":"T","ᅭ":"Y","ᅧ":"U","ᅣ":"I","ᅢ":"O","ᅦ":"P","ᄆ":"A","ᄂ":"S","ᄋ":"D","ᄅ":"F","ᄒ":"G","ᅩ":"H","ᅥ":"J","ᅡ":"K","ᅵ":"L","ᄏ":"Z","ᄐ":"X","ᄎ":"C","ᄑ":"V","ᅲ":"B","ᅮ":"N","ᅳ":"M",
"ᆸ":"Q","ᆽ":"W","ᆮ":"E","ᆨ":"R","ᆺ":"T","ᆷ":"A","ᆫ":"S","ᆼ":"D","ᆯ":"F","ᇂ":"G","ᆿ":"Z","ᇀ":"X","ᆾ":"C","ᇁ":"V"
};
function normalizeScanCode(value){
  const raw=String(value??"").normalize("NFD");
  return raw.replace(/[\u0000-\u001F\u007F-\u009F\u200B-\u200D\uFEFF]/g,"")
    .replace(/\s+/g,"")
    .split("").map(ch=>KO_TO_EN[ch]||ch).join("")
    .normalize("NFKC").toUpperCase()
    .replace(/[^A-Z0-9_\-~]/g,"");
}
const $=id=>document.getElementById(id);const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function splitCodes(value){const raw=String(value??"").trim();if(!raw)return[];if(raw==="699810")return["699","810"];return raw.split(/[,，]/).flatMap(p=>{p=p.trim();const m=p.match(/^(\d+)([A-Za-z]*)~(\d+)([A-Za-z]*)$/);if(!m)return[p];if(m[2]!==m[4])return[p];const a=+m[1],b=+m[3];if(b<a||b-a>500)return[p];return Array.from({length:b-a+1},(_,i)=>`${a+i}${m[2]}`);});}
async function guard(){const {data:{user}}=await supabaseClient.auth.getUser();const stored=sessionStorage.getItem(ADMIN_SESSION_KEY)||localStorage.getItem(ADMIN_SESSION_KEY);if(!user||(stored&&stored!==user.id)){location.replace("admin.html");return false;}const {data:p}=await supabaseClient.from("customers").select("is_admin,blocked").eq("id",user.id).maybeSingle();if(!ADMIN_EMAILS.has((user.email||"").toLowerCase())&&!(p?.is_admin===true&&p?.blocked!==true)){location.replace("admin.html");return false;}document.body.classList.add("auth-ready");document.body.classList.remove("auth-pending");return true;}
function focusScanner(){setTimeout(()=>$('scanInput')?.focus({preventScroll:true}),30)}
function setStatus(title,text,type="ready"){$('scanStatus').className=`scan-status ${type}`;$('scanStatus').innerHTML=`<strong>${esc(title)}</strong><span>${esc(text)}</span>`;}
function renderRecent(){$('recentScans').innerHTML=recent.length?recent.map(r=>`<div class="scan-row ${r.ok?(r.mode==='IN'?'mode-in':'mode-out'):'fail'}"><div><strong>${esc(r.item)}</strong><small>${esc(r.text)}</small></div><time>${r.time}</time></div>`).join(""):'<p>아직 스캔 기록이 없습니다.</p>';}
function renderInventory(){const q=normalizeScanCode(($('inventorySearch').value||'').trim());let visible=items.filter(x=>{const item=normalizeScanCode(x.item_number);if(!q)return true;return item===q||item.startsWith(q)||normalizeScanCode(x.product_name).includes(q)||normalizeScanCode(x.brand).includes(q)||normalizeScanCode(x.location_code).includes(q);});visible.sort((a,b)=>{const aa=normalizeScanCode(a.item_number),bb=normalizeScanCode(b.item_number);if(q){if(aa===q&&bb!==q)return -1;if(bb===q&&aa!==q)return 1;}return aa.localeCompare(bb,'ko',{numeric:true});});visible=visible.slice(0,500);$('inventoryList').innerHTML=visible.length?visible.map(x=>`<div class="inventory-live-row ${x.quantity<=0?'out':x.quantity<=x.safety_stock?'low':''}"><div><strong class="inventory-item-number">${esc(x.item_number)}</strong><small>${esc(x.product_name||'상품명 미등록')}${x.brand?' · '+esc(x.brand):''}${x.location_code?' · 위치 '+esc(x.location_code):''} · 안전재고 ${Number(x.safety_stock||0).toLocaleString()}</small></div><b>${Number(x.quantity).toLocaleString()}개</b></div>`).join(''):'<p class="inventory-empty">검색된 개별 품번이 없습니다.</p>';$('totalSku').textContent=items.length.toLocaleString();$('totalQty').textContent=items.reduce((s,x)=>s+Number(x.quantity||0),0).toLocaleString();$('lowQty').textContent=items.filter(x=>Number(x.quantity)>0&&Number(x.quantity)<=Number(x.safety_stock||0)).length.toLocaleString();$('outQty').textContent=items.filter(x=>Number(x.quantity)<=0).length.toLocaleString();}
function renderMovements(){const q=($('movementSearch').value||'').trim().toLowerCase();const t=$('movementType').value;const visible=movements.filter(x=>(!t||x.movement_type===t)&&(!q||[x.item_number,x.device_name,x.order_number,x.note].join(' ').toLowerCase().includes(q)));$('movementList').innerHTML=visible.length?visible.map(x=>`<div class="movement-row"><div><strong>${esc(x.item_number)}</strong><small>${x.movement_type==='IN'?'입고':x.movement_type==='OUT'?'출고':'조정'} ${Number(x.quantity).toLocaleString()}개 · ${Number(x.quantity_before).toLocaleString()} → ${Number(x.quantity_after).toLocaleString()}</small></div><div class="movement-meta"><span>${esc(x.device_name||'PC 미지정')}</span><time>${new Date(x.created_at).toLocaleString('ko-KR')}</time></div></div>`).join(''):'<p>표시할 작업이력이 없습니다.</p>';}
async function loadInventory(){const {data,error}=await supabaseClient.from('inventory_items').select('*').order('item_number');if(error){setStatus('설치 필요',error.message,'error');return;}items=data||[];renderInventory();}
async function loadMovements(){const {data,error}=await supabaseClient.from('inventory_movements').select('*').order('created_at',{ascending:false}).limit(300);if(error){$('movementList').innerHTML=`<p>${esc(error.message)}</p>`;return;}movements=data||[];renderMovements();}
async function syncProducts(){setStatus('상품 동기화 중','주문 프로그램 상품 품번을 재고 마스터에 등록합니다.');const {data:groups,error}=await supabaseClient.from('product_groups').select('id,title,item_numbers');if(error){setStatus('동기화 실패',error.message,'error');return;}const rows=[];for(const g of groups||[])for(const code of (Array.isArray(g.item_numbers)?g.item_numbers:[]).flatMap(splitCodes)){const c=String(code).trim();if(c)rows.push({item_number:c,barcode:c,product_group_id:g.id,product_name:g.title||'',updated_at:new Date().toISOString()});}const unique=[...new Map(rows.map(x=>[x.item_number,x])).values()];const {error:upError}=await supabaseClient.from('inventory_items').upsert(unique,{onConflict:'item_number'});if(upError){setStatus('동기화 실패',upError.message,'error');return;}setStatus('동기화 완료',`${unique.length.toLocaleString()}개 품번이 연결되었습니다.`,'success');await loadInventory();focusScanner();}
async function applyScan(raw){let code=normalizeScanCode(raw);if(!code)return;const mapped=splitCodes(code);if(mapped.length>1){setStatus('묶음 바코드 사용 불가',`${code}는 ${mapped.join(', ')}로 분리된 품번입니다. 개별 라벨을 스캔하세요.`,'error');recent.unshift({ok:false,mode,item:code,text:'개별 품번 스캔 필요',time:new Date().toLocaleTimeString('ko-KR')});renderRecent();return;}code=mapped[0];setStatus('처리 중',`${code} ${mode==='IN'?'입고':'출고'} ${step}개`);const {data,error}=await supabaseClient.rpc('apply_inventory_scan',{p_item_number:code,p_mode:mode,p_increment:step,p_device_name:$('deviceName').value||'',p_order_number:null});if(error){setStatus('처리 실패',error.message,'error');recent.unshift({ok:false,mode,item:code,text:error.message,time:new Date().toLocaleTimeString('ko-KR')});}else{const row=Array.isArray(data)?data[0]:data;setStatus('처리 완료',`${row.item_number} · 현재재고 ${Number(row.quantity).toLocaleString()}개`,'success');recent.unshift({ok:true,mode,item:row.item_number,text:`${mode==='IN'?'입고':'출고'} ${step}개 → 재고 ${row.quantity}개`,time:new Date().toLocaleTimeString('ko-KR')});const found=items.find(x=>normalizeScanCode(x.item_number)===normalizeScanCode(row.item_number));if(found)found.quantity=Number(row.quantity);else await loadInventory();renderInventory();await loadMovements();}recent=recent.slice(0,30);renderRecent();focusScanner();}
function csvDownload(name,rows){if(!rows.length){alert('내보낼 데이터가 없습니다.');return;}const cols=Object.keys(rows[0]);const escCsv=v=>`"${String(v??'').replace(/"/g,'""')}"`;const csv='\ufeff'+[cols.join(','),...rows.map(r=>cols.map(c=>escCsv(r[c])).join(','))].join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function bind(){document.querySelectorAll('.scanner-mode').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('.scanner-mode').forEach(x=>x.classList.toggle('active',x===b));focusScanner();});document.querySelectorAll('.step-btn').forEach(b=>b.onclick=()=>{step=+b.dataset.step;document.querySelectorAll('.step-btn').forEach(x=>x.classList.toggle('active',x===b));focusScanner();});$('syncProducts').onclick=syncProducts;$('refreshMovements').onclick=loadMovements;$('exportInventory').onclick=()=>csvDownload(`design-socks-inventory-${new Date().toISOString().slice(0,10)}.csv`,items);$('exportMovements').onclick=()=>csvDownload(`design-socks-movements-${new Date().toISOString().slice(0,10)}.csv`,movements);$('inventorySearch').oninput=renderInventory;$('movementSearch').oninput=renderMovements;$('movementType').onchange=renderMovements;$('deviceName').value=localStorage.getItem('designjam.scanner.device')||'';$('deviceName').onchange=e=>localStorage.setItem('designjam.scanner.device',e.target.value);$('scanInput').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();const v=e.target.value;e.target.value='';applyScan(v);}});document.addEventListener('click',e=>{if(!e.target.closest('input,button,select'))focusScanner();});window.addEventListener('focus',focusScanner);}
document.addEventListener('DOMContentLoaded',async()=>{if(!(await guard()))return;bind();await Promise.all([loadInventory(),loadMovements()]);supabaseClient.channel('inventory-live-v6').on('postgres_changes',{event:'*',schema:'public',table:'inventory_items'},()=>loadInventory()).on('postgres_changes',{event:'INSERT',schema:'public',table:'inventory_movements'},()=>loadMovements()).subscribe();focusScanner();});
})();
