const supabaseClient=window.supabase.createClient('https://dtjhuejmxrjkcxzvilgw.supabase.co','sb_publishable_kwXvFOCpknkDf9BKmcszrQ_Q7IBVg87');
const ADMIN_SESSION_KEY='designjam_admin_session',ADMIN_EMAILS=new Set(['900smk@naver.com','sm0727sm@hanmail.net','p1028p@naver.com']);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
async function guard(){const {data:{user}}=await supabaseClient.auth.getUser();if(!user)return location.replace('admin.html');const {data:p}=await supabaseClient.from('customers').select('is_admin').eq('id',user.id).maybeSingle();if(!ADMIN_EMAILS.has(String(user.email).toLowerCase())&&!p?.is_admin)return location.replace('admin.html');document.body.classList.add('auth-ready');return true;}
async function loadAccounts(){const box=document.getElementById('accountList');const {data,error}=await supabaseClient.from('payment_accounts').select('*').order('is_default',{ascending:false}).order('created_at');if(error){box.innerHTML=`<div class="product-card"><p>계좌 테이블 설치가 필요합니다: ${esc(error.message)}</p></div>`;return;}box.innerHTML=data?.length?data.map(a=>`<article class="product-card v3-account-card ${a.is_default?'default':''}"><div><h2>${a.is_default?'● ':''}${esc(a.label)}</h2><p>${esc(a.bank_name)} ${esc(a.account_number)}</p><p>예금주 ${esc(a.account_holder)}</p></div><div class="v3-card-actions">${!a.is_default?`<button class="cart-btn" onclick="setDefault('${a.id}')">기본계좌 지정</button>`:''}<button class="cart-btn gray-btn" onclick="removeAccount('${a.id}')">삭제</button></div></article>`).join(''):'<div class="product-card"><p>등록된 계좌가 없습니다.</p></div>';}
async function addAccount(){const payload={label:accountLabel.value.trim(),bank_name:accountBank.value.trim(),account_number:accountNumber.value.trim(),account_holder:accountHolder.value.trim()};if(Object.values(payload).some(v=>!v))return alert('계좌 정보를 모두 입력하세요.');const {count}=await supabaseClient.from('payment_accounts').select('*',{count:'exact',head:true});payload.is_default=(count||0)===0;const {error}=await supabaseClient.from('payment_accounts').insert(payload);if(error)return alert(error.message);['accountLabel','accountBank','accountNumber','accountHolder'].forEach(id=>document.getElementById(id).value='');loadAccounts();}
async function setDefault(id){await supabaseClient.from('payment_accounts').update({is_default:false}).neq('id',id);const {error}=await supabaseClient.from('payment_accounts').update({is_default:true}).eq('id',id);if(error)return alert(error.message);loadAccounts();}
async function removeAccount(id){if(!confirm('계좌를 삭제할까요?'))return;const {error}=await supabaseClient.from('payment_accounts').delete().eq('id',id);if(error)return alert(error.message);loadAccounts();}
window.setDefault=setDefault;window.removeAccount=removeAccount;document.addEventListener('DOMContentLoaded',async()=>{if(await guard()){document.getElementById('addAccountBtn').onclick=addAccount;loadAccounts();}});
