(()=>{'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const official=c=>/CJ|대한통운/i.test(c)?'https://www.cjlogistics.com/ko/tool/parcel/tracking':/한진/i.test(c)?'https://www.hanjin.com/kor/CMS/DeliveryMgr/WaybillResult.do':/롯데/i.test(c)?'https://www.lotteglogis.com/home/reservation/tracking/index':/로젠/i.test(c)?'https://www.ilogen.com/web/personal/trace':/경동/i.test(c)?'https://kdexp.com/service/delivery/etc/delivery.do':'https://www.cjlogistics.com/ko/tool/parcel/tracking';
const orderNumber=()=>new URLSearchParams(location.search).get('order')||'';
function managerDialogHtml(photos=[]){return `<dialog class="statement-shipment-dialog" data-statement-shipment-dialog><button type="button" class="statement-shipment-close" data-close-shipment-manager>닫기</button><div class="statement-shipment-manager" data-statement-shipment-manager><h3>운송장 등록·수정</h3><p>자동 연결이 되지 않았거나 잘못된 경우에만 사용하세요. 평소 송장 대량등록은 송장관리에서 처리합니다.</p><div class="statement-shipment-fields"><label>출고처<select data-shipment-warehouse><option value="">미구분</option><option>S</option><option>B</option><option>I</option></select></label><label>택배사<input data-shipment-carrier placeholder="예: 한진택배"></label><label>운송장번호<input data-shipment-tracking inputmode="numeric" placeholder="숫자·하이픈 입력"></label></div><div class="statement-shipment-actions"><button type="button" data-save-tracking>운송장 저장</button><label class="statement-shipment-file">송장사진 선택<input type="file" accept="image/jpeg,image/png,image/webp" multiple data-shipment-files></label><button type="button" data-upload-shipment>선택 사진 등록</button><a href="shipment-manager.html" target="_blank" rel="noopener">송장 대량등록 열기</a></div><small data-shipment-status></small>${photos.length?`<div class="statement-shipment-photos"><h3>등록된 송장사진</h3>${photos.map((x,i)=>`<figure><img src="${esc(x.url)}" alt="송장사진 ${i+1}"><figcaption>${esc(x.label)}</figcaption><div><a href="${esc(x.url)}" target="_blank" rel="noopener">원본 열기</a><button type="button" data-copy-shipment="${esc(x.url)}">사진 복사</button></div></figure>`).join('')}</div>`:''}</div></dialog>`}
function html(rows,customer=false){return`<section class="linked-shipment-box ${rows.length?'shipment-has-tracking':'shipment-no-tracking'}" data-linked-shipment-box><div class="linked-shipment-heading"><h3>택배/송장정보</h3>${customer?'':'<button type="button" class="statement-shipment-admin-button" data-open-shipment-manager>송장 수정</button>'}</div>${!rows.length?'<p class="shipment-empty">연결된 운송장이 없습니다.</p>':''}${rows.map(x=>`<div class="linked-shipment-row"><b>${esc(x.warehouse_code||'-')} | ${esc(x.carrier_name||'택배사 미확인')} | ${esc(x.tracking_number||'번호 없음')}</b>${customer&&x.tracking_number?`<a href="${official(x.carrier_name)}" target="_blank" rel="noopener">공식 배송조회</a>`:''}</div>`).join('')}</section>`}
async function copyImage(url){try{const blob=await fetch(url).then(r=>r.blob());await navigator.clipboard.write([new ClipboardItem({[blob.type]:blob})]);alert('송장사진을 복사했습니다. 카카오톡에 붙여넣으세요.')}catch(e){window.open(url,'_blank');alert('직접 복사가 제한되어 원본을 열었습니다. 열린 사진을 복사해주세요.')}}
async function fetchRows(n){const r=await supabaseClient.from('shipment_order_links').select('shipment_labels(id,warehouse_code,carrier_name,tracking_number,shipment_documents(id,storage_path,image_deleted_at))').eq('order_number',n);if(r.error)throw r.error;return(r.data||[]).map(x=>x.shipment_labels).filter(Boolean)}
async function photoRows(rows){const photos=[];for(const row of rows){const d=row.shipment_documents;if(!d?.storage_path||d.image_deleted_at)continue;const signed=await supabaseClient.storage.from('shipping-labels').createSignedUrl(d.storage_path,1800);if(signed.data?.signedUrl)photos.push({url:signed.data.signedUrl,label:`${row.warehouse_code||'-'} ${row.carrier_name||''} ${row.tracking_number||''}`})}return photos}
async function renderStatementShipments(){const n=orderNumber();if(!n)return;let rows=[];try{rows=await fetchRows(n)}catch(e){console.warn(e)}const photos=await photoRows(rows);let tries=0,t=setInterval(()=>{const area=document.getElementById('statementArea'),old=area?.querySelector('[data-linked-shipment-box]');if(old)old.remove();document.querySelector('[data-statement-shipment-dialog]')?.remove();const logistics=area?.querySelector('.statement-logistics-column'),parcel=logistics?.querySelector('.statement-parcel-box');if(logistics){if(parcel)parcel.insertAdjacentHTML('afterend',html(rows,false));else logistics.insertAdjacentHTML('beforeend',html(rows,false));document.body.insertAdjacentHTML('beforeend',managerDialogHtml(photos));clearInterval(t)}if(++tries>60)clearInterval(t)},100)}
function status(text,error=false){const el=document.querySelector('[data-shipment-status]');if(el){el.textContent=text;el.classList.toggle('error',error)}}
function fields(){const box=document.querySelector('[data-statement-shipment-manager]');return{warehouse:box?.querySelector('[data-shipment-warehouse]')?.value||null,carrier:box?.querySelector('[data-shipment-carrier]')?.value.trim()||'',tracking:box?.querySelector('[data-shipment-tracking]')?.value.trim()||'',files:[...(box?.querySelector('[data-shipment-files]')?.files||[])]}}
async function saveTracking(){const n=orderNumber(),f=fields();if(!f.tracking)return status('운송장번호를 입력해주세요.',true);status('운송장 저장 중…');const r=await supabaseClient.rpc('save_manual_order_shipment',{p_order_number:n,p_warehouse_code:f.warehouse,p_carrier_name:f.carrier,p_tracking_number:f.tracking});if(r.error)return status(`저장 실패: ${r.error.message}`,true);status('운송장 저장 완료');await renderStatementShipments()}
async function sha256(file){const buf=await file.arrayBuffer(),hash=await crypto.subtle.digest('SHA-256',buf);return[...new Uint8Array(hash)].map(v=>v.toString(16).padStart(2,'0')).join('')}
async function uploadOne(file,f,n){const hash=await sha256(file);let doc=(await supabaseClient.from('shipment_documents').select('id,storage_path').eq('image_sha256',hash).maybeSingle()).data;if(!doc){const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'')||'jpg',path=`statement/${new Date().toISOString().slice(0,10)}/${crypto.randomUUID()}.${ext}`;const up=await supabaseClient.storage.from('shipping-labels').upload(path,file,{contentType:file.type,upsert:false});if(up.error)throw up.error;const user=(await supabaseClient.auth.getUser()).data.user;const ins=await supabaseClient.from('shipment_documents').insert({storage_path:path,original_name:file.name,mime_type:file.type,file_size:file.size,image_sha256:hash,uploaded_by:user?.id||null}).select('id,storage_path').single();if(ins.error)throw ins.error;doc=ins.data}const normalized=f.tracking.replace(/[^0-9A-Za-z]/g,'').toUpperCase()||null;let label=null;if(normalized)label=(await supabaseClient.from('shipment_labels').select('id').eq('tracking_normalized',normalized).limit(1).maybeSingle()).data;if(!label){const ins=await supabaseClient.from('shipment_labels').insert({document_id:doc.id,warehouse_code:f.warehouse,carrier_name:f.carrier||null,tracking_number:f.tracking||null,tracking_normalized:normalized,match_status:'matched',match_score:100}).select('id').single();if(ins.error)throw ins.error;label=ins.data}const link=await supabaseClient.from('shipment_order_links').upsert({label_id:label.id,order_number:n,link_type:'manual',confidence:100},{onConflict:'label_id,order_number'});if(link.error)throw link.error}
async function uploadPhotos(){const n=orderNumber(),f=fields();if(!f.files.length)return status('먼저 송장사진을 선택해주세요.',true);status(`${f.files.length}장 등록 중…`);try{for(const file of f.files)await uploadOne(file,f,n);status(`${f.files.length}장 등록 완료`);await renderStatementShipments()}catch(e){console.error(e);status(`사진 등록 실패: ${e.message}`,true)}}
async function customer(){const r=await supabaseClient.rpc('get_my_order_shipments',{p_order_number:null});if(r.error||!r.data?.length)return;const main=document.querySelector('main');if(main)main.insertAdjacentHTML('afterbegin',html(r.data,true))}
document.addEventListener('click',e=>{const copy=e.target.closest('[data-copy-shipment]');if(copy)return copyImage(copy.dataset.copyShipment);if(e.target.closest('[data-open-shipment-manager]'))return document.querySelector('[data-statement-shipment-dialog]')?.showModal();if(e.target.closest('[data-close-shipment-manager]'))return document.querySelector('[data-statement-shipment-dialog]')?.close();if(e.target.closest('[data-save-tracking]'))return saveTracking();if(e.target.closest('[data-upload-shipment]'))return uploadPhotos()});
document.addEventListener('DOMContentLoaded',()=>{if(location.pathname.endsWith('statement.html'))renderStatementShipments();if(location.pathname.endsWith('order.html'))customer()})})();
