(()=>{'use strict';const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let queue=[],orders=[];
const carriers=[['CJ대한통운',/(CJ\s*대한통운|대한통운|CJ\s*LOGISTICS)/i],['한진택배',/(한진택배|한진|HANJIN)/i],['롯데택배',/(롯데택배|롯데글로벌로지스|LOTTE|현대택배)/i],['로젠택배',/(로젠택배|로젠|LOGEN)/i],['경동택배',/(경동택배|경동정기화물|경동화물|KYUNGDONG)/i],['우리택배',/(우리택배|우리로지스|우리택배주식회사|WOORI)/i]];
const normPhone=s=>String(s||'').replace(/\D/g,'').replace(/^82/,'0'),normAddr=s=>String(s||'').replace(/[\s,().-]/g,'').replace(/(특별시|광역시|특별자치도|특별자치시)/g,'').replace(/대한민국/g,''),normName=s=>String(s||'').replace(/[^0-9a-zA-Z가-힣]/g,'').toLowerCase(),normTrack=s=>String(s||'').replace(/\D/g,'');
const carrierTrackLengths={'CJ대한통운':[10,12],'한진택배':[10,12],'롯데택배':[12],'로젠택배':[11],'경동택배':[9,10,11,12,13],'우리택배':[12]};
const addressStopWords=new Set(['대한민국','서울','서울시','부산','부산시','대구','대구시','인천','인천시','광주','광주시','대전','대전시','울산','울산시','세종','세종시','경기','경기도','강원','강원도','충북','충남','전북','전남','경북','경남','제주','제주도','주소','수하인','받는분']);
function addressTokens(value){return[...new Set(String(value||'').match(/[가-힣A-Za-z]+|\d+(?:-\d+)?/g)||[])].map(x=>x.toLowerCase()).filter(x=>!addressStopWords.has(x)&&(/\d/.test(x)||x.length>=2))}
function plausibleTrack(value,carrier,strong=false){const track=normTrack(value);if(track.length<9||track.length>14||/^20\d{6}$/.test(track)||/^0?10\d{7,8}$/.test(track))return false;const lengths=carrierTrackLengths[carrier];return lengths?lengths.includes(track.length):strong}
function inferCarrier(tracks=[]){return tracks.some(x=>/^452\d{8}$/.test(normTrack(x)))?'로젠택배':''}
const parseOrderSelection=value=>String(value||'').split('|')[0].trim();
const statusLabel=value=>({review:'확인필요',matched:'연결완료',duplicate:'중복',ignored:'사용안함'}[value]||value||'확인필요');
async function guard(){
 const {data:{user}}=await supabaseClient.auth.getUser();
 if(!user){location.replace('admin.html');return false}
 const {data:p,error}=await supabaseClient.from('customers').select('is_admin,blocked,admin_role').eq('id',user.id).maybeSingle();
 if(error)throw error;
 if(!p?.is_admin||p.blocked||p.admin_role==='employee'){location.replace('admin-home.html');return false}
 document.body.classList.add('auth-ready');document.body.classList.remove('auth-pending');return true
}
function parseText(text=''){
 const lines=text.split(/\n+/).map(x=>x.replace(/\s+/g,' ').trim()).filter(Boolean),carrier=carriers.find(x=>x[1].test(text))?.[0]||'';
 const phoneMatches=text.match(/(?:01[016789]|0\d{1,2})[\s.-]?\d{3,4}[\s.-]?\d{4}/g)||[],phone=phoneMatches.find(x=>/^01/.test(normPhone(x)))||'',phones=new Set(phoneMatches.map(normPhone));
 const explicit=[];lines.forEach((line,index)=>{if(/운송장번호|송장번호|등기번호|배송번호/.test(line)){[line,...lines.slice(index+1,index+5)].forEach(value=>(value.match(/\d[\d\s-]{8,18}\d/g)||[]).forEach(x=>explicit.push(normTrack(x))))}});
 const bracketed=(text.match(/[[(]\s*\d{9,14}\s*[\])]/g)||[]).map(normTrack),topStyle=(text.match(/\b\d{3,5}[\s-]\d{3,5}[\s-]\d{3,5}\b/g)||[]).map(normTrack),raw=(text.match(/\b\d{9,14}\b/g)||[]).map(normTrack);
 let tracks=[...new Set([...explicit.filter(x=>plausibleTrack(x,carrier,true)),...bracketed.filter(x=>plausibleTrack(x,carrier,true)),...topStyle.filter(x=>plausibleTrack(x,carrier,true)),...raw.filter(x=>plausibleTrack(x,carrier,false)||/^452\d{8}$/.test(x))].filter(x=>!phones.has(x)))];
 let recipient=lines.find(x=>/수하인|받는분|수취인/.test(x))?.replace(/^.*?(수하인|받는분|수취인)\s*[:：]?/,'').trim()||'';
 if(!recipient){const masked=lines.find(x=>/[가-힣]{2,}[＊*]?\s*(?:\/|,)?\s*01[016789][-\s]?\d{2,4}[-\s]?[＊*xX]{2,}/);if(masked)recipient=masked.split(/\/|,|01[016789]/)[0].replace(/^(수하인|받는분|수취인)\s*[:：]?/,'').trim()}
 let address='',addressIndex=lines.findIndex(x=>/(서울|부산|대구|인천|광주|대전|울산|세종|경기|강원|충북|충남|전북|전남|경북|경남|제주).*(시|구|군|읍|면|동|로|길)/.test(x));
 if(addressIndex<0)addressIndex=lines.findIndex(x=>/(시|구|군|읍|면|동|리|로|길)\s*\d{1,4}(?:-\d+)?|\d{1,4}(?:-\d+)?\s*(번지|동|호|층)/.test(x));
 if(addressIndex>=0){address=lines[addressIndex];const next=lines[addressIndex+1]||'';if(next&&!/송하인|수하인|운송장|선불|착불|접수|주문번호|바코드/.test(next)&&/\d|동|호|층|문|마트|상가|시장|점$/.test(next))address+=' '+next}
 return{carrier:carrier||inferCarrier(tracks),phone,tracks:tracks.length?tracks:[''],recipient,address,raw:text}
}
async function trackingBarcodes(file){
 const results=[];
 try{
  if(typeof BarcodeDetector!=='undefined'){const supported=await BarcodeDetector.getSupportedFormats(),wanted=['code_128','code_39','codabar','itf','ean_13'].filter(x=>supported.includes(x));if(wanted.length){const detector=new BarcodeDetector({formats:wanted}),bitmap=await createImageBitmap(file),found=await detector.detect(bitmap);bitmap.close?.();results.push(...found.map(x=>normTrack(x.rawValue)))}}
 }catch(error){console.warn('기본 바코드 인식 실패',error)}
 if(!results.length){try{if(!window.ZXing)await new Promise((resolve,reject)=>{const old=document.querySelector('script[data-zxing]');if(old){old.addEventListener('load',resolve,{once:true});old.addEventListener('error',reject,{once:true});return}const script=document.createElement('script');script.dataset.zxing='1';script.src='https://cdn.jsdelivr.net/npm/@zxing/library@0.21.3/umd/index.min.js';script.onload=resolve;script.onerror=reject;document.head.appendChild(script)});const url=URL.createObjectURL(file),img=new Image;await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=reject;img.src=url});const reader=new ZXing.BrowserMultiFormatReader(),found=await reader.decodeFromImageElement(img);results.push(normTrack(found?.getText?.()||found?.text||''));reader.reset?.();URL.revokeObjectURL(url)}catch(error){console.warn('ZXing 보조 바코드 인식 실패',error)}}
 return[...new Set(results.filter(x=>x.length>=9&&x.length<=16))]
}
async function enhancedOcrImage(file){
 const bitmap=await createImageBitmap(file),max=2400,scale=Math.min(2,max/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext('2d');ctx.filter='grayscale(1) contrast(1.45)';ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close?.();return canvas;
}
async function numericOcr(file,logger){if(!window.Tesseract)return'';const source=await enhancedOcrImage(file),worker=await Tesseract.createWorker('eng',1,{logger});try{await worker.setParameters({tessedit_char_whitelist:'0123456789-[]()',tessedit_pageseg_mode:'11',preserve_interword_spaces:'1'});const out=await worker.recognize(source);return out.data.text||''}finally{await worker.terminate()}}
async function sha(file){const b=await file.arrayBuffer(),h=await crypto.subtle.digest('SHA-256',b);return[...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function addFiles(files){[...files].filter(f=>f.type.startsWith('image/')).forEach(file=>queue.push({file,url:URL.createObjectURL(file),status:'대기',parsed:{carrier:'',phone:'',tracks:[''],recipient:'',address:'',raw:''}}));renderQueue()}
function orderCaption(o){return`${o.order_number} · ${o.customer_name||'-'} · ${o.delivery_name||'-'} · ${String(o.created_at||'').slice(0,10)}`}
function candidateButtons(rows=[]){return rows.length?`<div class="shipment-candidates"><strong>연결 가능성이 높은 주문</strong>${rows.map((o,index)=>`<button type="button" data-act="choose-order" data-order="${esc(o.order_number)}"><span>${index+1}. ${esc(o.delivery_name||o.customer_name||'-')}</span><small>${esc(o.customer_name||'-')} · ${esc(String(o.created_at||'').slice(0,10))} · ${o.score}점 (${esc(o.reasons.join('·')||'최근 주문')})</small></button>`).join('')}<em>자동 확정하지 않은 후보입니다. 원본 송장과 비교한 뒤 선택하세요.</em></div>`:''}
function renderQueue(){$('shipmentQueue').innerHTML=queue.length?queue.map((q,i)=>`<article class="shipment-card" data-i="${i}"><img src="${q.url}" alt="송장 미리보기"><p><span class="shipment-badge">${esc(q.status)}</span></p><div class="shipment-fields"><label>택배사<input data-f="carrier" value="${esc(q.parsed.carrier)}" placeholder="예: 한진택배"></label><label>운송장번호(여러 개는 쉼표)<input data-f="track" value="${esc(q.parsed.tracks.join(", "))}" placeholder="1234..., 5678..."></label><label>수취인<input data-f="recipient" value="${esc(q.parsed.recipient)}"></label><label>전화번호<input data-f="phone" value="${esc(q.parsed.phone)}"></label><label class="wide">주소<input data-f="address" value="${esc(q.parsed.address)}"></label><label>출고처<select data-f="warehouse"><option value="">자동/미정</option><option>S</option><option>B</option><option>I</option></select></label><label>주문 연결<input data-f="order" list="orderList" value="${esc(q.manualOrder||'')}" placeholder="주문번호 검색"></label></div>${candidateButtons(q.candidates)}<details><summary>OCR 원문</summary><textarea data-f="raw">${esc(q.parsed.raw)}</textarea></details><div class="shipment-card-actions"><button data-act="analyze">이 사진 분석</button><button data-act="remove">제외</button></div></article>`).join(''):'<p class="empty">사진을 추가하세요.</p>';}
async function analyzeOne(i){const q=queue[i];q.status='바코드 확인 중';renderQueue();try{const barcodeTracks=await trackingBarcodes(q.file);let text='',numbers='';if(window.Tesseract){const source=await enhancedOcrImage(q.file),out=await Tesseract.recognize(source,'kor+eng',{logger:m=>{if(m.status==='recognizing text'){q.status=`글자 OCR ${Math.round((m.progress||0)*100)}%${barcodeTracks.length?` · 바코드 ${barcodeTracks.length}개`:''}`;renderQueue()}}});text=out.data.text||'';numbers=await numericOcr(q.file,m=>{if(m.status==='recognizing text'){q.status=`송장번호 전용 OCR ${Math.round((m.progress||0)*100)}%`;renderQueue()}})}q.parsed=parseText(`${text}\n${numbers}`);q.parsed.tracks=[...new Set([...barcodeTracks,...q.parsed.tracks.filter(Boolean)])];q.parsed.carrier=q.parsed.carrier||inferCarrier(q.parsed.tracks);if(!q.parsed.tracks.length)q.parsed.tracks=[''];q.candidates=rankCandidates(q).slice(0,3);const auto=candidate(q);q.status=auto?`주문 자동매칭 ${auto.score}점`:barcodeTracks.length?`바코드 ${barcodeTracks.length}개 · 주문확인 필요`:q.parsed.tracks.some(Boolean)?`송장번호 ${q.parsed.tracks.filter(Boolean).length}개 · 주문확인 필요`:'수동확인';renderQueue()}catch(e){q.status='수동입력 필요';renderQueue();console.warn(e)}}
function syncCard(card,q){const get=f=>card.querySelector(`[data-f="${f}"]`)?.value?.trim()||'';q.parsed={...q.parsed,carrier:get('carrier'),tracks:get('track').split(/[\s,]+/).filter(Boolean),recipient:get('recipient'),phone:get('phone'),address:get('address'),raw:get('raw')};q.warehouse=get('warehouse').toUpperCase();q.manualOrder=parseOrderSelection(get('order'))}
function scoreOrder(q,o){let score=0,reasons=[],strong=0,addressHit=false;const p=normPhone(q.parsed.phone),op=normPhone(o.delivery_phone||o.customer_phone);if(p&&op&&p===op){score+=60;strong++;reasons.push('전화 일치')}else if(p.length>=8&&op.length>=8&&p.slice(-8)===op.slice(-8)){score+=52;strong++;reasons.push('전화 뒷자리')}const a=normAddr(q.parsed.address),oa=normAddr(o.delivery_address),raw=normAddr(q.parsed.raw);if(a&&oa){if(a===oa){score+=70;strong++;addressHit=true;reasons.push('주소 일치')}else if((a.length>=10&&oa.includes(a))||(oa.length>=10&&a.includes(oa))){score+=60;strong++;addressHit=true;reasons.push('주소 포함')}else if(a.length>=12&&oa.length>=12&&a.slice(-12)===oa.slice(-12)){score+=50;strong++;addressHit=true;reasons.push('주소 끝부분')}}if(!addressHit&&raw&&o.delivery_address){const tokens=addressTokens(o.delivery_address),matched=tokens.filter(token=>raw.includes(normAddr(token))),hasNumber=matched.some(x=>/\d/.test(x)),ratio=tokens.length?matched.length/tokens.length:0;if(matched.length>=3&&ratio>=.35&&hasNumber){score+=65;strong++;addressHit=true;reasons.push(`주소 조각 ${matched.length}개 일치`)}else if(matched.length>=2&&ratio>=.3&&hasNumber){score+=55;strong++;addressHit=true;reasons.push(`주소 조각 ${matched.length}개 일치`)}}const n=normName(q.parsed.recipient),names=[o.delivery_name,o.customer_name,o.customer_owner_name].map(normName).filter(Boolean);if(n&&names.some(on=>n===on)){score+=30;reasons.push('수취인 일치')}else if(n.length>=2&&names.some(on=>on.includes(n)||n.includes(on))){score+=20;reasons.push('수취인 일부일치')}else if(raw&&names.some(on=>on.length>=2&&raw.includes(on))){score+=25;reasons.push('수취인 원문일치')}if(q.warehouse&&q.warehouse===String(o.warehouse_code||'').toUpperCase()){score+=5;reasons.push('출고처')}return{score,reasons,strong}}
function rankCandidates(q){return orders.map(o=>({...o,...scoreOrder(q,o)})).filter(o=>o.score>=16).sort((a,b)=>b.score-a.score||new Date(b.created_at)-new Date(a.created_at))}
function candidate(q){if(q.manualOrder)return{order_number:q.manualOrder,score:100,reasons:['관리자 선택']};const ranked=rankCandidates(q),a=ranked[0],b=ranked[1];if(!a)return null;const addressAndName=a.strong>=1&&a.reasons.some(x=>x.startsWith('주소'))&&a.reasons.some(x=>x.startsWith('수취인')),supported=addressAndName||a.strong>=2;return supported&&a.score>=80&&a.score-(b?.score||0)>=15?a:null}
async function saveOne(card,q){syncCard(card,q);q.status='저장 중';renderQueue();const hash=await sha(q.file),dup=await supabaseClient.from('shipment_documents').select('id,original_name').eq('image_sha256',hash).maybeSingle();if(dup.data){q.status='이미 등록된 사진';return}const uid=(await supabaseClient.auth.getUser()).data.user?.id,path=`${new Date().toISOString().slice(0,10)}/${crypto.randomUUID()}-${q.file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const up=await supabaseClient.storage.from('shipping-labels').upload(path,q.file,{contentType:q.file.type,upsert:false});if(up.error)throw up.error;const d=await supabaseClient.from('shipment_documents').insert({storage_path:path,original_name:q.file.name,mime_type:q.file.type,file_size:q.file.size,image_sha256:hash,ocr_text:q.parsed.raw,ocr_engine:'tesseract-local',uploaded_by:uid,delete_after:new Date(Date.now()+31*86400000).toISOString()}).select().single();if(d.error)throw d.error;const tracks=q.parsed.tracks.filter(Boolean).length?q.parsed.tracks:[''];for(const track of tracks){const c=candidate(q),payload={document_id:d.data.id,warehouse_code:q.warehouse||null,carrier_name:q.parsed.carrier||null,tracking_number:track||null,tracking_normalized:normTrack(track)||null,recipient_name:q.parsed.recipient||null,recipient_phone:q.parsed.phone||null,recipient_address:q.parsed.address||null,match_status:c?'matched':'review',match_score:c?.score||0,match_reasons:c?.reasons||[]};const l=await supabaseClient.from('shipment_labels').insert(payload).select().single();if(l.error&&/duplicate|unique/i.test(l.error.message)){q.status='이미 등록된 송장';continue}if(l.error)throw l.error;if(c){const link=await supabaseClient.from('shipment_order_links').insert({label_id:l.data.id,order_number:c.order_number,link_type:c.score===100?'manual':'auto',confidence:c.score,linked_by:uid});if(link.error)throw link.error}}q.status='저장완료'}
async function loadOrders(){const since=new Date(Date.now()-30*86400000).toISOString();const r=await supabaseClient.from('orders').select('*').gte('created_at',since).order('created_at',{ascending:false}).limit(6000);const map=new Map;(r.data||[]).forEach(o=>{if(!map.has(o.order_number))map.set(o.order_number,o)});orders=[...map.values()];let dl=document.getElementById('orderList');if(!dl){dl=document.createElement('datalist');dl.id='orderList';document.body.appendChild(dl)}dl.innerHTML=orders.map(o=>`<option value="${esc(orderCaption(o))}"></option>`).join('')}
async function savedPhotoUrl(row){const path=row.shipment_documents?.storage_path;if(!path||row.shipment_documents?.image_deleted_at)return'';const result=await supabaseClient.storage.from('shipping-labels').createSignedUrl(path,1200);return result.data?.signedUrl||''}
async function loadSaved(){
 let q=supabaseClient.from('shipment_labels').select('id,warehouse_code,carrier_name,tracking_number,recipient_name,recipient_phone,recipient_address,match_status,match_score,created_at,shipment_documents(storage_path,image_deleted_at),shipment_order_links(order_number)').order('created_at',{ascending:false}).limit(100);if($('shipmentState').value)q=q.eq('match_status',$('shipmentState').value);const r=await q;
 if(r.error){$('shipmentSaved').innerHTML=`<p class="empty">최근 송장 조회 실패: ${esc(r.error.message)}</p>`;return}
 const list=[];for(const x of r.data||[]){const photo=await savedPhotoUrl(x),linked=x.shipment_order_links?.[0]?.order_number||'',reviewCandidates=rankCandidates({parsed:{phone:x.recipient_phone,address:x.recipient_address,recipient:x.recipient_name},warehouse:x.warehouse_code}).slice(0,3);list.push(`<article class="saved-row ${x.match_status==='review'?'needs-review':''}" data-label-id="${esc(x.id)}" data-photo-url="${esc(photo)}"><div class="saved-row-head"><div><b>${esc(x.carrier_name||'택배사 미확인')} ${esc(x.tracking_number||'번호 수동확인')}</b><p>${esc(x.warehouse_code||'-')} · ${esc(x.recipient_name||'-')} · 주문 ${esc(linked||'미연결')} · 점수 ${x.match_score||0}</p></div><span class="shipment-badge">${esc(statusLabel(x.match_status))}</span></div><div class="saved-row-actions">${photo?'<button type="button" data-act="reanalyze-label">원본 다시 자동분석</button>':''}<button type="button" data-act="toggle-review">${x.match_status==='review'?'수동확인·연결':'정보 확인·수정'}</button>${photo?`<a href="${esc(photo)}" target="_blank" rel="noopener">원본사진 크게보기</a>`:''}</div><small class="reanalyze-status" data-reanalyze-status></small><section class="saved-review-editor" hidden>${photo?`<img src="${esc(photo)}" alt="송장 원본사진">`:'<p class="empty">보관된 원본사진이 없습니다.</p>'}${candidateButtons(reviewCandidates)}<div class="saved-review-fields"><label>출고처<select data-review="warehouse"><option value="">미구분</option><option ${x.warehouse_code==='S'?'selected':''}>S</option><option ${x.warehouse_code==='B'?'selected':''}>B</option><option ${x.warehouse_code==='I'?'selected':''}>I</option></select></label><label>택배사<input data-review="carrier" value="${esc(x.carrier_name||'')}" placeholder="예: 한진택배"></label><label>운송장번호<input data-review="tracking" value="${esc(x.tracking_number||'')}" placeholder="숫자·하이픈"></label><label class="wide">주문 검색·선택<input data-review="order" list="orderList" value="${esc(linked)}" placeholder="주문번호·거래처명·실제 납품처명 입력"></label></div><p class="saved-review-help">후보 주문을 누르거나 검색목록에서 선택하세요. 원본 송장의 수취인·전화·주소가 실제 납품처와 맞는지 확인하면 됩니다.</p><div class="saved-review-buttons"><button type="button" data-act="save-review">확인완료·주문연결</button><button type="button" class="ignore" data-act="ignore-label">사용 안 함</button><small data-review-status></small></div></section></article>`)}
 $('shipmentSaved').innerHTML=list.join('')||'<p class="empty">저장된 송장이 없습니다.</p>';
}
async function saveManualReview(row){
 const labelId=row.dataset.labelId,get=name=>row.querySelector(`[data-review="${name}"]`)?.value?.trim()||'',orderNumber=parseOrderSelection(get('order')),order=orders.find(o=>String(o.order_number)===orderNumber),status=row.querySelector('[data-review-status]');
 if(!order){status.textContent='주문 검색목록에서 연결할 주문을 선택해주세요.';status.classList.add('error');return}
 const carrier=get('carrier'),tracking=get('tracking'),normalized=normTrack(tracking);status.textContent='저장 중…';status.classList.remove('error');
 const update=await supabaseClient.from('shipment_labels').update({warehouse_code:get('warehouse')||null,carrier_name:carrier||null,tracking_number:tracking||null,tracking_normalized:normalized||null,match_status:'matched',match_score:100,match_reasons:['수동확인'],updated_at:new Date().toISOString()}).eq('id',labelId);
 if(update.error){status.textContent=/duplicate|unique/i.test(update.error.message)?'이미 등록된 송장번호입니다. 기존 송장 연결을 확인해주세요.':'정보 저장 실패: '+update.error.message;status.classList.add('error');return}
 const remove=await supabaseClient.from('shipment_order_links').delete().eq('label_id',labelId);if(remove.error){status.textContent='기존 연결 정리 실패: '+remove.error.message;status.classList.add('error');return}
 const uid=(await supabaseClient.auth.getUser()).data.user?.id,link=await supabaseClient.from('shipment_order_links').insert({label_id:labelId,order_number:orderNumber,link_type:'manual',confidence:100,linked_by:uid});
 if(link.error){status.textContent='주문 연결 실패: '+link.error.message;status.classList.add('error');return}
 status.textContent='수동확인·주문연결 완료';await loadSaved();
}
async function reanalyzeSavedLabel(row,button){
 const url=row.dataset.photoUrl,status=row.querySelector('[data-reanalyze-status]'),labelId=row.dataset.labelId;if(!url)return;
 button.disabled=true;status.textContent='원본사진 불러오는 중…';status.classList.remove('error');
 try{
  const response=await fetch(url);if(!response.ok)throw new Error('원본사진을 불러오지 못했습니다.');const blob=await response.blob(),file=new File([blob],'saved-shipment.'+(blob.type.split('/')[1]||'jpg'),{type:blob.type});
  status.textContent='바코드 확인 중…';const barcodeTracks=await trackingBarcodes(file);let text='';
  if(window.Tesseract){const source=await enhancedOcrImage(file),out=await Tesseract.recognize(source,'kor+eng',{logger:m=>{if(m.status==='recognizing text')status.textContent=`글자 OCR 다시 분석 ${Math.round((m.progress||0)*100)}%`}});text=out.data.text||'';text+='\n'+await numericOcr(file,m=>{if(m.status==='recognizing text')status.textContent=`송장번호 전용 OCR ${Math.round((m.progress||0)*100)}%`})}
  const parsed=parseText(text);parsed.tracks=[...new Set([...barcodeTracks,...parsed.tracks.filter(Boolean)])];parsed.carrier=parsed.carrier||inferCarrier(parsed.tracks);const warehouse=row.querySelector('[data-review="warehouse"]')?.value||'',q={parsed,warehouse},matched=candidate(q),tracking=parsed.tracks[0]||'',normalized=normTrack(tracking);
  if(normalized){const duplicate=await supabaseClient.from('shipment_labels').select('id,carrier_name,tracking_number').eq('tracking_normalized',normalized).neq('id',labelId).limit(1).maybeSingle();if(duplicate.data){status.textContent=`이미 등록된 송장입니다: ${duplicate.data.carrier_name||'택배사 미확인'} ${duplicate.data.tracking_number||normalized}`;status.classList.add('error');return}}
  const update=await supabaseClient.from('shipment_labels').update({carrier_name:parsed.carrier||null,tracking_number:tracking||null,tracking_normalized:normTrack(tracking)||null,recipient_name:parsed.recipient||null,recipient_phone:parsed.phone||null,recipient_address:parsed.address||null,match_status:matched?'matched':'review',match_score:matched?.score||0,match_reasons:matched?.reasons||[],updated_at:new Date().toISOString()}).eq('id',labelId);if(update.error)throw update.error;
  const clear=await supabaseClient.from('shipment_order_links').delete().eq('label_id',labelId);if(clear.error)throw clear.error;
  if(matched){const uid=(await supabaseClient.auth.getUser()).data.user?.id,link=await supabaseClient.from('shipment_order_links').insert({label_id:labelId,order_number:matched.order_number,link_type:'auto',confidence:matched.score,linked_by:uid});if(link.error)throw link.error}
  status.textContent=matched?`재분석 완료 · ${matched.order_number} 자동연결`:'재분석 완료 · 후보 확인 필요';await loadSaved();
 }catch(error){status.textContent='다시 분석 실패: '+(error?.message||error);status.classList.add('error')}finally{button.disabled=false}
}
async function ignoreLabel(row){if(!confirm('이 송장 판독결과를 사용하지 않도록 제외할까요?\n원본사진과 기록은 보관되며 주문에는 연결되지 않습니다.'))return;const id=row.dataset.labelId;await supabaseClient.from('shipment_order_links').delete().eq('label_id',id);const r=await supabaseClient.from('shipment_labels').update({match_status:'ignored',match_score:0,match_reasons:['관리자 제외'],updated_at:new Date().toISOString()}).eq('id',id);if(r.error)return alert('제외 처리 실패: '+r.error.message);await loadSaved()}
async function init(){try{if(!await guard())return;await loadOrders();await loadSaved();$('shipmentDrop').onclick=()=>$('shipmentFiles').click();$('pickShipmentFiles').onclick=()=>$('shipmentFiles').click();$('shipmentFiles').onchange=e=>addFiles(e.target.files);['dragenter','dragover'].forEach(t=>$('shipmentDrop').addEventListener(t,e=>{e.preventDefault();$('shipmentDrop').classList.add('drag')}));['dragleave','drop'].forEach(t=>$('shipmentDrop').addEventListener(t,e=>{e.preventDefault();$('shipmentDrop').classList.remove('drag');if(t==='drop')addFiles(e.dataTransfer.files)}));document.addEventListener('paste',e=>addFiles([...e.clipboardData.items].map(x=>x.getAsFile()).filter(Boolean)));$('shipmentQueue').onclick=e=>{const card=e.target.closest('.shipment-card'),i=Number(card?.dataset.i);if(!card)return;if(e.target.closest('[data-act="choose-order"]')){queue[i].manualOrder=e.target.closest('[data-order]').dataset.order;renderQueue()}if(e.target.dataset.act==='remove'){queue.splice(i,1);renderQueue()}if(e.target.dataset.act==='analyze')analyzeOne(i)};$('runShipmentAnalysis').onclick=async()=>{for(let i=0;i<queue.length;i++){if(!queue[i].parsed.raw)await analyzeOne(i);const card=$('shipmentQueue').querySelector(`[data-i="${i}"]`);try{await saveOne(card,queue[i])}catch(e){queue[i].status='오류: '+e.message}renderQueue()}await loadSaved()};$('shipmentSaved').onclick=e=>{const row=e.target.closest('.saved-row');if(!row)return;if(e.target.closest('[data-act="reanalyze-label"]'))reanalyzeSavedLabel(row,e.target.closest('[data-act="reanalyze-label"]'));if(e.target.closest('[data-act="choose-order"]')){const order=e.target.closest('[data-order]').dataset.order,input=row.querySelector('[data-review="order"]'),found=orders.find(o=>String(o.order_number)===order);input.value=found?orderCaption(found):order}if(e.target.closest('[data-act="toggle-review"]')){const editor=row.querySelector('.saved-review-editor');editor.hidden=!editor.hidden}if(e.target.closest('[data-act="save-review"]'))saveManualReview(row);if(e.target.closest('[data-act="ignore-label"]'))ignoreLabel(row)};$('refreshShipments').onclick=loadSaved;$('shipmentState').onchange=loadSaved}catch(error){console.error(error);document.body.classList.add('auth-ready');document.body.classList.remove('auth-pending');const box=$('shipmentSaved');if(box)box.innerHTML=`<p class="empty">송장 화면을 불러오지 못했습니다: ${esc(error?.message||error)}</p>`}}
document.addEventListener('DOMContentLoaded',init)})();
