(()=>{'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const official=c=>/CJ|대한통운/i.test(c)?'https://www.cjlogistics.com/ko/tool/parcel/tracking':/한진/i.test(c)?'https://www.hanjin.com/kor/CMS/DeliveryMgr/WaybillResult.do':/롯데/i.test(c)?'https://www.lotteglogis.com/home/reservation/tracking/index':/로젠/i.test(c)?'https://www.ilogen.com/web/personal/trace':/경동/i.test(c)?'https://kdexp.com/service/delivery/etc/delivery.do':'https://www.cjlogistics.com/ko/tool/parcel/tracking';
function html(rows,customer=false,photos=[]){return`<section class="linked-shipment-box"><h2>택배/송장정보</h2>${rows.map(x=>`<div class="linked-shipment-row"><b>${esc(x.warehouse_code||'-')} | ${esc(x.carrier_name||'택배사 미확인')} | ${esc(x.tracking_number||'번호 없음')}</b>${customer&&x.tracking_number?`<a href="${official(x.carrier_name)}" target="_blank" rel="noopener">공식 배송조회</a>`:''}</div>`).join('')}${photos.length?`<div class="statement-shipment-photos"><h3>송장사진 · 긴 명세서와 함께 확인</h3>${photos.map((x,i)=>`<figure><img src="${esc(x.url)}" alt="송장사진 ${i+1}"><figcaption>${esc(x.label)}</figcaption><div><a href="${esc(x.url)}" target="_blank" rel="noopener">원본 열기</a><button type="button" data-copy-shipment="${esc(x.url)}">사진 복사</button></div></figure>`).join('')}</div>`:''}</section>`}
async function copyImage(url){try{const blob=await fetch(url).then(r=>r.blob());await navigator.clipboard.write([new ClipboardItem({[blob.type]:blob})]);alert('송장사진을 복사했습니다. 카카오톡에 붙여넣으세요.')}catch(e){window.open(url,'_blank');alert('직접 복사가 제한되어 원본을 열었습니다. 열린 사진을 복사해주세요.')}}
async function statement(){const n=new URLSearchParams(location.search).get('order');if(!n)return;const r=await supabaseClient.from('shipment_order_links').select('shipment_labels(warehouse_code,carrier_name,tracking_number,shipment_documents(storage_path,image_deleted_at))').eq('order_number',n);const rows=(r.data||[]).map(x=>x.shipment_labels).filter(Boolean);if(!rows.length)return;const photos=[];for(const row of rows){const d=row.shipment_documents;if(!d?.storage_path||d.image_deleted_at)continue;const signed=await supabaseClient.storage.from('shipping-labels').createSignedUrl(d.storage_path,1800);if(signed.data?.signedUrl)photos.push({url:signed.data.signedUrl,label:`${row.warehouse_code||'-'} ${row.carrier_name||''} ${row.tracking_number||''}`})}let tries=0,t=setInterval(()=>{const area=document.getElementById('statementArea');if(area&&area.querySelector('.statement-footer')){area.querySelector('.statement-footer').insertAdjacentHTML('beforebegin',html(rows,false,photos));clearInterval(t)}if(++tries>50)clearInterval(t)},100)}
async function customer(){const r=await supabaseClient.rpc('get_my_order_shipments',{p_order_number:null});if(r.error||!r.data?.length)return;const main=document.querySelector('main');if(main)main.insertAdjacentHTML('afterbegin',html(r.data,true))}
document.addEventListener('click',e=>{const b=e.target.closest('[data-copy-shipment]');if(b)copyImage(b.dataset.copyShipment)});
document.addEventListener('DOMContentLoaded',()=>{if(location.pathname.endsWith('statement.html'))statement();if(location.pathname.endsWith('order.html'))customer()})})();
