-- DESIGN SOCKS V6.0.0 실시간 재고/스캔 시스템
-- Supabase SQL Editor에서 전체 실행

create table if not exists public.inventory_items (
  item_number text primary key,
  barcode text unique not null,
  product_group_id bigint null,
  product_name text not null default '',
  brand text not null default '',
  category_name text not null default '',
  location_code text not null default '',
  quantity integer not null default 0 check (quantity >= 0),
  safety_stock integer not null default 10 check (safety_stock >= 0),
  updated_at timestamptz not null default now(),
  updated_by uuid null references auth.users(id)
);

create table if not exists public.inventory_movements (
  id bigint generated by default as identity primary key,
  item_number text not null references public.inventory_items(item_number) on update cascade,
  movement_type text not null check (movement_type in ('IN','OUT','ADJUST')),
  quantity integer not null check (quantity > 0),
  quantity_before integer not null,
  quantity_after integer not null,
  source text not null default 'SCANNER',
  order_number text null,
  note text not null default '',
  device_name text not null default '',
  created_at timestamptz not null default now(),
  created_by uuid null references auth.users(id)
);

create index if not exists inventory_movements_item_created_idx
  on public.inventory_movements(item_number, created_at desc);
create index if not exists inventory_movements_created_idx
  on public.inventory_movements(created_at desc);

alter table public.inventory_items enable row level security;
alter table public.inventory_movements enable row level security;

create or replace function public.is_inventory_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.customers c
    where c.id = auth.uid()
      and c.is_admin = true
      and coalesce(c.blocked, false) = false
  );
$$;

drop policy if exists inventory_items_admin_select on public.inventory_items;
drop policy if exists inventory_items_admin_write on public.inventory_items;
drop policy if exists inventory_movements_admin_select on public.inventory_movements;
drop policy if exists inventory_movements_admin_insert on public.inventory_movements;

create policy inventory_items_admin_select on public.inventory_items
for select to authenticated using (public.is_inventory_admin());
create policy inventory_items_admin_write on public.inventory_items
for all to authenticated using (public.is_inventory_admin()) with check (public.is_inventory_admin());
create policy inventory_movements_admin_select on public.inventory_movements
for select to authenticated using (public.is_inventory_admin());
create policy inventory_movements_admin_insert on public.inventory_movements
for insert to authenticated with check (public.is_inventory_admin());

create or replace function public.apply_inventory_scan(
  p_item_number text,
  p_mode text,
  p_increment integer default 1,
  p_device_name text default '',
  p_order_number text default null
)
returns public.inventory_items
language plpgsql
security definer
set search_path = public
as $$
declare
  v_item public.inventory_items;
  v_before integer;
  v_after integer;
  v_mode text := upper(trim(p_mode));
begin
  if not public.is_inventory_admin() then
    raise exception '관리자 권한이 필요합니다.';
  end if;
  if p_increment is null or p_increment < 1 or p_increment > 1000 then
    raise exception '증감 수량은 1~1000 사이여야 합니다.';
  end if;
  if v_mode not in ('IN','OUT') then
    raise exception '입고(IN) 또는 출고(OUT) 모드만 가능합니다.';
  end if;

  select * into v_item
  from public.inventory_items
  where item_number = trim(p_item_number) or barcode = trim(p_item_number)
  for update;

  if not found then
    raise exception '미등록 품번: %', p_item_number;
  end if;

  v_before := v_item.quantity;
  v_after := case when v_mode = 'IN' then v_before + p_increment else v_before - p_increment end;
  if v_after < 0 then
    raise exception '재고 부족: 현재 %, 요청 %', v_before, p_increment;
  end if;

  update public.inventory_items
     set quantity = v_after, updated_at = now(), updated_by = auth.uid()
   where item_number = v_item.item_number
   returning * into v_item;

  insert into public.inventory_movements(
    item_number,movement_type,quantity,quantity_before,quantity_after,
    source,order_number,device_name,created_by
  ) values (
    v_item.item_number,v_mode,p_increment,v_before,v_after,
    'SCANNER',nullif(trim(p_order_number),''),coalesce(p_device_name,''),auth.uid()
  );

  return v_item;
end;
$$;

grant execute on function public.apply_inventory_scan(text,text,integer,text,text) to authenticated;
grant execute on function public.is_inventory_admin() to authenticated;

-- Realtime 활성화 (이미 추가되어 있으면 오류가 날 수 있으므로 그 경우 무시)
do $$ begin
  alter publication supabase_realtime add table public.inventory_items;
exception when duplicate_object then null;
end $$;
