-- DESIGN SOCKS V6.1.2 모바일/부분품절/접속현황/수동출고
alter table public.orders add column if not exists soldout_qty integer not null default 0 check (soldout_qty >= 0);
alter table public.customers add column if not exists last_login_at timestamptz null;
alter table public.customers add column if not exists last_seen_at timestamptz null;
alter table public.customers add column if not exists login_count integer not null default 0;
create table if not exists public.customer_login_events(id bigint generated always as identity primary key,customer_id uuid not null references public.customers(id) on delete cascade,logged_in_at timestamptz not null default now());
create index if not exists customer_login_events_logged_idx on public.customer_login_events(logged_in_at desc);
alter table public.customer_login_events enable row level security;
drop policy if exists customer_login_events_insert_self on public.customer_login_events;create policy customer_login_events_insert_self on public.customer_login_events for insert to authenticated with check(customer_id=auth.uid());
drop policy if exists customer_login_events_admin_select on public.customer_login_events;create policy customer_login_events_admin_select on public.customer_login_events for select to authenticated using(public.is_inventory_admin());
create or replace function public.record_customer_login() returns void language plpgsql security definer set search_path=public as $$ begin update customers set last_login_at=now(),last_seen_at=now(),login_count=coalesce(login_count,0)+1 where id=auth.uid() and coalesce(is_admin,false)=false;insert into customer_login_events(customer_id) values(auth.uid());end;$$;grant execute on function public.record_customer_login() to authenticated;
create or replace function public.touch_customer_presence() returns void language plpgsql security definer set search_path=public as $$ begin update customers set last_seen_at=now() where id=auth.uid() and coalesce(is_admin,false)=false;end;$$;grant execute on function public.touch_customer_presence() to authenticated;
create or replace function public.complete_order_picking(p_order_number text,p_device_name text default '피킹검증') returns jsonb language plpgsql security definer set search_path=public as $$
declare v_customer_id text;v_customer_name text;v_bad integer;v_row record;v_item public.inventory_items;v_before integer;v_after integer;begin
 if not public.is_inventory_admin() then raise exception '관리자 권한이 필요합니다.';end if;
 select count(*) into v_bad from public.orders where order_number=p_order_number and coalesce(picked_qty,0)+coalesce(soldout_qty,0)<>coalesce(qty,0);if v_bad>0 then raise exception '피킹+품절 수량 불일치 품목이 %개 있습니다.',v_bad;end if;
 select customer_id::text,coalesce(customer_name,'거래처 미입력') into v_customer_id,v_customer_name from public.orders where order_number=p_order_number limit 1;if not found then raise exception '주문을 찾을 수 없습니다.';end if;
 for v_row in select item_number,sum(coalesce(picked_qty,0))::integer as qty from public.orders where order_number=p_order_number group by item_number loop if v_row.qty<=0 then continue;end if;select * into v_item from inventory_items where item_number=trim(v_row.item_number) or barcode=trim(v_row.item_number) for update;if not found then raise exception '재고 미등록 품번: %',v_row.item_number;end if;v_before:=v_item.quantity;v_after:=v_before-v_row.qty;if v_after<0 then raise exception '재고 부족: % 현재 %, 출고 %',v_row.item_number,v_before,v_row.qty;end if;update inventory_items set quantity=v_after,updated_at=now(),updated_by=auth.uid() where item_number=v_item.item_number;insert into inventory_movements(item_number,movement_type,quantity,quantity_before,quantity_after,source,order_number,customer_id,customer_name,device_name,created_by) values(v_item.item_number,'OUT',v_row.qty,v_before,v_after,'ORDER_PICKING',p_order_number,v_customer_id,v_customer_name,coalesce(p_device_name,''),auth.uid());end loop;
 update orders set status='출고완료',picking_status=case when soldout_qty>0 then '부분품절 출고완료' else '검증완료' end,picking_verified_at=now(),picking_verified_by=auth.uid(),is_soldout=(soldout_qty>=qty) where order_number=p_order_number;return jsonb_build_object('ok',true,'order_number',p_order_number,'customer_name',v_customer_name);end;$$;grant execute on function public.complete_order_picking(text,text) to authenticated;