-- DESIGN SOCKS V6.3.4 관리자 로그인 기록 및 실시간 접속 상태

alter table public.customers add column if not exists last_login_at timestamptz;
alter table public.customers add column if not exists admin_last_seen_at timestamptz;
alter table public.customers add column if not exists admin_logged_out_at timestamptz;
alter table public.customers add column if not exists admin_device text;

create table if not exists public.admin_login_events (
  id bigint generated by default as identity primary key,
  admin_id uuid not null references auth.users(id) on delete cascade,
  logged_in_at timestamptz not null default now(),
  device_info text not null default '',
  user_agent text not null default ''
);

create index if not exists idx_admin_login_events_admin_time
  on public.admin_login_events(admin_id, logged_in_at desc);

alter table public.admin_login_events enable row level security;

create or replace function public.record_admin_login(
  p_device_info text default '',
  p_user_agent text default ''
) returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1 from public.customers
     where id = auth.uid() and is_admin = true and coalesce(blocked, false) = false
  ) then
    raise exception '사용 가능한 관리자 계정이 아닙니다.';
  end if;

  update public.customers
     set last_login_at = now(),
         admin_last_seen_at = now(),
         admin_logged_out_at = null,
         admin_device = left(coalesce(p_device_info, ''), 200)
   where id = auth.uid();

  insert into public.admin_login_events(admin_id, device_info, user_agent)
  values(auth.uid(), left(coalesce(p_device_info, ''), 200), left(coalesce(p_user_agent, ''), 500));
end;
$$;

create or replace function public.touch_admin_presence(
  p_device_info text default ''
) returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.customers
     set admin_last_seen_at = now(),
         admin_logged_out_at = null,
         admin_device = case
           when nullif(trim(coalesce(p_device_info, '')), '') is null then admin_device
           else left(p_device_info, 200)
         end
   where id = auth.uid()
     and is_admin = true
     and coalesce(blocked, false) = false;
end;
$$;

create or replace function public.record_admin_logout() returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.customers
     set admin_logged_out_at = now(),
         admin_last_seen_at = now()
   where id = auth.uid() and is_admin = true;
end;
$$;

create or replace function public.get_admin_presence()
returns table (
  id uuid,
  email text,
  business_name text,
  owner_name text,
  blocked boolean,
  created_at timestamptz,
  admin_role text,
  last_login_at timestamptz,
  admin_last_seen_at timestamptz,
  admin_logged_out_at timestamptz,
  admin_device text,
  today_login_count bigint
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1 from public.customers c
     where c.id = auth.uid()
       and c.is_admin = true
       and coalesce(c.blocked, false) = false
       and (
         c.admin_role = 'developer_admin'
         or lower(coalesce(c.email, '')) in (
           '900smk@naver.com',
           'sm0727sm@hanmail.net',
           'p1028p@naver.com'
         )
       )
  ) then
    raise exception '개발관리자만 전체 관리자 접속 현황을 볼 수 있습니다.';
  end if;

  return query
  select
    c.id,
    c.email::text,
    c.business_name::text,
    c.owner_name::text,
    coalesce(c.blocked, false),
    c.created_at,
    coalesce(c.admin_role, 'admin')::text,
    c.last_login_at,
    c.admin_last_seen_at,
    c.admin_logged_out_at,
    c.admin_device::text,
    (
      select count(*)
        from public.admin_login_events e
       where e.admin_id = c.id
         and e.logged_in_at >= (
           (now() at time zone 'Asia/Seoul')::date
           at time zone 'Asia/Seoul'
         )
    )::bigint
  from public.customers c
  where c.is_admin = true
  order by c.created_at asc;
end;
$$;

revoke all on function public.record_admin_login(text, text) from public;
revoke all on function public.touch_admin_presence(text) from public;
revoke all on function public.record_admin_logout() from public;
revoke all on function public.get_admin_presence() from public;
grant execute on function public.record_admin_login(text, text) to authenticated;
grant execute on function public.touch_admin_presence(text) to authenticated;
grant execute on function public.record_admin_logout() to authenticated;
grant execute on function public.get_admin_presence() to authenticated;
