-- DESIGN SOCKS V6.4.0 통합 안정화
-- 필수: Supabase SQL Editor에서 전체 실행

alter table public.orders add column if not exists picking_batch_id uuid;
alter table public.orders add column if not exists warehouse_code text;
alter table public.product_groups add column if not exists warehouse_code text;
alter table public.inventory_movements add column if not exists picking_batch_id uuid;

create table if not exists public.customer_item_prices (
  id bigint generated by default as identity primary key,
  customer_id uuid not null references public.customers(id) on delete cascade,
  item_number text not null,
  price integer not null check (price >= 0 and price % 50 = 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(customer_id,item_number)
);
alter table public.customer_item_prices enable row level security;
drop policy if exists customer_item_prices_select on public.customer_item_prices;
create policy customer_item_prices_select on public.customer_item_prices for select to authenticated
using (customer_id=auth.uid() or public.is_inventory_admin());
drop policy if exists customer_item_prices_admin_write on public.customer_item_prices;
create policy customer_item_prices_admin_write on public.customer_item_prices for all to authenticated
using (public.is_inventory_admin()) with check (public.is_inventory_admin());

create or replace function public.complete_order_picking(p_order_number text,p_device_name text default '피킹검증') returns jsonb
language plpgsql security definer set search_path=public as $$
declare v_customer_id text;v_customer_name text;v_bad integer;v_row record;v_item public.inventory_items;v_before integer;v_after integer;v_already integer;v_batch uuid:=gen_random_uuid();
begin
 if not public.is_inventory_admin() then raise exception '관리자 권한이 필요합니다.';end if;
 perform 1 from public.orders where order_number=p_order_number for update;
 select count(*) into v_bad from public.orders where order_number=p_order_number and coalesce(picked_qty,0)+coalesce(soldout_qty,0)<>coalesce(qty,0);
 if v_bad>0 then raise exception '피킹+품절 수량 불일치 품목이 %개 있습니다.',v_bad;end if;
 select count(*) into v_already from public.orders where order_number=p_order_number and coalesce(picking_status,'') in ('검증완료','부분품절 검증완료');
 if v_already>0 then raise exception '이미 피킹 최종검증이 완료된 주문입니다.';end if;
 select customer_id::text,coalesce(customer_name,'거래처 미입력') into v_customer_id,v_customer_name from public.orders where order_number=p_order_number limit 1;
 if not found then raise exception '주문을 찾을 수 없습니다.';end if;
 for v_row in select item_number,sum(coalesce(picked_qty,0))::integer as qty from public.orders where order_number=p_order_number group by item_number loop
  if v_row.qty<=0 then continue;end if;
  select * into v_item from public.inventory_items where item_number=trim(v_row.item_number) or barcode=trim(v_row.item_number) for update;
  if not found then raise exception '재고 미등록 품번: %',v_row.item_number;end if;
  v_before:=v_item.quantity;v_after:=v_before-v_row.qty;
  if v_after<0 then raise exception '재고 부족: % 현재 %, 출고 %',v_row.item_number,v_before,v_row.qty;end if;
  update public.inventory_items set quantity=v_after,updated_at=now(),updated_by=auth.uid() where item_number=v_item.item_number;
  insert into public.inventory_movements(item_number,movement_type,quantity,quantity_before,quantity_after,source,order_number,customer_id,customer_name,device_name,created_by,picking_batch_id)
  values(v_item.item_number,'OUT',v_row.qty,v_before,v_after,'ORDER_PICKING',p_order_number,v_customer_id,v_customer_name,coalesce(p_device_name,''),auth.uid(),v_batch);
 end loop;
 update public.orders set status='주문접수',picking_status=case when soldout_qty>0 then '부분품절 검증완료' else '검증완료' end,picking_verified_at=now(),picking_verified_by=auth.uid(),is_soldout=(soldout_qty>=qty),picking_batch_id=v_batch where order_number=p_order_number;
 return jsonb_build_object('ok',true,'order_number',p_order_number,'customer_name',v_customer_name,'next_status','출고대기','picking_batch_id',v_batch);
end;$$;

create or replace function public.reset_order_picking(p_order_number text,p_device_name text default '피킹 초기화') returns jsonb
language plpgsql security definer set search_path=public as $$
declare v_batch uuid;v_verified boolean;v_row record;v_item public.inventory_items;v_before integer;v_after integer;v_restored integer:=0;v_items integer:=0;v_customer_id text;v_customer_name text;
begin
 if not public.is_inventory_admin() then raise exception '관리자 권한이 필요합니다.';end if;
 select picking_batch_id,coalesce(picking_status,'') in ('검증완료','부분품절 검증완료'),customer_id::text,coalesce(customer_name,'거래처 미입력')
 into v_batch,v_verified,v_customer_id,v_customer_name from public.orders where order_number=p_order_number limit 1 for update;
 if not found then raise exception '주문을 찾을 수 없습니다.';end if;
 if v_verified then
  for v_row in
   select m.item_number,sum(m.quantity)::integer qty from public.inventory_movements m
   where m.order_number=p_order_number and m.movement_type='OUT' and m.source='ORDER_PICKING'
     and ((v_batch is not null and m.picking_batch_id=v_batch) or (v_batch is null and m.picking_batch_id is null))
     and not exists (select 1 from public.inventory_movements r where r.order_number=p_order_number and r.source='ORDER_PICKING_RESET' and r.picking_batch_id is not distinct from m.picking_batch_id)
   group by m.item_number
  loop
   select * into v_item from public.inventory_items where item_number=v_row.item_number for update;
   if not found then raise exception '복원할 재고 품번이 없습니다: %',v_row.item_number;end if;
   v_before:=v_item.quantity;v_after:=v_before+v_row.qty;
   update public.inventory_items set quantity=v_after,updated_at=now(),updated_by=auth.uid() where item_number=v_item.item_number;
   insert into public.inventory_movements(item_number,movement_type,quantity,quantity_before,quantity_after,source,order_number,customer_id,customer_name,device_name,created_by,picking_batch_id)
   values(v_item.item_number,'IN',v_row.qty,v_before,v_after,'ORDER_PICKING_RESET',p_order_number,v_customer_id,v_customer_name,coalesce(p_device_name,''),auth.uid(),v_batch);
   v_restored:=v_restored+v_row.qty;v_items:=v_items+1;
  end loop;
 end if;
 update public.orders set picked_qty=0,soldout_qty=0,is_soldout=false,picking_status='대기',picking_started_at=null,picking_verified_at=null,picking_verified_by=null,picking_batch_id=null where order_number=p_order_number;
 return jsonb_build_object('ok',true,'restored_items',v_items,'restored_quantity',v_restored);
end;$$;
grant execute on function public.complete_order_picking(text,text) to authenticated;
grant execute on function public.reset_order_picking(text,text) to authenticated;
