-- DESIGN SOCKS V6.4.9 거래처·공장발주·전용단가 안정화
create table if not exists public.factory_orders (
  id bigint generated by default as identity primary key,
  factory_code text not null check (factory_code in ('S','B','I')),
  factory_order_number text not null unique,
  status text not null default '발주완료' check (status in ('발주완료','생산중','입고완료','취소')),
  items jsonb not null default '[]'::jsonb,
  source_order_numbers jsonb not null default '[]'::jsonb,
  note text not null default '',
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.factory_orders enable row level security;
drop policy if exists factory_orders_admin_select on public.factory_orders;
create policy factory_orders_admin_select on public.factory_orders for select to authenticated using (public.is_inventory_admin());
drop policy if exists factory_orders_admin_write on public.factory_orders;
create policy factory_orders_admin_write on public.factory_orders for all to authenticated using (public.is_inventory_admin()) with check (public.is_inventory_admin());
create index if not exists factory_orders_code_created_idx on public.factory_orders(factory_code,created_at desc);

-- 피킹 초기화 후 과거 검증상태가 남아 버튼이 잠기는 기존 데이터 복구
update public.orders set picking_status='대기',picking_started_at=null,picking_verified_at=null,picking_verified_by=null,picking_batch_id=null
where status='주문접수' and coalesce(picked_qty,0)=0 and coalesce(soldout_qty,0)=0
  and coalesce(picking_status,'대기')<>'대기';

-- 엑셀의 S-/B-/I- 접두어와 중복 단가를 실제 품번 한 건으로 정리합니다.
with ranked as (
  select id,row_number() over(
    partition by customer_id,regexp_replace(upper(trim(item_number)),'^[SBI][-_[:space:]]+','')
    order by updated_at desc nulls last,id desc
  ) as rn
  from public.customer_item_prices
)
delete from public.customer_item_prices p using ranked r where p.id=r.id and r.rn>1;
update public.customer_item_prices
set item_number=regexp_replace(upper(trim(item_number)),'^[SBI][-_[:space:]]+',''),updated_at=now()
where item_number<>regexp_replace(upper(trim(item_number)),'^[SBI][-_[:space:]]+','');

-- 일반 거래처 주문·관리자 대신주문 모두 저장 직전에 전용 단가를 강제 적용합니다.
create or replace function public.apply_customer_item_price_to_order()
returns trigger language plpgsql security definer set search_path=public as $$
declare v_price integer;
begin
  if new.customer_id is null then return new; end if;
  select p.price into v_price from public.customer_item_prices p
   where p.customer_id=new.customer_id
     and regexp_replace(upper(trim(p.item_number)),'^[SBI][-_[:space:]]+','')=
         regexp_replace(upper(trim(new.item_number)),'^[SBI][-_[:space:]]+','')
   order by p.updated_at desc nulls last,p.id desc limit 1;
  if found then new.price:=v_price;new.total:=greatest(0,coalesce(new.qty,0))*v_price;end if;
  return new;
end;$$;
drop trigger if exists orders_apply_customer_item_price on public.orders;
create trigger orders_apply_customer_item_price before insert on public.orders
for each row execute function public.apply_customer_item_price_to_order();

-- S/B/I 중 선택한 출고지의 모든 품번을 같은 재고 수량으로 설정합니다.
-- 품번마다 변경 전·후 수량과 사유를 ERP 작업이력에 남깁니다.
create or replace function public.bulk_set_inventory_by_warehouse(
  p_warehouse_code text,
  p_new_quantity integer,
  p_note text,
  p_device_name text default ''
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_code text := upper(trim(coalesce(p_warehouse_code,'')));
  v_item public.inventory_items%rowtype;
  v_matched integer := 0;
  v_changed integer := 0;
  v_difference integer;
begin
  if not public.is_inventory_admin() then
    raise exception '관리자 권한이 필요합니다.';
  end if;
  if v_code not in ('S','B','I') then
    raise exception '출고지는 S, B, I 중 하나여야 합니다.';
  end if;
  if p_new_quantity is null or p_new_quantity < 0 then
    raise exception '전체 적용 수량은 0 이상의 정수여야 합니다.';
  end if;
  if length(trim(coalesce(p_note,''))) < 1 then
    raise exception '일괄수정 사유를 입력하세요.';
  end if;

  for v_item in
    select * from public.inventory_items
     where upper(coalesce(warehouse_code,'')) = v_code
     order by item_number
     for update
  loop
    v_matched := v_matched + 1;
    if v_item.quantity = p_new_quantity then continue; end if;
    v_difference := abs(p_new_quantity - v_item.quantity);

    update public.inventory_items
       set quantity = p_new_quantity,
           updated_at = now(),
           updated_by = auth.uid()
     where item_number = v_item.item_number;

    insert into public.inventory_movements(
      item_number,movement_type,quantity,quantity_before,quantity_after,
      source,note,device_name,created_by
    ) values (
      v_item.item_number,'ADJUST',greatest(v_difference,1),v_item.quantity,p_new_quantity,
      'WAREHOUSE_SET_ALL',v_code || ' 출고지 전체 동일수량 설정: ' || trim(p_note),
      coalesce(p_device_name,''),auth.uid()
    );
    v_changed := v_changed + 1;
  end loop;

  if v_matched = 0 then
    raise exception '% 출고지에 등록된 재고 품번이 없습니다.', v_code;
  end if;
  return jsonb_build_object(
    'ok',true,
    'warehouse_code',v_code,
    'new_quantity',p_new_quantity,
    'matched_count',v_matched,
    'changed_count',v_changed
  );
end;
$$;

revoke all on function public.bulk_set_inventory_by_warehouse(text,integer,text,text) from public;
grant execute on function public.bulk_set_inventory_by_warehouse(text,integer,text,text) to authenticated;
