-- DESIGN SOCKS V6.4.8 피킹 안정화·생산공장 발주관리
create table if not exists public.factory_orders (
  id bigint generated by default as identity primary key,
  factory_code text not null check (factory_code in ('S','B','I')),
  factory_order_number text not null unique,
  status text not null default '발주완료' check (status in ('발주완료','생산중','입고완료','취소')),
  items jsonb not null default '[]'::jsonb,
  source_order_numbers jsonb not null default '[]'::jsonb,
  note text not null default '',
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.factory_orders enable row level security;
drop policy if exists factory_orders_admin_select on public.factory_orders;
create policy factory_orders_admin_select on public.factory_orders for select to authenticated using (public.is_inventory_admin());
drop policy if exists factory_orders_admin_write on public.factory_orders;
create policy factory_orders_admin_write on public.factory_orders for all to authenticated using (public.is_inventory_admin()) with check (public.is_inventory_admin());
create index if not exists factory_orders_code_created_idx on public.factory_orders(factory_code,created_at desc);

-- 피킹 초기화 후 과거 검증상태가 남아 버튼이 잠기는 기존 데이터 복구
update public.orders set picking_status='대기',picking_started_at=null,picking_verified_at=null,picking_verified_by=null,picking_batch_id=null
where status='주문접수' and coalesce(picked_qty,0)=0 and coalesce(soldout_qty,0)=0
  and coalesce(picking_status,'대기')<>'대기';

-- 엑셀에 S-품번/B-품번/I-품번으로 들어온 거래처 단가를 실제 품번과 같은 키로 정리합니다.
update public.customer_item_prices
set item_number=regexp_replace(upper(trim(item_number)),'^[SBI][-_[:space:]]+','')
where upper(trim(item_number)) ~ '^[SBI][-_[:space:]]+' 
  and not exists (
    select 1 from public.customer_item_prices x
    where x.customer_id=customer_item_prices.customer_id
      and upper(trim(x.item_number))=regexp_replace(upper(trim(customer_item_prices.item_number)),'^[SBI][-_[:space:]]+','')
      and x.id<>customer_item_prices.id
  );

-- S/B/I 중 선택한 출고지의 모든 품번을 같은 재고 수량으로 설정합니다.
-- 품번마다 변경 전·후 수량과 사유를 ERP 작업이력에 남깁니다.
create or replace function public.bulk_set_inventory_by_warehouse(
  p_warehouse_code text,
  p_new_quantity integer,
  p_note text,
  p_device_name text default ''
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_code text := upper(trim(coalesce(p_warehouse_code,'')));
  v_item public.inventory_items%rowtype;
  v_matched integer := 0;
  v_changed integer := 0;
  v_difference integer;
begin
  if not public.is_inventory_admin() then
    raise exception '관리자 권한이 필요합니다.';
  end if;
  if v_code not in ('S','B','I') then
    raise exception '출고지는 S, B, I 중 하나여야 합니다.';
  end if;
  if p_new_quantity is null or p_new_quantity < 0 then
    raise exception '전체 적용 수량은 0 이상의 정수여야 합니다.';
  end if;
  if length(trim(coalesce(p_note,''))) < 1 then
    raise exception '일괄수정 사유를 입력하세요.';
  end if;

  for v_item in
    select * from public.inventory_items
     where upper(coalesce(warehouse_code,'')) = v_code
     order by item_number
     for update
  loop
    v_matched := v_matched + 1;
    if v_item.quantity = p_new_quantity then continue; end if;
    v_difference := abs(p_new_quantity - v_item.quantity);

    update public.inventory_items
       set quantity = p_new_quantity,
           updated_at = now(),
           updated_by = auth.uid()
     where item_number = v_item.item_number;

    insert into public.inventory_movements(
      item_number,movement_type,quantity,quantity_before,quantity_after,
      source,note,device_name,created_by
    ) values (
      v_item.item_number,'ADJUST',greatest(v_difference,1),v_item.quantity,p_new_quantity,
      'WAREHOUSE_SET_ALL',v_code || ' 출고지 전체 동일수량 설정: ' || trim(p_note),
      coalesce(p_device_name,''),auth.uid()
    );
    v_changed := v_changed + 1;
  end loop;

  if v_matched = 0 then
    raise exception '% 출고지에 등록된 재고 품번이 없습니다.', v_code;
  end if;
  return jsonb_build_object(
    'ok',true,
    'warehouse_code',v_code,
    'new_quantity',p_new_quantity,
    'matched_count',v_matched,
    'changed_count',v_changed
  );
end;
$$;

revoke all on function public.bulk_set_inventory_by_warehouse(text,integer,text,text) from public;
grant execute on function public.bulk_set_inventory_by_warehouse(text,integer,text,text) to authenticated;
