-- DESIGN SOCKS V6.5.2 거래처별 단가 적용 보강
-- Supabase SQL Editor에서 전체 실행하세요.

create table if not exists public.customer_item_prices (
  id bigint generated by default as identity primary key,
  customer_id uuid not null references public.customers(id) on delete cascade,
  item_number text not null,
  price integer not null check (price >= 0 and price % 50 = 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(customer_id,item_number)
);

alter table public.customer_item_prices enable row level security;
drop policy if exists customer_item_prices_select on public.customer_item_prices;
create policy customer_item_prices_select on public.customer_item_prices
for select to authenticated
using (customer_id=auth.uid() or public.is_inventory_admin());

drop policy if exists customer_item_prices_admin_write on public.customer_item_prices;
create policy customer_item_prices_admin_write on public.customer_item_prices
for all to authenticated
using (public.is_inventory_admin())
with check (public.is_inventory_admin());

delete from public.customer_item_prices where price<=0;

create or replace function public.apply_customer_item_price_to_order()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare v_price integer;
begin
  if new.customer_id is null then return new; end if;
  select p.price into v_price
  from public.customer_item_prices p
  where p.customer_id=new.customer_id
    and regexp_replace(upper(trim(p.item_number)),'^[SBI][-_[:space:]]+','')=
        regexp_replace(upper(trim(new.item_number)),'^[SBI][-_[:space:]]+','')
  order by p.updated_at desc nulls last,p.id desc
  limit 1;
  if found then
    new.price:=v_price;
    new.total:=greatest(0,coalesce(new.qty,0))*v_price;
  end if;
  return new;
end;
$$;

drop trigger if exists orders_apply_customer_item_price on public.orders;
create trigger orders_apply_customer_item_price
before insert on public.orders
for each row execute function public.apply_customer_item_price_to_order();
