-- DESIGN SOCKS V6.5.69
-- 관리자 대신주문 통합 거래처 및 미가입 거래처별 납품처 저장·수정·삭제
-- 상품 단가, 거래처별 단가, orders.price/total은 변경하지 않습니다.

begin;

create table if not exists public.admin_proxy_parties(
  id bigint generated by default as identity primary key,
  customer_name text not null,
  normalized_name text not null unique,
  linked_customer_id uuid references public.customers(id) on delete set null,
  last_used_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_proxy_party_destinations(
  id bigint generated by default as identity primary key,
  party_id bigint not null references public.admin_proxy_parties(id) on delete cascade,
  delivery_name text not null,
  delivery_phone text,
  delivery_address text,
  normalized_destination text not null,
  last_used_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(party_id,normalized_destination)
);

alter table public.admin_proxy_parties enable row level security;
alter table public.admin_proxy_party_destinations enable row level security;
drop policy if exists admin_proxy_parties_admin on public.admin_proxy_parties;
create policy admin_proxy_parties_admin on public.admin_proxy_parties for all to authenticated
using(public.is_inventory_admin()) with check(public.is_inventory_admin());
drop policy if exists admin_proxy_destinations_admin on public.admin_proxy_party_destinations;
create policy admin_proxy_destinations_admin on public.admin_proxy_party_destinations for all to authenticated
using(public.is_inventory_admin()) with check(public.is_inventory_admin());

create or replace function public.proxy_normalized_text(p_value text) returns text
language sql immutable as $$
 select lower(regexp_replace(coalesce(trim(p_value),''),'[[:space:]_.·,(){}/-]+','','g'))
$$;

create or replace function public.save_admin_proxy_party_destination(
 p_customer_name text,p_linked_customer_id uuid,p_destination_id bigint,
 p_delivery_name text,p_delivery_phone text,p_delivery_address text
) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_party_id bigint;v_destination_id bigint;v_name_key text;v_destination_key text;
begin
 if not public.is_inventory_admin() then raise exception '관리자 권한이 필요합니다.'; end if;
 if nullif(trim(p_customer_name),'') is null then raise exception '거래처명이 필요합니다.'; end if;
 if nullif(trim(p_delivery_name),'') is null then raise exception '납품처명이 필요합니다.'; end if;
 v_name_key:=public.proxy_normalized_text(p_customer_name);
 v_destination_key:=public.proxy_normalized_text(p_delivery_name)||'|'||public.proxy_normalized_text(p_delivery_address);
 insert into public.admin_proxy_parties(customer_name,normalized_name,linked_customer_id,last_used_at,updated_at)
 values(trim(p_customer_name),v_name_key,p_linked_customer_id,now(),now())
 on conflict(normalized_name) do update set customer_name=excluded.customer_name,
  linked_customer_id=coalesce(excluded.linked_customer_id,admin_proxy_parties.linked_customer_id),last_used_at=now(),updated_at=now()
 returning id into v_party_id;
 if p_destination_id is not null then
  update public.admin_proxy_party_destinations set delivery_name=trim(p_delivery_name),delivery_phone=nullif(trim(p_delivery_phone),''),
   delivery_address=nullif(trim(p_delivery_address),''),normalized_destination=v_destination_key,last_used_at=now(),updated_at=now()
  where id=p_destination_id and party_id=v_party_id returning id into v_destination_id;
 end if;
 if v_destination_id is null then
  insert into public.admin_proxy_party_destinations(party_id,delivery_name,delivery_phone,delivery_address,normalized_destination,last_used_at,updated_at)
  values(v_party_id,trim(p_delivery_name),nullif(trim(p_delivery_phone),''),nullif(trim(p_delivery_address),''),v_destination_key,now(),now())
  on conflict(party_id,normalized_destination) do update set delivery_phone=excluded.delivery_phone,delivery_address=excluded.delivery_address,last_used_at=now(),updated_at=now()
  returning id into v_destination_id;
 end if;
 return jsonb_build_object('ok',true,'party_id',v_party_id,'destination_id',v_destination_id);
end $$;

create or replace function public.delete_admin_proxy_party_destination(p_destination_id bigint) returns jsonb
language plpgsql security definer set search_path=public as $$
begin
 if not public.is_inventory_admin() then raise exception '관리자 권한이 필요합니다.'; end if;
 delete from public.admin_proxy_party_destinations where id=p_destination_id;
 return jsonb_build_object('ok',true,'destination_id',p_destination_id);
end $$;

grant execute on function public.save_admin_proxy_party_destination(text,uuid,bigint,text,text,text) to authenticated;
grant execute on function public.delete_admin_proxy_party_destination(bigint) to authenticated;

-- 기존 관리자 대신주문 거래처와 납품처를 새 관리목록으로 이관합니다.
insert into public.admin_proxy_parties(customer_name,normalized_name,linked_customer_id,last_used_at)
select max(customer_name),public.proxy_normalized_text(customer_name),(array_agg(customer_id order by created_at desc) filter(where customer_id is not null))[1],max(created_at)
from public.orders where order_number like 'ADMIN-%' and nullif(trim(customer_name),'') is not null
group by public.proxy_normalized_text(customer_name)
on conflict(normalized_name) do update set last_used_at=greatest(admin_proxy_parties.last_used_at,excluded.last_used_at),linked_customer_id=coalesce(excluded.linked_customer_id,admin_proxy_parties.linked_customer_id);

insert into public.admin_proxy_party_destinations(party_id,delivery_name,delivery_phone,delivery_address,normalized_destination,last_used_at)
select p.id,max(o.delivery_name),max(o.delivery_phone),max(o.delivery_address),
 public.proxy_normalized_text(o.delivery_name)||'|'||public.proxy_normalized_text(o.delivery_address),max(o.created_at)
from public.orders o join public.admin_proxy_parties p on p.normalized_name=public.proxy_normalized_text(o.customer_name)
where o.order_number like 'ADMIN-%' and nullif(trim(o.delivery_name),'') is not null
group by p.id,public.proxy_normalized_text(o.delivery_name)||'|'||public.proxy_normalized_text(o.delivery_address)
on conflict(party_id,normalized_destination) do update set last_used_at=greatest(admin_proxy_party_destinations.last_used_at,excluded.last_used_at);

commit;

select 'V6.5.69 통합 거래처·납품처 저장/수정/삭제 적용 완료 - 단가 변경 없음' as result;
