-- DESIGN SOCKS V6.5.5 미가입·직접입력 거래처명 전용단가 적용
-- Supabase SQL Editor에서 전체 실행한 뒤, 상품관리에서 단가 엑셀을 다시 등록하세요.

create table if not exists public.customer_name_item_prices (
  id bigint generated by default as identity primary key,
  normalized_name text not null,
  customer_name text not null,
  item_number text not null,
  price integer not null check (price > 0 and price % 50 = 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(normalized_name,item_number)
);

alter table public.customer_name_item_prices enable row level security;
drop policy if exists customer_name_item_prices_admin on public.customer_name_item_prices;
create policy customer_name_item_prices_admin on public.customer_name_item_prices
for all to authenticated
using (public.is_inventory_admin()) with check (public.is_inventory_admin());

create or replace function public.normalize_customer_price_name(p_name text)
returns text language sql immutable parallel safe as $$
  select regexp_replace(lower(trim(coalesce(p_name,''))),'[[:space:]_.·,()\[\]{}\-/]+','','g');
$$;

create or replace function public.upsert_customer_name_item_prices(p_prices jsonb)
returns jsonb
language plpgsql security definer set search_path=public
as $$
declare
  v_row jsonb; v_name text; v_key text; v_item text; v_price integer; v_saved integer:=0;
begin
  if not public.is_inventory_admin() then raise exception '관리자 권한이 필요합니다.'; end if;
  if p_prices is null or jsonb_typeof(p_prices)<>'array' then raise exception '단가 자료 형식이 올바르지 않습니다.'; end if;
  for v_row in select * from jsonb_array_elements(p_prices)
  loop
    v_name:=trim(coalesce(v_row->>'customer_name',''));
    v_key:=public.normalize_customer_price_name(v_name);
    v_item:=regexp_replace(upper(trim(coalesce(v_row->>'item_number',''))),'^[SBI][-_[:space:]]+','');
    begin v_price:=(v_row->>'price')::integer; exception when others then continue; end;
    if v_key='' or v_item='' or v_price<=0 or mod(v_price,50)<>0 then continue; end if;
    insert into public.customer_name_item_prices(normalized_name,customer_name,item_number,price,updated_at)
    values(v_key,v_name,v_item,v_price,now())
    on conflict(normalized_name,item_number)
    do update set customer_name=excluded.customer_name,price=excluded.price,updated_at=now();
    v_saved:=v_saved+1;

    -- 같은 상호로 이미 가입한 거래처에도 동시에 연결합니다.
    insert into public.customer_item_prices(customer_id,item_number,price,updated_at)
    select c.id,v_item,v_price,now() from public.customers c
    where coalesce(c.is_admin,false)=false
      and public.normalize_customer_price_name(c.business_name)=v_key
    on conflict(customer_id,item_number)
    do update set price=excluded.price,updated_at=now();
  end loop;
  return jsonb_build_object('ok',true,'saved',v_saved);
end;
$$;

create or replace function public.get_customer_item_prices_by_name_for_admin(p_customer_name text)
returns table(item_number text,price integer)
language plpgsql stable security definer set search_path=public
as $$
begin
  if not public.is_inventory_admin() then raise exception '관리자 권한이 필요합니다.'; end if;
  return query
  select p.item_number,p.price from public.customer_name_item_prices p
  where p.normalized_name=public.normalize_customer_price_name(p_customer_name) and p.price>0
  order by p.item_number;
end;
$$;

-- 이미 가입했지만 ID 단가가 아직 복사되지 않은 계정도 상호명 단가를 즉시 사용합니다.
create or replace function public.get_customer_item_prices_for_admin(p_customer_id uuid)
returns table(item_number text,price integer)
language plpgsql stable security definer set search_path=public
as $$
begin
  if not public.is_inventory_admin() then raise exception '관리자 권한이 필요합니다.'; end if;
  return query
  select distinct on (source.item_number) source.item_number,source.price
  from (
    select p.item_number,p.price,1 as priority from public.customer_item_prices p where p.customer_id=p_customer_id and p.price>0
    union all
    select np.item_number,np.price,2 as priority
    from public.customer_name_item_prices np
    join public.customers c on c.id=p_customer_id
    where np.normalized_name=public.normalize_customer_price_name(c.business_name) and np.price>0
  ) source
  order by source.item_number,source.priority;
end;
$$;

create or replace function public.get_my_customer_item_prices()
returns table(item_number text,price integer)
language sql stable security definer set search_path=public
as $$
  select distinct on (source.item_number) source.item_number,source.price
  from (
    select p.item_number,p.price,1 as priority from public.customer_item_prices p where p.customer_id=auth.uid() and p.price>0
    union all
    select np.item_number,np.price,2 as priority
    from public.customer_name_item_prices np
    join public.customers c on c.id=auth.uid()
    where np.normalized_name=public.normalize_customer_price_name(c.business_name) and np.price>0
  ) source
  order by source.item_number,source.priority;
$$;

create or replace function public.apply_customer_item_price_to_order()
returns trigger language plpgsql security definer set search_path=public as $$
declare v_price integer; v_name text;
begin
  if new.customer_id is null then return new; end if;
  select p.price into v_price from public.customer_item_prices p
   where p.customer_id=new.customer_id
     and regexp_replace(upper(trim(p.item_number)),'^[SBI][-_[:space:]]+','')=regexp_replace(upper(trim(new.item_number)),'^[SBI][-_[:space:]]+','')
   order by p.updated_at desc nulls last,p.id desc limit 1;
  if not found then
    select business_name into v_name from public.customers where id=new.customer_id;
    select p.price into v_price from public.customer_name_item_prices p
     where p.normalized_name=public.normalize_customer_price_name(v_name)
       and regexp_replace(upper(trim(p.item_number)),'^[SBI][-_[:space:]]+','')=regexp_replace(upper(trim(new.item_number)),'^[SBI][-_[:space:]]+','')
     order by p.updated_at desc nulls last,p.id desc limit 1;
  end if;
  if v_price is not null then new.price:=v_price;new.total:=greatest(0,coalesce(new.qty,0))*v_price;end if;
  return new;
end;$$;

drop trigger if exists orders_apply_customer_item_price on public.orders;
create trigger orders_apply_customer_item_price before insert on public.orders
for each row execute function public.apply_customer_item_price_to_order();

revoke all on function public.upsert_customer_name_item_prices(jsonb) from public;
revoke all on function public.get_customer_item_prices_by_name_for_admin(text) from public;
grant execute on function public.upsert_customer_name_item_prices(jsonb) to authenticated;
grant execute on function public.get_customer_item_prices_by_name_for_admin(text) to authenticated;
grant execute on function public.get_customer_item_prices_for_admin(uuid) to authenticated;
grant execute on function public.get_my_customer_item_prices() to authenticated;
