create table if not exists public.customer_share_document_profiles (
  id bigint generated by default as identity primary key,
  customer_id uuid not null references auth.users(id) on delete cascade,
  recipient_key text not null,
  recipient_name text not null,
  owner_name text,
  phone text,
  delivery_address text,
  document_json jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  unique(customer_id,recipient_key)
);
alter table public.customer_share_document_profiles enable row level security;
drop policy if exists customer_share_document_profiles_owner on public.customer_share_document_profiles;
create policy customer_share_document_profiles_owner on public.customer_share_document_profiles for all to authenticated
using(customer_id=auth.uid() and coalesce((select customer_grade from public.customers where id=auth.uid()),'일반') in ('우수','우수고객','VIP','VVIP'))
with check(customer_id=auth.uid() and coalesce((select customer_grade from public.customers where id=auth.uid()),'일반') in ('우수','우수고객','VIP','VVIP'));
grant select,insert,update,delete on public.customer_share_document_profiles to authenticated;
grant usage,select on sequence public.customer_share_document_profiles_id_seq to authenticated;
select 'V6.5.52 거래처 전달용 문서 적용 완료' as result;
