-- DESIGN SOCKS V6.5.32
-- 관리자 3등급, 중요작업 재인증, 저장 납품처 관리
-- 주의: 상품 단가, customer_item_prices, orders.price/total은 변경하지 않습니다.

alter table public.customers add column if not exists admin_role text not null default 'admin';
alter table public.customer_delivery_destinations add column if not exists is_default boolean not null default false;
alter table public.customer_delivery_destinations add column if not exists updated_at timestamptz not null default now();

create table if not exists public.admin_security_grants(
  user_id uuid primary key references auth.users(id) on delete cascade,
  password_verified_until timestamptz,
  email_verified_until timestamptz,
  updated_at timestamptz not null default now()
);
alter table public.admin_security_grants enable row level security;
drop policy if exists admin_security_own on public.admin_security_grants;
create policy admin_security_own on public.admin_security_grants for select to authenticated using(user_id=auth.uid());

create table if not exists public.delivery_destination_history(
  id bigint generated by default as identity primary key,
  destination_id bigint,
  customer_id uuid,
  action text not null,
  snapshot jsonb,
  changed_by uuid,
  changed_at timestamptz not null default now()
);
alter table public.delivery_destination_history enable row level security;
drop policy if exists delivery_history_admin_read on public.delivery_destination_history;
create policy delivery_history_admin_read on public.delivery_destination_history for select to authenticated
using(public.is_inventory_admin() and coalesce((select admin_role from public.customers where id=auth.uid()),'employee') in ('admin','developer_admin'));

create or replace function public.current_admin_role() returns text
language sql stable security definer set search_path=public as $$
  select case when c.is_admin=true and c.blocked is not true then coalesce(c.admin_role,'admin') else null end
  from public.customers c where c.id=auth.uid()
$$;
grant execute on function public.current_admin_role() to authenticated;

create or replace function public.mark_admin_password_verified() returns jsonb
language plpgsql security definer set search_path=public as $$
begin
  if public.current_admin_role() not in ('admin','developer_admin') then raise exception '관리자 권한이 필요합니다.'; end if;
  insert into public.admin_security_grants(user_id,password_verified_until,updated_at)
  values(auth.uid(),now()+interval '10 minutes',now()) on conflict(user_id) do update
  set password_verified_until=excluded.password_verified_until,updated_at=now();
  return jsonb_build_object('ok',true,'verified_until',now()+interval '10 minutes');
end $$;
grant execute on function public.mark_admin_password_verified() to authenticated;

create or replace function public.mark_admin_email_verified() returns jsonb
language plpgsql security definer set search_path=public as $$
begin
  if public.current_admin_role()<>'developer_admin' then raise exception '개발관리자 권한이 필요합니다.'; end if;
  insert into public.admin_security_grants(user_id,email_verified_until,updated_at)
  values(auth.uid(),now()+interval '10 minutes',now()) on conflict(user_id) do update
  set email_verified_until=excluded.email_verified_until,updated_at=now();
  return jsonb_build_object('ok',true,'verified_until',now()+interval '10 minutes');
end $$;
grant execute on function public.mark_admin_email_verified() to authenticated;

create or replace function public.save_customer_delivery_destination(
 p_id bigint,p_delivery_name text,p_delivery_phone text,p_delivery_address text,p_is_default boolean default false
) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_customer uuid;v_id bigint;v_old jsonb;v_role text;
begin
  if nullif(trim(p_delivery_name),'') is null then raise exception '납품처명을 입력하세요.'; end if;
  if p_id is not null then select customer_id,to_jsonb(d) into v_customer,v_old from public.customer_delivery_destinations d where id=p_id for update;
  else v_customer:=auth.uid(); end if;
  v_role:=public.current_admin_role();
  if v_customer<>auth.uid() and v_role not in ('admin','developer_admin') then raise exception '납품처를 수정할 권한이 없습니다.'; end if;
  if p_is_default then update public.customer_delivery_destinations set is_default=false where customer_id=v_customer; end if;
  if p_id is null then
    insert into public.customer_delivery_destinations(customer_id,delivery_name,delivery_phone,delivery_address,is_default,last_used_at,updated_at)
    values(v_customer,trim(p_delivery_name),nullif(trim(p_delivery_phone),''),nullif(trim(p_delivery_address),''),p_is_default,now(),now()) returning id into v_id;
  else
    update public.customer_delivery_destinations set delivery_name=trim(p_delivery_name),delivery_phone=nullif(trim(p_delivery_phone),''),delivery_address=nullif(trim(p_delivery_address),''),is_default=p_is_default,updated_at=now() where id=p_id returning id into v_id;
  end if;
  insert into public.delivery_destination_history(destination_id,customer_id,action,snapshot,changed_by) values(v_id,v_customer,case when p_id is null then 'create' else 'update' end,v_old,auth.uid());
  return jsonb_build_object('ok',true,'id',v_id);
end $$;
grant execute on function public.save_customer_delivery_destination(bigint,text,text,text,boolean) to authenticated;

create or replace function public.delete_customer_delivery_destination(p_id bigint) returns jsonb
language plpgsql security definer set search_path=public as $$
declare v_row public.customer_delivery_destinations%rowtype;v_role text;
begin
  select * into v_row from public.customer_delivery_destinations where id=p_id for update;
  if not found then raise exception '납품처를 찾을 수 없습니다.'; end if;
  v_role:=public.current_admin_role();
  if v_row.customer_id<>auth.uid() and v_role not in ('admin','developer_admin') then raise exception '납품처를 삭제할 권한이 없습니다.'; end if;
  insert into public.delivery_destination_history(destination_id,customer_id,action,snapshot,changed_by) values(v_row.id,v_row.customer_id,'delete',to_jsonb(v_row),auth.uid());
  delete from public.customer_delivery_destinations where id=p_id;
  return jsonb_build_object('ok',true);
end $$;
grant execute on function public.delete_customer_delivery_destination(bigint) to authenticated;

-- 직원은 상세 거래처/전용단가를 조회하지 못하도록 별도 서버 함수에서도 차단합니다.
create or replace function public.require_manager_role() returns void language plpgsql security definer set search_path=public as $$
begin if public.current_admin_role() not in ('admin','developer_admin') then raise exception '관리자 이상 권한이 필요합니다.'; end if; end $$;
grant execute on function public.require_manager_role() to authenticated;

-- 직원이 다른 거래처의 저장 납품처와 전용단가 원본을 직접 조회하지 못하게 제한합니다.
drop policy if exists delivery_destination_manager_restrict on public.customer_delivery_destinations;
create policy delivery_destination_manager_restrict on public.customer_delivery_destinations as restrictive for all to authenticated
using(customer_id=auth.uid() or public.current_admin_role() in ('admin','developer_admin'))
with check(customer_id=auth.uid() or public.current_admin_role() in ('admin','developer_admin'));

alter table public.customer_item_prices enable row level security;
drop policy if exists customer_prices_manager_restrict on public.customer_item_prices;
create policy customer_prices_manager_restrict on public.customer_item_prices as restrictive for select to authenticated
using(customer_id=auth.uid() or public.current_admin_role() in ('admin','developer_admin'));

