-- DESIGN SOCKS V6.5.28
-- 거래처/대표자 관리, 납품처, 삭제주문 보관
-- 주문 단가(price/total) 및 거래처별 전용단가 테이블은 변경하지 않습니다.

alter table public.orders add column if not exists customer_owner_name text;
alter table public.orders add column if not exists delivery_name text;
alter table public.orders add column if not exists delivery_phone text;
alter table public.orders add column if not exists delivery_address text;

create table if not exists public.customer_delivery_destinations (
  id bigint generated by default as identity primary key,
  customer_id uuid not null references public.customers(id) on delete cascade,
  delivery_name text not null,
  delivery_phone text,
  delivery_address text,
  last_used_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique(customer_id, delivery_name, delivery_address)
);
alter table public.customer_delivery_destinations enable row level security;
drop policy if exists customer_delivery_own on public.customer_delivery_destinations;
create policy customer_delivery_own on public.customer_delivery_destinations
for all to authenticated using (customer_id=auth.uid() or public.is_inventory_admin())
with check (customer_id=auth.uid() or public.is_inventory_admin());

create table if not exists public.customer_identity_change_history (
  id bigint generated by default as identity primary key,
  customer_id uuid not null,
  old_business_name text,
  new_business_name text,
  old_owner_name text,
  new_owner_name text,
  changed_by uuid,
  changed_at timestamptz not null default now()
);
alter table public.customer_identity_change_history enable row level security;
drop policy if exists customer_identity_admin_read on public.customer_identity_change_history;
create policy customer_identity_admin_read on public.customer_identity_change_history
for select to authenticated using (public.is_inventory_admin());

create table if not exists public.deleted_order_history (
  id bigint generated by default as identity primary key,
  order_number text not null,
  customer_id uuid,
  customer_name text,
  deleted_by uuid,
  deleted_by_role text not null,
  delete_reason text,
  order_snapshot jsonb not null,
  deleted_at timestamptz not null default now()
);
create index if not exists deleted_order_history_order_idx on public.deleted_order_history(order_number);
create index if not exists deleted_order_history_customer_idx on public.deleted_order_history(customer_id,deleted_at desc);
alter table public.deleted_order_history enable row level security;
drop policy if exists deleted_order_admin_read on public.deleted_order_history;
create policy deleted_order_admin_read on public.deleted_order_history
for select to authenticated using (public.is_inventory_admin());
drop policy if exists deleted_order_customer_read on public.deleted_order_history;
create policy deleted_order_customer_read on public.deleted_order_history
for select to authenticated using (customer_id=auth.uid());

create or replace function public.admin_update_customer_identity(
  p_customer_id uuid,
  p_business_name text,
  p_owner_name text
) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_old public.customers%rowtype;
begin
  if not public.is_inventory_admin() then raise exception '관리자만 거래처 정보를 수정할 수 있습니다.'; end if;
  select * into v_old from public.customers where id=p_customer_id for update;
  if not found then raise exception '거래처를 찾을 수 없습니다.'; end if;
  if nullif(trim(p_business_name),'') is null then raise exception '거래처명을 입력하세요.'; end if;
  update public.customers set business_name=trim(p_business_name),owner_name=nullif(trim(p_owner_name),'') where id=p_customer_id;
  insert into public.customer_identity_change_history(customer_id,old_business_name,new_business_name,old_owner_name,new_owner_name,changed_by)
  values(p_customer_id,v_old.business_name,trim(p_business_name),v_old.owner_name,nullif(trim(p_owner_name),''),auth.uid());
  return jsonb_build_object('ok',true,'customer_id',p_customer_id);
end $$;
revoke all on function public.admin_update_customer_identity(uuid,text,text) from public;
grant execute on function public.admin_update_customer_identity(uuid,text,text) to authenticated;

create or replace function public.save_order_delivery_info(
  p_order_number text,
  p_owner_name text,
  p_delivery_name text,
  p_delivery_phone text,
  p_delivery_address text
) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_customer uuid; v_allowed boolean;
begin
  select customer_id into v_customer from public.orders where order_number=p_order_number limit 1;
  v_allowed := public.is_inventory_admin() or v_customer=auth.uid();
  if not v_allowed then raise exception '이 주문의 납품처를 수정할 권한이 없습니다.'; end if;
  update public.orders set customer_owner_name=nullif(trim(p_owner_name),''),delivery_name=nullif(trim(p_delivery_name),''),delivery_phone=nullif(trim(p_delivery_phone),''),delivery_address=nullif(trim(p_delivery_address),'') where order_number=p_order_number;
  if v_customer is not null and nullif(trim(p_delivery_name),'') is not null then
    insert into public.customer_delivery_destinations(customer_id,delivery_name,delivery_phone,delivery_address,last_used_at)
    values(v_customer,trim(p_delivery_name),nullif(trim(p_delivery_phone),''),nullif(trim(p_delivery_address),''),now())
    on conflict(customer_id,delivery_name,delivery_address) do update set delivery_phone=excluded.delivery_phone,last_used_at=now();
  end if;
  return jsonb_build_object('ok',true);
end $$;
revoke all on function public.save_order_delivery_info(text,text,text,text,text) from public;
grant execute on function public.save_order_delivery_info(text,text,text,text,text) to authenticated;

create or replace function public.delete_order_and_restore_inventory(p_order_number text,p_device_name text default '피킹 전 주문삭제')
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_rows jsonb; v_customer uuid; v_name text; v_deleted integer;
begin
  if not public.is_inventory_admin() then raise exception '관리자만 주문을 삭제할 수 있습니다.'; end if;
  if exists(select 1 from public.orders where order_number=p_order_number and (coalesce(picked_qty,0)>0 or coalesce(soldout_qty,0)>0 or coalesce(picking_status,'대기') not in ('','대기'))) then
    raise exception '피킹을 시작한 주문은 전체 삭제할 수 없습니다.';
  end if;
  select jsonb_agg(to_jsonb(o) order by o.id) into v_rows from public.orders o where order_number=p_order_number;
  select customer_id,customer_name into v_customer,v_name from public.orders where order_number=p_order_number limit 1;
  if v_rows is null then raise exception '주문을 찾을 수 없습니다.'; end if;
  insert into public.deleted_order_history(order_number,customer_id,customer_name,deleted_by,deleted_by_role,delete_reason,order_snapshot)
  values(p_order_number,v_customer,v_name,auth.uid(),'관리자',coalesce(nullif(trim(p_device_name),''),'피킹 전 주문삭제'),v_rows);
  delete from public.orders where order_number=p_order_number; get diagnostics v_deleted=row_count;
  return jsonb_build_object('ok',true,'order_number',p_order_number,'deleted_rows',v_deleted,'archived',true);
end $$;
revoke all on function public.delete_order_and_restore_inventory(text,text) from public;
grant execute on function public.delete_order_and_restore_inventory(text,text) to authenticated;

create or replace function public.customer_delete_pending_order(p_order_number text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_rows jsonb; v_name text; v_deleted integer;
begin
  if exists(select 1 from public.orders where order_number=p_order_number and customer_id=auth.uid() and (coalesce(picked_qty,0)>0 or coalesce(soldout_qty,0)>0 or coalesce(picking_status,'대기') not in ('','대기'))) then
    raise exception '피킹을 시작한 주문은 수정·삭제할 수 없습니다.';
  end if;
  select jsonb_agg(to_jsonb(o) order by o.id),min(customer_name) into v_rows,v_name from public.orders o where order_number=p_order_number and customer_id=auth.uid();
  if v_rows is null then raise exception '삭제할 주문을 찾을 수 없습니다.'; end if;
  insert into public.deleted_order_history(order_number,customer_id,customer_name,deleted_by,deleted_by_role,delete_reason,order_snapshot)
  values(p_order_number,auth.uid(),v_name,auth.uid(),'거래처','거래처 피킹 전 삭제',v_rows);
  delete from public.orders where order_number=p_order_number and customer_id=auth.uid(); get diagnostics v_deleted=row_count;
  return jsonb_build_object('ok',true,'deleted_rows',v_deleted,'archived',true);
end $$;
revoke all on function public.customer_delete_pending_order(text) from public;
grant execute on function public.customer_delete_pending_order(text) to authenticated;
