-- V6.6.69 거래처 관리메모
create table if not exists public.customer_admin_notes (
  id bigint generated by default as identity primary key,
  customer_id uuid not null references public.customers(id) on delete cascade,
  customer_name text not null default '',
  note_text text not null,
  created_by uuid not null references auth.users(id),
  created_by_name text not null default '',
  created_at timestamptz not null default now()
);
create index if not exists customer_admin_notes_customer_idx on public.customer_admin_notes(customer_id, created_at desc);
alter table public.customer_admin_notes enable row level security;
drop policy if exists "admins manage customer admin notes" on public.customer_admin_notes;
create policy "admins manage customer admin notes" on public.customer_admin_notes for all to authenticated
using (exists(select 1 from public.customers c where c.id=auth.uid() and c.is_admin=true and coalesce(c.blocked,false)=false))
with check (exists(select 1 from public.customers c where c.id=auth.uid() and c.is_admin=true and coalesce(c.blocked,false)=false));
