begin;

create table if not exists public.order_payment_records (
 id bigint generated by default as identity primary key,
 order_number text not null,
 customer_key text not null default '',
 customer_name text not null default '',
 order_amount numeric(14,2) not null default 0,
 paid_amount numeric(14,2) not null default 0 check (paid_amount>=0),
 payment_status text not null default '미입금' check (payment_status in ('미입금','일부입금','입금완료')),
 payment_account text,
 depositor_name text,
 paid_at timestamptz,
 memo text,
 confirmed_by uuid,
 confirmed_by_name text,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 unique(order_number,customer_key)
);
create index if not exists order_payment_records_status_idx on public.order_payment_records(payment_status,updated_at desc);

-- V6.6.4: 이 기능을 처음 적용하는 순간 이미 출고완료였던 과거 주문은 관리 대상에서 제외합니다.
-- 한 번 기준시각이 저장된 뒤에는 현재 미출고 주문과 이후 신규 주문의 입금이력이 출고완료 후에도 유지됩니다.
create table if not exists public.order_payment_feature_config (
 id boolean primary key default true check(id=true),
 activated_at timestamptz not null default now()
);
do $$
begin
 if not exists(select 1 from public.order_payment_feature_config where id=true) then
  delete from public.order_payment_records p
  where exists(
   select 1 from public.orders o
   where o.order_number=p.order_number
     and coalesce(o.customer_id::text,'')=p.customer_key
   group by o.order_number,coalesce(o.customer_id::text,'')
   having bool_and(coalesce(o.status,'주문접수')='출고완료')
  );
  insert into public.order_payment_feature_config(id,activated_at) values(true,now());
 end if;
end$$;

-- 설치 시점에 이미 피킹검증이 끝난 '출고대기' 주문부터 관리합니다.
-- 그 이전 주문은 입금완료로 간주하고 관리 대상에 넣지 않습니다.
insert into public.order_payment_records(order_number,customer_key,customer_name,order_amount,paid_amount,payment_status,created_at,updated_at)
select o.order_number,coalesce(o.customer_id::text,''),max(coalesce(o.customer_name,'')),
 sum(greatest(0,coalesce(o.qty,0)-case when coalesce(o.is_soldout,false) then coalesce(o.qty,0) else coalesce(o.soldout_qty,0) end)*coalesce(o.price,0))+max(coalesce(o.shipping_fee,0)),
 0,'미입금',min(coalesce(o.created_at,now())),now()
from public.orders o
where coalesce(o.status,'주문접수')='주문접수'
  and coalesce(o.picking_status,'') in ('검증완료','부분품절 검증완료')
group by o.order_number,coalesce(o.customer_id::text,'')
on conflict(order_number,customer_key) do nothing;

create or replace function public.initialize_order_payment_record() returns trigger language plpgsql security definer set search_path=public as $$
begin
 insert into public.order_payment_records(order_number,customer_key,customer_name,order_amount,paid_amount,payment_status,created_at,updated_at)
 values(new.order_number,coalesce(new.customer_id::text,''),coalesce(new.customer_name,''),0,0,'미입금',coalesce(new.created_at,now()),now())
 on conflict(order_number,customer_key) do update set customer_name=excluded.customer_name;
 return new;
end;$$;
drop trigger if exists orders_initialize_payment_record on public.orders;
create trigger orders_initialize_payment_record after insert on public.orders for each row execute function public.initialize_order_payment_record();

create table if not exists public.order_payment_history (
 id bigint generated by default as identity primary key,
 payment_record_id bigint references public.order_payment_records(id) on delete cascade,
 order_number text not null,
 customer_key text not null default '',
 previous_status text,
 new_status text not null,
 previous_paid_amount numeric(14,2),
 new_paid_amount numeric(14,2) not null,
 changed_by uuid,
 changed_by_name text,
 changed_at timestamptz not null default now()
);
alter table public.order_payment_records add column if not exists confirmed_by_name text;
alter table public.order_payment_history add column if not exists changed_by_name text;

create or replace function public.is_payment_admin() returns boolean language sql stable security definer set search_path=public as $$
 select exists(select 1 from public.customers c where c.id=auth.uid() and c.is_admin=true and coalesce(c.blocked,false)=false and coalesce(c.admin_role,'admin') not in ('manager','employee'));
$$;

alter table public.order_payment_records enable row level security;
alter table public.order_payment_history enable row level security;
drop policy if exists payment_records_admin_all on public.order_payment_records;
create policy payment_records_admin_all on public.order_payment_records for all to authenticated using(public.is_payment_admin()) with check(public.is_payment_admin());
drop policy if exists payment_history_admin_select on public.order_payment_history;
create policy payment_history_admin_select on public.order_payment_history for select to authenticated using(public.is_payment_admin());

create or replace function public.admin_save_order_payment(p_order_number text,p_customer_key text,p_customer_name text,p_order_amount numeric,p_paid_amount numeric,p_payment_account text default null,p_depositor_name text default null,p_paid_at timestamptz default null,p_memo text default null)
returns public.order_payment_records language plpgsql security definer set search_path=public as $$
declare v_old public.order_payment_records;v_new public.order_payment_records;v_status text;v_paid numeric:=greatest(coalesce(p_paid_amount,0),0);v_total numeric:=greatest(coalesce(p_order_amount,0),0);v_actor_name text;
begin
 if not public.is_payment_admin() then raise exception '일반 관리자 이상만 입금정보를 관리할 수 있습니다.';end if;
 if nullif(trim(p_order_number),'') is null then raise exception '주문번호가 없습니다.';end if;
 v_status:=case when v_paid<=0 then '미입금' when v_paid<v_total then '일부입금' else '입금완료' end;
 select coalesce(nullif(trim(business_name),''),nullif(trim(owner_name),''),nullif(trim(email),''),'관리자') into v_actor_name from public.customers where id=auth.uid();
 v_actor_name:=coalesce(v_actor_name,'관리자');
 select * into v_old from public.order_payment_records where order_number=p_order_number and customer_key=coalesce(p_customer_key,'');
 insert into public.order_payment_records(order_number,customer_key,customer_name,order_amount,paid_amount,payment_status,payment_account,depositor_name,paid_at,memo,confirmed_by,confirmed_by_name,updated_at)
 values(trim(p_order_number),coalesce(p_customer_key,''),coalesce(p_customer_name,''),v_total,v_paid,v_status,nullif(trim(p_payment_account),''),nullif(trim(p_depositor_name),''),case when v_paid>0 then coalesce(p_paid_at,now()) else null end,nullif(trim(p_memo),''),auth.uid(),v_actor_name,now())
 on conflict(order_number,customer_key) do update set customer_name=excluded.customer_name,order_amount=excluded.order_amount,paid_amount=excluded.paid_amount,payment_status=excluded.payment_status,payment_account=excluded.payment_account,depositor_name=excluded.depositor_name,paid_at=excluded.paid_at,memo=excluded.memo,confirmed_by=auth.uid(),confirmed_by_name=v_actor_name,updated_at=now() returning * into v_new;
 insert into public.order_payment_history(payment_record_id,order_number,customer_key,previous_status,new_status,previous_paid_amount,new_paid_amount,changed_by,changed_by_name) values(v_new.id,v_new.order_number,v_new.customer_key,v_old.payment_status,v_new.payment_status,v_old.paid_amount,v_new.paid_amount,auth.uid(),v_actor_name);
 return v_new;
end;$$;
revoke all on function public.admin_save_order_payment(text,text,text,numeric,numeric,text,text,timestamptz,text) from public;
grant execute on function public.admin_save_order_payment(text,text,text,numeric,numeric,text,text,timestamptz,text) to authenticated;
grant execute on function public.is_payment_admin() to authenticated;
commit;
