begin;

create table if not exists public.order_payment_records (
 id bigint generated by default as identity primary key,
 order_number text not null,
 customer_key text not null default '',
 customer_name text not null default '',
 order_amount numeric(14,2) not null default 0,
 paid_amount numeric(14,2) not null default 0 check (paid_amount>=0),
 payment_status text not null default '미입금' check (payment_status in ('미입금','일부입금','입금완료')),
 payment_account text,
 depositor_name text,
 paid_at timestamptz,
 memo text,
 confirmed_by uuid,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 unique(order_number,customer_key)
);
create index if not exists order_payment_records_status_idx on public.order_payment_records(payment_status,updated_at desc);

create table if not exists public.order_payment_history (
 id bigint generated by default as identity primary key,
 payment_record_id bigint references public.order_payment_records(id) on delete cascade,
 order_number text not null,
 customer_key text not null default '',
 previous_status text,
 new_status text not null,
 previous_paid_amount numeric(14,2),
 new_paid_amount numeric(14,2) not null,
 changed_by uuid,
 changed_at timestamptz not null default now()
);

create or replace function public.is_payment_admin() returns boolean language sql stable security definer set search_path=public as $$
 select exists(select 1 from public.customers c where c.id=auth.uid() and c.is_admin=true and coalesce(c.blocked,false)=false and coalesce(c.admin_role,'admin') not in ('manager','employee'));
$$;

alter table public.order_payment_records enable row level security;
alter table public.order_payment_history enable row level security;
drop policy if exists payment_records_admin_all on public.order_payment_records;
create policy payment_records_admin_all on public.order_payment_records for all to authenticated using(public.is_payment_admin()) with check(public.is_payment_admin());
drop policy if exists payment_history_admin_select on public.order_payment_history;
create policy payment_history_admin_select on public.order_payment_history for select to authenticated using(public.is_payment_admin());

create or replace function public.admin_save_order_payment(p_order_number text,p_customer_key text,p_customer_name text,p_order_amount numeric,p_paid_amount numeric,p_payment_account text default null,p_depositor_name text default null,p_paid_at timestamptz default null,p_memo text default null)
returns public.order_payment_records language plpgsql security definer set search_path=public as $$
declare v_old public.order_payment_records;v_new public.order_payment_records;v_status text;v_paid numeric:=greatest(coalesce(p_paid_amount,0),0);v_total numeric:=greatest(coalesce(p_order_amount,0),0);
begin
 if not public.is_payment_admin() then raise exception '일반 관리자 이상만 입금정보를 관리할 수 있습니다.';end if;
 if nullif(trim(p_order_number),'') is null then raise exception '주문번호가 없습니다.';end if;
 v_status:=case when v_paid<=0 then '미입금' when v_paid<v_total then '일부입금' else '입금완료' end;
 select * into v_old from public.order_payment_records where order_number=p_order_number and customer_key=coalesce(p_customer_key,'');
 insert into public.order_payment_records(order_number,customer_key,customer_name,order_amount,paid_amount,payment_status,payment_account,depositor_name,paid_at,memo,confirmed_by,updated_at)
 values(trim(p_order_number),coalesce(p_customer_key,''),coalesce(p_customer_name,''),v_total,v_paid,v_status,nullif(trim(p_payment_account),''),nullif(trim(p_depositor_name),''),case when v_paid>0 then coalesce(p_paid_at,now()) else null end,nullif(trim(p_memo),''),auth.uid(),now())
 on conflict(order_number,customer_key) do update set customer_name=excluded.customer_name,order_amount=excluded.order_amount,paid_amount=excluded.paid_amount,payment_status=excluded.payment_status,payment_account=excluded.payment_account,depositor_name=excluded.depositor_name,paid_at=excluded.paid_at,memo=excluded.memo,confirmed_by=auth.uid(),updated_at=now() returning * into v_new;
 insert into public.order_payment_history(payment_record_id,order_number,customer_key,previous_status,new_status,previous_paid_amount,new_paid_amount,changed_by) values(v_new.id,v_new.order_number,v_new.customer_key,v_old.payment_status,v_new.payment_status,v_old.paid_amount,v_new.paid_amount,auth.uid());
 return v_new;
end;$$;
revoke all on function public.admin_save_order_payment(text,text,text,numeric,numeric,text,text,timestamptz,text) from public;
grant execute on function public.admin_save_order_payment(text,text,text,numeric,numeric,text,text,timestamptz,text) to authenticated;
grant execute on function public.is_payment_admin() to authenticated;
commit;
