-- DESIGN SOCKS V6.6.82 거래처 주문 알림 / 자주 쓰는 메시지
create table if not exists public.customer_notification_templates (
  id bigint generated by default as identity primary key,
  title text not null,
  message text not null,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.customer_order_notifications (
  id bigint generated by default as identity primary key,
  customer_id uuid not null references public.customers(id) on delete cascade,
  order_number text,
  message text not null,
  sent_by uuid references auth.users(id) on delete set null,
  sent_by_name text,
  created_at timestamptz not null default now(),
  read_at timestamptz
);

create index if not exists customer_order_notifications_customer_idx
on public.customer_order_notifications(customer_id, created_at desc);

alter table public.customer_notification_templates enable row level security;
alter table public.customer_order_notifications enable row level security;

drop policy if exists "admins manage notification templates" on public.customer_notification_templates;
create policy "admins manage notification templates" on public.customer_notification_templates
for all to authenticated
using (exists(select 1 from public.customers c where c.id=auth.uid() and c.is_admin=true and coalesce(c.blocked,false)=false))
with check (exists(select 1 from public.customers c where c.id=auth.uid() and c.is_admin=true and coalesce(c.blocked,false)=false));

drop policy if exists "admins manage customer notifications" on public.customer_order_notifications;
create policy "admins manage customer notifications" on public.customer_order_notifications
for all to authenticated
using (exists(select 1 from public.customers c where c.id=auth.uid() and c.is_admin=true and coalesce(c.blocked,false)=false))
with check (exists(select 1 from public.customers c where c.id=auth.uid() and c.is_admin=true and coalesce(c.blocked,false)=false));

drop policy if exists "customers read own notifications" on public.customer_order_notifications;
create policy "customers read own notifications" on public.customer_order_notifications
for select to authenticated using (customer_id=auth.uid());

drop policy if exists "customers acknowledge own notifications" on public.customer_order_notifications;
create policy "customers acknowledge own notifications" on public.customer_order_notifications
for update to authenticated using (customer_id=auth.uid()) with check (customer_id=auth.uid());

-- Realtime publication: 이미 등록된 경우 duplicate_object를 무시합니다.
do $$ begin
  alter publication supabase_realtime add table public.customer_order_notifications;
exception when duplicate_object then null;
end $$;

-- 고객은 메시지 내용은 바꿀 수 없고 본인 알림의 확인시간만 기록합니다.
drop policy if exists "customers acknowledge own notifications" on public.customer_order_notifications;

create or replace function public.customer_ack_order_notification(p_notification_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.customer_order_notifications
  set read_at = coalesce(read_at, now())
  where id = p_notification_id and customer_id = auth.uid();
end;
$$;

grant execute on function public.customer_ack_order_notification(bigint) to authenticated;
