-- DESIGN SOCKS V6.7.64 S/B/I 정산 기록
-- 기존 주문·매출·재고는 변경하지 않고 정산 결과와 원문만 별도 저장합니다.
create table if not exists public.warehouse_settlements (
  id bigint generated by default as identity primary key,
  settlement_date date not null,
  warehouse_code text not null check (warehouse_code in ('S','B','I')),
  customer_key text not null default '',
  customer_name text not null default '',
  representative_name text not null default '',
  erp_sales_amount numeric not null default 0 check (erp_sales_amount >= 0),
  supplier_cost_amount numeric not null default 0 check (supplier_cost_amount >= 0),
  settlement_amount numeric not null default 0,
  erp_order_numbers jsonb not null default '[]'::jsonb,
  parsed_items jsonb not null default '[]'::jsonb,
  raw_text text not null default '',
  note text not null default '',
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.warehouse_settlements enable row level security;
drop policy if exists warehouse_settlements_admin_select on public.warehouse_settlements;
create policy warehouse_settlements_admin_select on public.warehouse_settlements for select to authenticated using (public.is_inventory_admin());
drop policy if exists warehouse_settlements_admin_write on public.warehouse_settlements;
create policy warehouse_settlements_admin_write on public.warehouse_settlements for all to authenticated using (public.is_inventory_admin()) with check (public.is_inventory_admin());
create index if not exists warehouse_settlements_date_code_idx on public.warehouse_settlements(settlement_date desc,warehouse_code);

